openapi: 3.0.3
components:
  schemas:

    PageIndex:
      description: "Page index of the image from input list"
      type: integer

    Source:
      description: "Document data sources"
      type: string
      enum:
        - 'MRZ'
        - 'VISUAL'
        - 'BARCODE'
        - 'RFID'
        - 'MAGNETIC'

    CheckResult:
      type: integer
      enum:
        - 0
        - 1
        - 2
      x-enum-varnames:
        - 'ERROR'
        - 'OK'
        - 'WAS_NOT_DONE'
      x-enum-descriptions:
        - 'Check was performed and result is NEGATIVE'
        - 'Check was performed and result is POSITIVE'
        - 'Check was NOT PERFORMED'

    # todo update x-enum-descriptions
    Scenario:
      type: string
      description: "Document processing scenario"
      enum:
        - "Mrz"
        - "Barcode"
        - "Locate"
        - "Ocr"
        - "DocType"
        - "MrzOrBarcode"
        - "MrzOrLocate"
        - "MrzAndLocate"
        - "MrzOrOcr"
        - "MrzOrBarcodeOrOcr"
        - "LocateVisual_And_MrzOrOcr"
        - "FullProcess"
        - "FullAuth"
        - "Id3Rus"
        - "RusStamp"
        - "OcrFree"
        - "CreditCard"
        - "Capture"
      x-enum-varnames:
        - "MRZ"
        - "BARCODE"
        - "LOCATE"
        - "OCR"
        - "DOCTYPE"
        - "MRZ_OR_BARCODE"
        - "MRZ_OR_LOCATE"
        - "MRZ_AND_LOCATE"
        - "MRZ_OR_OCR"
        - "MRZ_OR_BARCODE_OR_OCR"
        - "LOCATE_VISUAL_AND_MRZ_OR_OCR"
        - "FULL_PROCESS"
        - "FULL_AUTH"
        - "ID3RUS"
        - "RUS_STAMP"
        - "OCR_FREE"
        - "CREDIT_CARD"
        - "CAPTURE"

    ImageData:
      type: object
      required:
        - image
      properties:
        image:
          description: "base64 encoded image"
          type: string
          format: byte

    RectangleCoordinates:
      description: "Coordinates of the rectangle region in the normalized image of the document."
      type: object
      required:
        - left
        - top
        - right
        - bottom
      properties:
        left:
          type: integer
        top:
          type: integer
        right:
          type: integer
        bottom:
          type: integer

    RfidLocation:
      type: integer
      description: "Determines the presence and location of an RFID chip in a document"
      enum:
        - 0
        - 1
        - 2
      x-enum-descriptions:
        - 'There is no RFID chip in the document'
        - 'The RFID chip is located in the document data page'
        - 'The RFID chip is located in the back page or inlay of the document'
      x-enum-varnames:
        - 'NONE'
        - 'MAIN_PAGE'
        - 'BACK_PAGE'

    Light:
      type: integer
      description: "image light index"
      enum:
        - 0
        - 6
        - 24
        - 128
      x-enum-descriptions:
        - 'No Light'
        - 'White'
        - 'Infrared'
        - 'Ultraviolet'
      x-enum-varnames:
        - "OFF"
        - "WHITE"
        - "IR"
        - "UV"
