openapi: 3.0.4
components:
  parameters:
    x-request:
      in: header
      name: X-RequestID
      schema:
        type: string
        description: It allows the client and server to correlate each HTTP request. HTTP requests with an identifier are sent from the client to the server and back again. 

  schemas:
    PageIndex:
      title: "PageIndex"
      description: "Page index of the image from input list"
      type: integer

    Source:
      title: "Source"
      description: "Document data sources"
      type: string
      enum:
        - "MRZ"
        - "VISUAL"
        - "BARCODE"
        - "RFID"
        - "MAGNETIC"
        - "EXTERNAL"
      x-enum-varnames:
        - "MRZ"
        - "VISUAL"
        - "BARCODE"
        - "RFID"
        - "MAGNETIC"
        - "EXTERNAL"
      x-enum-descriptions:
        - "Machine readable zone (MRZ)"
        - "Visual zone"
        - "Barcode"
        - "RFID"
        - "Magnetic"
        - "External"

    CheckResult:
      title: "CheckResult"
      type: integer
      description: "0 - result is negative; 1 - result is positive; 2 - сheck was not performed"
      enum:
        - 0
        - 1
        - 2
      x-enum-varnames:
        - "ERROR"
        - "OK"
        - "WAS_NOT_DONE"
      x-enum-descriptions:
        - "Check was performed and result is NEGATIVE"
        - "Check was performed and result is POSITIVE"
        - "Check was NOT PERFORMED"

    Scenario:
      title: "Scenario"
      type: string
      description: "Document processing scenario"
      enum:
        - "Mrz"
        - "Barcode"
        - "Locate"
        - "Ocr"
        - "DocType"
        - "MrzOrBarcode"
        - "MrzOrLocate"
        - "MrzAndLocate"
        - "BarcodeAndLocate"
        - "MrzOrOcr"
        - "MrzOrBarcodeOrOcr"
        - "LocateVisual_And_MrzOrOcr"
        - "FullProcess"
        - "FullAuth"
        - "RusStamp"
        - "OcrFree"
        - "CreditCard"
        - "Capture"
        - "DTC"
      x-enum-varnames:
        - "MRZ"
        - "BARCODE"
        - "LOCATE"
        - "OCR"
        - "DOCTYPE"
        - "MRZ_OR_BARCODE"
        - "MRZ_OR_LOCATE"
        - "MRZ_AND_LOCATE"
        - "BARCODE_AND_LOCATE"
        - "MRZ_OR_OCR"
        - "MRZ_OR_BARCODE_OR_OCR"
        - "LOCATE_VISUAL_AND_MRZ_OR_OCR"
        - "FULL_PROCESS"
        - "FULL_AUTH"
        - "RUS_STAMP"
        - "OCR_FREE"
        - "CREDIT_CARD"
        - "CAPTURE"
        - "DTC"
      x-enum-descriptions:
        - "Processing scenario for obtaining MRZ data"
        - "Processing scenario for obtaining barcode data"
        - "Processing scenario for detecting document boundaries"
        - "Processing scenario for obtaining visual zone OCR results"
        - "Processing scenario for document type recognition"
        - "Processing scenario for obtaining MRZ and/or barcode data"
        - "Processing scenario for detecting document boundaries and/or obtaining MRZ data"
        - "Processing scenario for detecting document boundaries and obtaining MRZ data"
        - "Processing scenario for detecting the document boundaries and obtaining barcode data"
        - "Processing scenario for obtaining MRZ data or visual zone OCR results"
        - "Processing scenario for obtaining MRZ or barcode or visual zone OCR results"
        - "Processing scenario for detecting document boundaries and obtaining MRZ data or visual zone OCR results"
        - "Processing scenario for obtaining all document data"
        - "Processing scenario for obtaining all document data and document authentication"
        - "Processing scenario for obtaining data from registration stamps"
        - "Processing scenario for obtaining OCR results of any image"
        - "Processing scenario for obtaining bank card data"
        - "Scenario for obtaining an original image without any processing"
        - "Processing scenario for Digital Travel Credentials (DTC-VC) data processing"

    ImageData:
      title: "ImageData"
      type: object
      required:
        - image
      properties:
        image:
          $ref: "#/components/schemas/ImageBase64"
        format:
          description: "Image format"
          type: string

    ImageTransactionData:
      title: "ImageTransactionData"
      type: object
      properties:
        image:
          $ref: './rt-images.yml#/components/schemas/ImagesFieldValue'

    ImageBase64:
      title: "ImageBase64"
      description: "Base64 encoded image"
      type: string
      format: base64
      example: "Base64 encoded image"

    RectangleCoordinates:
      title: "RectangleCoordinates"
      description: "Coordinates of the rectangle region on a document image(result type 1). Represented by two points - (left, top) + (right, bottom)"
      type: object
      required:
        - left
        - top
        - right
        - bottom
      properties:
        left:
          type: integer
        top:
          type: integer
        right:
          type: integer
        bottom:
          type: integer

    RfidLocation:
      title: "RfidLocation"
      type: integer
      description: "Determines the presence and location of an RFID chip in a document. 0 - no rfid chip; 1 - chip is located in the document data page; 2 - chip is located in the back page or inlay of the document"
      enum:
        - 0
        - 1
        - 2
      x-enum-descriptions:
        - "There is no RFID chip in the document"
        - "The RFID chip is located in the document data page"
        - "The RFID chip is located in the back page or inlay of the document"
      x-enum-varnames:
        - "NONE"
        - "MAIN_PAGE"
        - "BACK_PAGE"

    RfidOrigin:
      title: "RfidOrigin"
      type: object
      description: "Location of data in RFID chip"
      required:
        - dg
        - dgTag
        - tagEntry
        - entryView
      properties:
        dg:
          description: "Source data group file"
          type: integer
        dgTag:
          description: "Index of the source record of the image with biometric information in the information data group"
          type: integer
        tagEntry:
          description: "Index of the template in the record with biometric data"
          type: integer
        entryView:
          description: "Index of the variant of the biometric data template"
          type: integer

    Light:
      title: "Light"
      type: integer
      format: int64
      description: "Image light index"
      enum:
        - 0x00000000
        - 0x00000001
        - 0x00000002
        - 0x00000004
        - 0x00800000
        - 0x00000006
        - 0x00000008
        - 0x00000010
        - 0x01000000
        - 0x00000018
        - 0x02000000
        - 0x00000080
        - 0x04000000
        - 0x08000000
        - 0x10000000
        - 0x00000100
        - 0x00000400
        - 0x00000800
        - 0x00000200
        - 0x00001000
        - 0x00002000
        - 0x00000C00
        - 0x80000000
        - 0x90000000
        - 0xA0000000
        - 0xB0000000
        - 0xC0000000
        - 0x00000020
        - 0x00000040
        - 0x00010000
        - 0x00004000
        - 0x00040000
        - 0x00020000
        - 0x00008000
        - 0x01000000
        - 0x04000000
        - 0x00000040
        - 0x00000020
        - 0x00080000
        - 0x00100000
        - 0x00200000
        - 0x00400000
      x-enum-descriptions:
        - "Lighting schemes are off"
        - "OVI scheme"
        - "Upper/lower lighters of white light scheme"
        - "Side lighters of white light scheme"
        - "General white light without separate control of side and upper/lower lighters scheme"
        - "Upper/lower and side lighters of white light scheme"
        - "Upper/lower lighters of IR light scheme"
        - "Side lighters of IR light scheme"
        - "General IR light without separate control of side and upper/lower lighters scheme"
        - "Upper/lower and side lighters of IR light scheme"
        - "general white image converted to grayscale"
        - "General UV light scheme"
        - "OVD light for hologram visualization"
        - "Video detection light for internal use only"
        - "Light IR 870 oblique"
        - "IR luminescence"
        - "Left lighter of white coaxial light scheme"
        - "Right lighter of white coaxial light scheme"
        - "Coaxial white light without separate control of left and right lighters scheme"
        - "IR720"
        - "IR940"
        - "Right and left lighters of white coaxial light scheme"
        - "For internal use"
        - "For internal use"
        - "For internal use"
        - "For internal use"
        - "For internal use"
        - "Transmitted"
        - "Transmitted IR"
        - "Transmitted AntiStokes"
        - "Transmitted IR940"
        - "OVD right"
        - "OVD left"
        - "IR 700"
        - "Front IR870 (mod. 8803)"
        - "OVD light (hologram visualization) (mod. 8850)"
        - "For internal use"
        - "For internal use"
        - "UVС 254 (mod. 88X0)"
        - "UVB 313 (mod. 88X0)"
        - "White oblique light"
        - "For internal use"
      x-enum-varnames:
        - "OFF"
        - "OVI"
        - "WHITE_TOP"
        - "WHITE_SIDE"
        - "WHITE_FRONT"
        - "WHITE"
        - "IR_TOP"
        - "IR_SIDE"
        - "IR_FRONT"
        - "IR"
        - "WHITE_GRAY"
        - "UV"
        - "OVD"
        - "VIDEODETECTION"
        - "IR_870_OBL"
        - "IR_LUMINESCENCE"
        - "AXIAL_WHITE_LEFT"
        - "AXIAL_WHITE_RIGHT"
        - "AXIAL_WHITE_FRONT"
        - "IR_720"
        - "IR_940"
        - "AXIAL_WHITE_FULL"
        - "RAW_DATA"
        - "RAW_DATA_GRBG"
        - "RAW_DATA_GBGR"
        - "RAW_DATA_RGGB"
        - "RAW_DATA_BGGR"
        - "TRANSMITTED"
        - "TRANSMITTED_IR"
        - "ANTI_STOKES"
        - "TRANSMITTED_IR940"
        - "OVD_RIGHT"
        - "OVD_LEFT"
        - "IR_700"
        - "IR_870"
        - "HOLO"
        - "IR_BOTTOM"
        - "WHITE_BOTTOM"
        - "UVC"
        - "UVB"
        - "WHITE_OBL"
        - "WHITE_SPECIAL"

    Point:
      title: "Point"
      type: object
      required:
        - x
        - y
      properties:
        x:
          type: integer
        y:
          type: integer

    License:
      title: "License"
      description: "Base64 encoded data"
      type: string
      format: byte
      example: "Base64 encoded data"

    EncryptedRCL:
      title: "EncryptedRCL"
      description: "Base64 encoded data"
      type: string
      format: byte
      example: "Base64 encoded data"

    FaceApi:
      title: "FaceApi"
      type: object
      properties:
        url:
          type: string
          example: "https://faceapi.regulaforensics.com"
          description: "The URL of the Regula Face Web service to be used."
        mode:
          type: string
          example: "match"
          description: "The processing mode: \"match\" or \"match+search\"."
        search:
          type: object
          description: "A search filter that can be applied if the \"match+search\" mode is enabled. May include limit, threshold, group_ids. If the group_ids are specified, the search is performed only in these groups. Find more information in the <a href=\"https://dev.regulaforensics.com/FaceSDK-web-openapi/#tag/search/operation/search\" target=\"_blank\">OpenAPI documentation</a>."
          properties:
            limit:
              type: integer
              description: "The maximum number of results to be returned."
            threshold:
              type: number
              format: float
              description: "The similarity threshold."
            group_ids:
              type: array
              items:
                type: integer
              description: " The groups where to conduct the search."
        threshold:
          type: integer
          example: 75
          description: "The similarity threshold, 0-100. Above 75 means that the faces' similarity is verified, below 75 is not."
        serviceTimeout:
          type: integer
          example: 3000
          description: "The Regula Face Web service requests timeout, ms."
        proxy:
          type: string
          example: "http://localhost:8080"
          description: "Proxy to use, should be set according to the <a href=\"https://curl.se/libcurl/c/CURLOPT_PROXY.html\" target=\"_blank\">cURL standard</a>."
        proxy_userpwd:
          type: string
          example: "user:pass"
          description: "Username and password to use for proxy authentication, should be set according to the <a href=\"https://curl.se/libcurl/c/CURLOPT_PROXYUSERPWD.html\" target=\"_blank\">cURL standard</a>."
        proxy_type:
          type: integer
          example: 0
          description: "Proxy protocol type, should be set according to the <a href=\"https://curl.se/libcurl/c/CURLOPT_PROXYTYPE.html\" target=\"_blank\">cURL standard</a>."
        childAgeThreshold:
          type: integer
          example: 13
          description: "Minimum age of a child, at which portrait comparison result will be effective. Default: 13."
        childDocValidityYears:
          type: integer
          example: 5
          description: "Estimated duration of validity for a child's passport, years. Default: 5."
