openapi: 3.0.4
components:
  schemas:
    BarcodeType:
      title: "BarcodeType"
      type: integer
      description: "Enumeration contains the types of barcodes that can be processed"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
      x-enum-varnames:
        - "UNKNOWN"
        - "CODE128"
        - "CODE39"
        - "EAN8"
        - "ITF"
        - "PDF417"
        - "STF"
        - "MTF"
        - "IATA"
        - "CODABAR"
        - "UPCA"
        - "CODE93"
        - "UPCE"
        - "EAN13"
        - "QRCODE"
        - "AZTEC"
        - "DATAMATRIX"
        - "ALL_1D"
        - "CODE11"
        - "JABCODE"
      x-enum-descriptions:
        - "Unknown"
        - "Code 128"
        - "Code 39"
        - "EAN-8"
        - "ITF"
        - "PDF417"
        - "STF"
        - "MTF"
        - "IATA"
        - "Codabar"
        - "UPC-A"
        - "Code 93"
        - "UPC-E"
        - "EAN-13"
        - "QR code"
        - "Aztec code"
        - "Datamatrix"
        - "All 1D barcodes"
        - "Code 11"
        - "JAB code"
