openapi: 3.0.3
components:
  schemas:

    GraphicFieldType:
      type: integer
      enum:
        - 201
        - 202
        - 203
        - 204
        - 205
        - 206
        - 207
        - 208
        - 209
        - 210
        - 211
        - 250
        - 300
        - 301
        - 302
        - 303
        - 304
        - 305
        - 306
        - 307
        - 308
        - 309
      x-enum-descriptions:
        - 'Document holder photo'
        - 'Fingerprint of document holder'
        - 'Image of the iris of document holder'
        - 'Signature of document holder'
        - 'Barcode image'
        - 'Image of document confirming owner citizenship'
        - 'Image of the front side of the document'
        - 'Image of the rear side of the document'
        - 'Area with dynamic color change'
        - 'Additional Portrait'
        - 'Stamp'
        - 'Undefined image type'
        - 'Fingerprint (thumb, left hand)'
        - 'Fingerprint (index, left hand)'
        - 'Fingerprint (middle, left hand)'
        - 'Fingerprint (ring, left hand)'
        - 'Fingerprint (little, left hand)'
        - 'Fingerprint (thumb, right hand)'
        - 'Fingerprint (index, right hand)'
        - 'Fingerprint (middle, right hand)'
        - 'Fingerprint (ring, right hand)'
        - 'Fingerprint (little, right hand)'
      x-enum-varnames:
        - 'PORTRAIT'
        - 'FINGERPRINT'
        - 'EYE'
        - 'SIGNATURE'
        - 'BAR_CODE'
        - 'PROOF_OF_CITIZENSHIP'
        - 'DOCUMENT_FRONT'
        - 'DOCUMENT_REAR'
        - 'COLOR_DYNAMIC'
        - 'GHOST_PORTRAIT'
        - 'STAMP'
        - 'OTHER'
        - 'FINGER_LEFT_THUMB'
        - 'FINGER_LEFT_INDEX'
        - 'FINGER_LEFT_MIDDLE'
        - 'FINGER_LEFT_RING'
        - 'FINGER_LEFT_LITTLE'
        - 'FINGER_RIGHT_THUMB'
        - 'FINGER_RIGHT_INDEX'
        - 'FINGER_RIGHT_MIDDLE'
        - 'FINGER_RIGHT_RING'
        - 'FINGER_RIGHT_LITTLE'
