openapi: 3.0.3
components:
  schemas:
    InputBarcodeType:
      type: integer
      description: "Enumeration contains the types of barcodes that can be processed"
      enum:
        - "bct_unknown"
        - "bct_Code128"
        - "bct_Code39"
        - "bct_EAN8"
        - "bct_ITF"
        - "bct_PDF417"
        - "bct_STF"
        - "bct_MTF"
        - "bct_IATA"
        - "bct_CODABAR"
        - "bct_UPCA"
        - "bct_CODE93"
        - "bct_UPCE"
        - "bct_EAN13"
        - "bct_QRCODE"
        - "bct_AZTEC"
        - "bct_DATAMATRIX"
        - "bct_ALL_1D"
        - "bct_Code11"
        - "bct_JABCODE"
      x-enum-varnames:
        - "Unknown"
        - "CODE128"
        - "CODE39"
        - "EAN8"
        - "ITF"
        - "PDF417"
        - "STF"
        - "MTF"
        - "IATA"
        - "CODABAR"
        - "UPCA"
        - "CODE93"
        - "UPCE"
        - "EAN13"
        - "QRCODE"
        - "AZTEC"
        - "DATAMATRIX"
        - "ALL_1D"
        - "CODE11"
        - "JABCODE"
      x-enum-descriptions:
        - "Unknown"
        - "Code 128"
        - "Code 39"
        - "EAN-8"
        - "ITF"
        - "PDF417"
        - "STF"
        - "MTF"
        - "IATA"
        - "Codabar"
        - "UPC-A"
        - "Code 93"
        - "UPC-E"
        - "EAN-13"
        - "QR code"
        - "Aztec code"
        - "Datamatrix"
        - "All 1D barcodes"
        - "Code 11"
        - "JAB code"
