openapi: 3.0.3
components:
  schemas:
    ParsingErrorCodes:
      title: "ParsingErrorCodes"
      type: integer
      format: int64
      description: "The enumeration contains error codes that can return during the RFID chip processing."
      enum:
        - 0x00000001
        - 0x80000001
        - 0x80000002
        - 0x80000003
        - 0x80000008
        - 0x80000009
        - 0x8000000A
        - 0x80000011
        - 0x80000013
        - 0x80000014
        - 0x80000015
        - 0x80000016
        - 0x80000012
        - 0x80000017
        - 0x80000018
        - 0x80000019
        - 0x8000001A
        - 0x8000001B
        - 0x8000001C
        - 0x8000001D
        - 0x8000001E
        - 0x8000001F
        - 0x80000020
        - 0x80000021
        - 0x80000022
        - 0x80000023
        - 0x80000024
        - 0x80000025
        - 0x80000026
        - 0x80000027
        - 0x80000030
        - 0x80000031
        - 0x80000032
        - 0x80000033
        - 0x80000034
        - 0x80000036
        - 0x80000035
        - 0x80000050
        - 0x80000051
        - 0x80000052
        - 0x80000053
        - 0x80000054
        - 0x80000055
        - 0x80000056
        - 0x80000057
        - 0x80000058
        - 0x80000059
        - 0x8000005A
        - 0x80000070
        - 0x80000071
        - 0x81000011
        - 0x81000020
        - 0x81000021
        - 0x81000022
        - 0x81000023
        - 0x81000024
        - 0x81000025
        - 0x81000026
        - 0x81000027
        - 0x81000028
        - 0x81000029
        - 0x8100002A
        - 0x8100002B
        - 0x8100002C
        - 0x8100002D
        - 0x8100002E
        - 0x8100002F
        - 0x81000030
        - 0x81000031
        - 0x81000032
        - 0x81000033
        - 0x81000034
        - 0x81000035
        - 0x81000036
        - 0x81000037
        - 0x81000038
        - 0x81000040
        - 0x81000041
        - 0x81000042
        - 0x81000043
        - 0x81000044
        - 0x81000045
        - 0x81000050
        - 0x81000051
        - 0x81000052
        - 0x81000053
        - 0x81000054
        - 0x81000055
        - 0x81000056
        - 0x81000057
        - 0x81000070
        - 0x81000071
        - 0x81000072
        - 0x81000060
        - 0x81000062
        - 0x81000063
        - 0x81000064
        - 0x81000065
        - 0x81000160
        - 0x81000161
        - 0x81000162
        - 0x81000163
        - 0x81000164
        - 0x81000165
        - 0x81000166
        - 0x81000167
        - 0x81000168
        - 0x81000169
        - 0x8100016A
        - 0x81000200
        - 0x81000201
        - 0x81000202
        - 0x81000203
        - 0x81000204
        - 0x81000205
        - 0x81000300
        - 0x81000301
        - 0x81000302
        - 0x81000303
        - 0x81000304
        - 0x81000305
        - 0x81000306
        - 0x81000307
        - 0x81000308
        - 0x81000309
        - 0x8100030A
      x-enum-descriptions:
        - "OK"
        - "ASN: Incorrect data"
        - "ASN: Not enough data"
        - "ASN: Contents unexpected data"
        - "ASN Signed data: Incorrect data"
        - "ASN Signed data: Encap contents incorrect data"
        - "ASN Signed data: Version incorrect data"
        - "ASN Signed data: Digest algorithms incorrect data"
        - "ASN LDS object: Incorrect data"
        - "ASN LDS object: Version incorrect data"
        - "ASN LDS object: Digest algorithm incorrect data"
        - "ASN LDS object: DG hashes incorrect data"
        - "ASN LDS object: Version info incorrect data"
        - "ASN Certificate: Incorrect data"
        - "ASN Certificate: Version incorrect data"
        - "ASN Certificate: SN incorrect data"
        - "ASN Certificate: Signature incorrect data"
        - "ASN Certificate: Issuer incorrect data"
        - "ASN Certificate: Validity incorrect data"
        - "ASN Certificate: Subject incorrect data"
        - "ASN Certificate: Subject PK incorrect data"
        - "ASN Certificate: Extensions incorrect data"
        - "ASN Signer info: Incorrect data"
        - "ASN Signer info: Version incorrect data"
        - "ASN Signer info: SID incorrect data"
        - "ASN Signer info: Digest algorithms incorrect data"
        - "ASN Signer info: Signed attributes incorrect data"
        - "ASN Signer info: Sign algorithms incorrect data"
        - "ASN Signer info: Signature incorrect data"
        - "ASN Signer info: Unsigned attributes incorrect data"
        - "ICAO LDS object: Unsupported digest algorithm"
        - "ICAO Signed data: Signer info empty"
        - "ICAO Signer info: Unsupported digest algorithm"
        - "ICAO Signer info: Unsupported signature algorithm"
        - "ICAO Signer info: Message digest error"
        - "ICAO Signer info: Signed attributes missed"
        - "Auth: Signer info cannot find certificate"
        - "Auth: Error"
        - "Auth: Unsupported signature algorithm"
        - "Auth: Unsupported public key algorithm"
        - "Auth: Messed algorithms"
        - "Auth: Public key data invalid"
        - "Auth: Algorithm parameters data invalid"
        - "Auth: Signature data invalid"
        - "Auth: Unsupported digest algorithm"
        - "Auth: Signature data incorrect"
        - "Auth: Algorithm parameters not defined"
        - "Auth: Signature check failed"
        - "DG: Wrong Tag"
        - "DG: Contents unexpected data"
        - "BAP: Symmetric Cypher Cannot Initialize"
        - "PACE: Info Not Available"
        - "PACE: Symmetric Cypher Cannot Initialize"
        - "PACE: Key Agreement Cannot Initialize"
        - "PACE: Ephemeral Keys Cannot Create"
        - "PACE: Mapping Cannot Decode Nonce"
        - "PACE: Shared Secret Cannot Create"
        - "PACE: Domain Params Unsupported Format"
        - "PACE: Ephemeral Keys Incorrect"
        - "PACE: Mapping Ephemeral Keys Incorrect"
        - "PACE: Mapping Cannot Perform"
        - "PACE: Non-Matching Auth Tokens"
        - "PACE: CAM data incorrect"
        - "PACE: CAM data cannot verify"
        - "PACE: CAM data non-matching"
        - "PACE: IM scheme incorrect"
        - "PACE: Random mapping failed"
        - "CA: Cannot Find Public Key"
        - "CA: Cannot Find Info"
        - "CA: Incorrect Version"
        - "CA: Cannot Find Domain Parameters"
        - "CA: Key Agreement Cannot Initialize"
        - "CA: Public Key Unsupported Algorithm"
        - "CA: Ephemeral Keys Cannot Create"
        - "CA: Shared Secret Cannot Create"
        - "CA: Non-Matching Auth Tokens"
        - "TA: Incorrect Version"
        - "TA: Cannot Build Certificate Chain"
        - "TA: Cannot Find IS Private Key"
        - "TA: Public Key Unsupported Algorithm"
        - "TA: Signature Building Error"
        - "TA: Invalid Key Algorithm Parameters"
        - "AA: Public Key Unsupported Algorithm"
        - "AA: Public Key Incorrect Data"
        - "AA: Public Key Incorrect Parameters"
        - "AA: Public Key Undefined Parameters"
        - "AA: Signature Incorrect Data"
        - "AA: Unsupported recovery scheme"
        - "AA: Incorrect Trailer"
        - "AA: Unsupported Digest Algorithm"
        - "RI: Sector Key Cannot Find"
        - "RI: Sector Key Incorrect Data"
        - "RI: Sector Key Incomplete Data"
        - "CV Certificate: Missing mandatory data PK"
        - "CV Certificate: Public key unsupported"
        - "CV Certificate: CHAT unsupported terminal type"
        - "CV Certificate: Private key unsupported"
        - "CV Certificate: Private key invalid params"
        - "CV Certificate: Incorrect data"
        - "CV Certificate: CPI incorrect data"
        - "CV Certificate: CAR incorrect data"
        - "CV Certificate: Public key incorrect data"
        - "CV Certificate: CHR incorrect data"
        - "CV Certificate: CHAT incorrect data"
        - "CV Certificate: Valid from incorrect data"
        - "CV Certificate: Valid to incorrect data"
        - "CV Certificate: Extensions incorrect data"
        - "CV Certificate: Private key incorrect data"
        - "CV Certificate: Private key missing"
        - "VDS: Unsupported version"
        - "VDS: Issuing country size"
        - "VDS: Issuing country incorrect data"
        - "VDS: Signature certificate size"
        - "VDS: Signature certificate data"
        - "VDS: Signature incorrect data"
        - "VDS: Incorrect data"
        - "VDS: Missing or incorrect data"
        - "VDS: Missing or incorrect header"
        - "VDS: Missing or incorrect type"
        - "VDS: Missing or incorrect version"
        - "VDS: Missing or incorrect issuing country"
        - "VDS: Missing or incorrect message"
        - "VDS: Missing or incorrect signature"
        - "VDS: Missing or incorrect signature algorithm"
        - "VDS: Missing or incorrect certificate"
        - "VDS: Missing or incorrect signature value"
      x-enum-varnames:
        - "errLDS_Ok"
        - "errLDS_ASN_IncorrectData"
        - "errLDS_ASN_NotEnoughData"
        - "errLDS_ASN_Contents_UnexpectedData"
        - "errLDS_ASN_SignedData_IncorrectData"
        - "errLDS_ASN_SignedData_EncapContents_IncorrectData"
        - "errLDS_ASN_SignedData_Version_IncorrectData"
        - "errLDS_ASN_SignedData_DigestAlgorithms_IncorrectData"
        - "errLDS_ASN_LDSObject_IncorrectData"
        - "errLDS_ASN_LDSObject_Version_IncorrectData"
        - "errLDS_ASN_LDSObject_DigestAlgorithm_IncorrectData"
        - "errLDS_ASN_LDSObject_DGHashes_IncorrectData"
        - "errLDS_ASN_LDSObject_VersionInfo_IncorrectData"
        - "errLDS_ASN_Certificate_IncorrectData"
        - "errLDS_ASN_Certificate_Version_IncorrectData"
        - "errLDS_ASN_Certificate_SN_IncorrectData"
        - "errLDS_ASN_Certificate_Signature_IncorrectData"
        - "errLDS_ASN_Certificate_Issuer_IncorrectData"
        - "errLDS_ASN_Certificate_Validity_IncorrectData"
        - "errLDS_ASN_Certificate_Subject_IncorrectData"
        - "errLDS_ASN_Certificate_SubjectPK_IncorrectData"
        - "errLDS_ASN_Certificate_Extensions_IncorrectData"
        - "errLDS_ASN_SignerInfo_IncorrectData"
        - "errLDS_ASN_SignerInfo_Version_IncorrectData"
        - "errLDS_ASN_SignerInfo_SID_IncorrectData"
        - "errLDS_ASN_SignerInfo_DigestAlg_IncorrectData"
        - "errLDS_ASN_SignerInfo_SignedAttrs_IncorrectData"
        - "errLDS_ASN_SignerInfo_SignAlg_IncorrectData"
        - "errLDS_ASN_SignerInfo_Signature_IncorrectData"
        - "errLDS_ASN_SignerInfo_UnsignedAttrs_IncorrectData"
        - "errLDS_ICAO_LDSObject_UnsupportedDigestAlgorithm"
        - "errLDS_ICAO_SignedData_SignerInfos_Empty"
        - "errLDS_ICAO_SignerInfo_UnsupportedDigestAlgorithm"
        - "errLDS_ICAO_SignerInfo_UnsupportedSignatureAlgorithm"
        - "errLDS_ICAO_SignerInfo_MessageDigestError"
        - "errLDS_ICAO_SignerInfo_SignedAttrs_Missed"
        - "errLDS_Auth_SignerInfo_CantFindCertificate"
        - "errLDS_Auth_Error"
        - "errLDS_Auth_UnsupportedSignatureAlgorithm"
        - "errLDS_Auth_UnsupportedPublicKeyAlgorithm"
        - "errLDS_Auth_MessedAlgorithms"
        - "errLDS_Auth_PublicKeyDataInvalid"
        - "errLDS_Auth_AlgorithmParametersDataInvalid"
        - "errLDS_Auth_SignatureDataInvalid"
        - "errLDS_Auth_UnsupportedDigestAlgorithm"
        - "errLDS_Auth_SignatureDataIncorrect"
        - "errLDS_Auth_AlgorithmParametersNotDefined"
        - "errLDS_Auth_SignatureCheckFailed"
        - "errLDS_DG_WrongTag"
        - "errLDS_DG_Contents_UnexpectedData"
        - "errLDS_BAP_SymmetricCypher_CantInitialize"
        - "errLDS_PACE_Info_NotAvailable"
        - "errLDS_PACE_SymmetricCypher_CantInitialize"
        - "errLDS_PACE_KeyAgreement_CantInitialize"
        - "errLDS_PACE_EphemeralKeys_CantCreate"
        - "errLDS_PACE_Mapping_CantDecodeNonce"
        - "errLDS_PACE_SharedSecret_CantCreate"
        - "errLDS_PACE_DomainParams_UnsupportedFormat"
        - "errLDS_PACE_EphemeralKeys_Incorrect"
        - "errLDS_PACE_Mapping_EphemeralKeys_Incorrect"
        - "errLDS_PACE_Mapping_CantPerform"
        - "errLDS_PACE_NonMatchingAuthTokens"
        - "errLDS_PACE_CAM_Data_Incorrect"
        - "errLDS_PACE_CAM_Data_CantVerify"
        - "errLDS_PACE_CAM_Data_NonMatching"
        - "errLDS_PACE_IM_Scheme_Incorrect"
        - "errLDS_PACE_IM_RandomMapping_Failed"
        - "errLDS_CA_CantFindPublicKey"
        - "errLDS_CA_CantFindInfo"
        - "errLDS_CA_IncorrectVersion"
        - "errLDS_CA_CantFindDomainParameters"
        - "errLDS_CA_KeyAgreement_CantInitialize"
        - "errLDS_CA_PublicKey_UnsupportedAlgorithm"
        - "errLDS_CA_EphemeralKeys_CantCreate"
        - "errLDS_CA_SharedSecret_CantCreate"
        - "errLDS_CA_NonMatchingAuthTokens"
        - "errLDS_TA_IncorrectVersion"
        - "errLDS_TA_CantBuildCertificateChain"
        - "errLDS_TA_CantFindISPrivateKey"
        - "errLDS_TA_PublicKey_UnsupportedAlgorithm"
        - "errLDS_TA_SignatureBuildingError"
        - "errLDS_TA_InvalidKeyAlgorithmParameters"
        - "errLDS_AA_PublicKey_UnsupportedAlgorithm"
        - "errLDS_AA_PublicKey_IncorrectData"
        - "errLDS_AA_PublicKey_IncorrectParameters"
        - "errLDS_AA_PublicKey_UndefinedParameters"
        - "errLDS_AA_Signature_IncorrectData"
        - "errLDS_AA_UnsupportedRecoveryScheme"
        - "errLDS_AA_IncorrectTrailer"
        - "errLDS_AA_UnsupportedDigestAlgorithm"
        - "errLDS_RI_SectorKey_CantFind"
        - "errLDS_RI_SectorKey_IncorrectData"
        - "errLDS_RI_SectorKey_IncompleteData"
        - "errLDS_CV_Certificate_MissingMandatoryData_PK"
        - "errLDS_CV_Certificate_PublicKey_Unsupported"
        - "errLDS_CV_Certificate_CHAT_UnsupportedTerminalType"
        - "errLDS_CV_Certificate_PrivateKey_Unsupported"
        - "errLDS_CV_Certificate_PrivateKey_InvalidParams"
        - "errLDS_CV_Certificate_IncorrectData"
        - "errLDS_CV_Certificate_CPI_IncorrectData"
        - "errLDS_CV_Certificate_CAR_IncorrectData"
        - "errLDS_CV_Certificate_PublicKey_IncorrectData"
        - "errLDS_CV_Certificate_CHR_IncorrectData"
        - "errLDS_CV_Certificate_CHAT_IncorrectData"
        - "errLDS_CV_Certificate_ValidFrom_IncorrectData"
        - "errLDS_CV_Certificate_ValidTo_IncorrectData"
        - "errLDS_CV_Certificate_Extensions_IncorrectData"
        - "errLDS_CV_Certificate_PrivateKey_IncorrectData"
        - "errLDS_CV_Certificate_PrivateKey_Missing"
        - "errLDS_VDS_UnsupportedVersion"
        - "errLDS_VDS_Issuing_Country_Size"
        - "errLDS_VDS_Issuing_Country_IncorrectData"
        - "errLDS_VDS_Signer_Certificate_Size"
        - "errLDS_VDS_Signer_Certificate_Data"
        - "errLDS_VDS_Signature_IncorrectData"
        - "errLDS_VDS_NC_IncorrectData"
        - "errLDS_VDS_NC_MissingOrIncorrect_Data"
        - "errLDS_VDS_NC_MissingOrIncorrect_Header"
        - "errLDS_VDS_NC_MissingOrIncorrect_Type"
        - "errLDS_VDS_NC_MissingOrIncorrect_Version"
        - "errLDS_VDS_NC_MissingOrIncorrect_IssuingCountry"
        - "errLDS_VDS_NC_MissingOrIncorrect_Message"
        - "errLDS_VDS_NC_MissingOrIncorrect_Signature"
        - "errLDS_VDS_NC_MissingOrIncorrect_SigAlgorithm"
        - "errLDS_VDS_NC_MissingOrIncorrect_Certificate"
        - "errLDS_VDS_NC_MissingOrIncorrect_SigValue"
