openapi: 3.0.3
components:
  schemas:
    ParsingNotificationCodes:
      description: "The enumeration contains possible values of notification codes returned during the RFID chip processing."
      type: integer
      enum:
      - -1879048191
      - -1879048190
      - -1879048189
      - -1879048188
      - -1879048187
      - -1879048186
      - -1879048184
      - -1879048178
      - -1879048177
      - -1879048176
      - -1879048169
      - -1879047680
      - -1879047679
      - -1879047678
      - -1879047677
      - -1879047676
      - -1879047675
      - -1879047674
      - -1879047673
      - -1879047672
      - -1879047671
      - -1879047670
      - -1879047669
      - -1879047668
      - -1879047667
      - -1879047666
      - -1879047665
      - -1879047664
      - -1879047663
      - -1879047662
      - -1879047661
      - -1879047660
      - -1879047659
      - -1879047658
      - -1879047657
      - -1879047656
      - -1879047655
      - -1879047654
      - -1879047653
      - -1879047652
      - -1879047651
      - -1879047650
      - -1879047649
      - -1879047648
      - -1879047647
      - -1879047646
      - -1879047645
      - -1879047644
      - -1879047643
      - -1879047642
      - -1879047640
      - -1879047639
      - -1879047638
      - -1879047637
      - -1879047636
      - -1879047635
      - -1879047634
      - -1879047633
      - -1879047631
      - -1879047630
      - -1879047629
      - -1879047628
      - -1879047627
      - -1879047626
      - -1879047625
      - -1879047624
      - -1879047623
      - -1879047622
      - -1879047621
      - -1879047620
      - -1879047619
      - -1879047618
      - -1879047617
      - -1879047616
      - -1879047615
      - -1879047614
      - -1879047613
      - -1879047612
      - -1879047611
      - -1879047610
      - -1879047609
      - -1879047608
      - -1879047607
      - -1879047606
      - -1879047605
      - -1879047604
      - -1879047603
      - -1879047602
      - -1879047601
      - -1879048160
      - -1879048159
      - -1879048158
      - -1879048157
      - -1879048156
      - -1879048155
      - -1879048154
      - -1879048144
      - -1879048143
      - -1879048142
      - -1879048141
      - -1879047936
      - -1879047776
      - -1879047775
      - -1879047935
      - -1879047934
      - -1879047933
      - -1879047927
      - -1879047760
      - -1879047759
      - -1879047758
      - -1879047932
      - -1879047931
      - -1879047930
      - -1879047929
      - -1879047928
      - -1879047744
      - -1879047736
      - -1879047728
      - -1879047720
      - -1879047926
      - -1879047925
      - -1879047924
      - -1879047923
      - -1879047922
      - -1879047921
      - -1879047920
      - -1879047919
      - -1879047918
      - -1879047909
      - -1879047908
      - -1879047907
      - -1879047906
      - -1879047905
      - -1879047915
      - -1879047914
      - -1879047913
      - -1879047912
      - -1879047911
      - -1879047910
      - 139272
      - 139273
      - 139274
      - 139277
      - 139278
      - 139279
      - 139280
      - 139281
      - 139282
      - 139283
      - 139284
      - 139285
      - 139286
      - 139287
      - 139288
      - -1878982656
      - -1878917120
      - -1878851584
      - -1878786048
      - -1878720512
      - -1878654976
      - -1878589440
      - -1878523904
      - -1878458368
      - -1878392832
      - -1878327296
      - -1877999616
      - -1877934080
      - -1877868544
      - -1877803008
      - -1877737472
      - -1877671936
      - -1877606400
      - -1877540864
      - -1877475328
      - -1877409792
      - -1877344256
      - -1862270976
      - -1862270975
      - -1862270974
      - -1862270973
      - -1862270972
      - -1862270971
      - -1862270970
      - -1862270969
      - -1862270968
      - -1862270967
      - -1862270966
      - -1862270965
      - -1862270964
      - -1862270963
      - -1862270962
      - -1862270720
      - -1862270719
      - -1862270718
      - -1862270717
      - -1862270716
      - -1862270715
      - -1862270714
      - -1862270713
      - -1862270712
      - -1862270711
      - -1862270710
      - -1862270709
      - -1862270708
      - -1862270707
      - -1862270706
      - -1862270705
      - -1862270704
      - -1862270463
      - -1862270462
      - -1862270461
      - -1862270460
      - -1862270208
      - -1845493483
      - -1845493482
      - -1845493481
      - -1845493480
      - -1845493479
      x-enum-varnames:
      - "NTF_LDS_ASN_CERTIFICATE_INCORRECT_VERSION"
      - "NTF_LDS_ASN_CERTIFICATE_NON_MATCHING_SIGNATURE_ALGORITHM"
      - "NTF_LDS_ASN_CERTIFICATE_INCORRECT_TIME_CODING"
      - "NTF_LDS_ASN_CERTIFICATE_INCORRECT_USE_OF_GENERALIZED_TIME"
      - "NTF_LDS_ASN_CERTIFICATE_EMPTY_ISSUER"
      - "NTF_LDS_ASN_CERTIFICATE_EMPTY_SUBJECT"
      - "NTF_LDS_ASN_CERTIFICATE_UNSUPPORTED_CRITICAL_EXTENSION"
      - "NTF_LDS_ASN_CERTIFICATE_FORCED_DEFAULT_CSCA_ROLE"
      - "NTF_LDS_ASN_CERTIFICATE_FORCED_DEFAULT_DS_ROLE"
      - "NTF_LDS_ASN_CERTIFICATE_INCORRECT_ISSUER_SUBJECT_DS"
      - "NTF_LDS_ASN_CERTIFICATE_DUPLICATING_EXTENSIONS"
      - "NTF_LDS_ICAO_CERTIFICATE_VERSION_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_VERSION_INCORRECT"
      - "NTF_LDS_ICAO_CERTIFICATE_ISSUER_COUNTRY_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_ISSUER_COMMON_NAME_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_ISSUER_COUNTRY_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_SUBJECT_COUNTRY_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_SUBJECT_COMMON_NAME_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_SUBJECT_COUNTRY_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_USING_NON_COMPLIANT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_UNSUPPORTED_SIGNATURE_ALGORITHM"
      - "NTF_LDS_ICAO_CERTIFICATE_UNSUPPORTED_PUBLIC_KEY_ALGORITHM"
      - "NTF_LDS_ICAO_CERTIFICATE_MISSED_EXTENSIONS"
      - "NTF_LDS_ICAO_CERTIFICATE_VALIDITY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_USING_NON_COMPLIANT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_KEY_USAGE_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_KEY_USAGE_NOT_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_KEY_USAGE_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_BASIC_C_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_BASIC_C_INCORRECT_USAGE1"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_BASIC_C_INCORRECT_USAGE2"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_BASIC_C_NOT_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_BASIC_C_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_BASIC_C_PATH_LEN_C_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_BASIC_C_PATH_LEN_C_INCORRECT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_EXT_KEY_USAGE_NOT_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_EXT_KEY_USAGE_INCORRECT_USAGE"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_EXT_KEY_USAGE_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_AUTH_KEY_ID_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_AUTH_KEY_ID_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_AUTH_KEY_ID_KEY_ID_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_KEY_ID_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_KEY_ID_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_PRIVATE_KEY_UP_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_PRIVATE_KEY_UP_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_PRIVATE_KEY_UP_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_DN_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_DN_INCORRECT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_SUBJECT_ALT_NAME_DN_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_DN_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_DN_INCORRECT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_ISSUER_ALT_NAME_DN_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_DOC_TYPE_LIST_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_DOC_TYPE_LIST_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_DOC_TYPE_LIST_VERSION"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_DOC_TYPE_LIST_DOC_TYPES"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_DOC_TYPE_LIST_DOC_TYPES_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CERT_POLICIES_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CERT_POLICIES_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CERT_POLICIES_POLICY_ID_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CRL_DIST_POINT_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CRL_DIST_POINT_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CRL_DIST_POINT_EMPTY"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CRL_DIST_POINT_POINT_MISSED"
      - "NTF_LDS_ICAO_CERTIFICATE_SN_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_ISSUER_SN_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_SUBJECT_SN_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_ISSUER_ATTRIBUTE_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_SUBJECT_ATTRIBUTE_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_ISSUER_SUBJECT_COUNTRY_NON_MATCHING"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_CSCA_ALT_NAMES_NON_MATCHING"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_NAME_CHANGE_INCORRECT_DATA"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_NAME_CHANGE_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_NAME_CHANGE_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_DOC_TYPE_LIST_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_DOC_TYPE_LIST_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_EXT_OPTIONAL_CRITICAL"
      - "NTF_LDS_ICAO_CERTIFICATE_SUBJECT_NON_COMPLIANT"
      - "NTF_LDS_ICAO_CERTIFICATE_SUBJECT_COMMON_NAME_NON_COMPLIANT"
      - "NTF_LDS_ICAO_COM_LDS_VERSION_INCORRECT"
      - "NTF_LDS_ICAO_COM_LDS_VERSION_MISSING"
      - "NTF_LDS_ICAO_COM_UNICODE_VERSION_INCORRECT"
      - "NTF_LDS_ICAO_COM_UNICODE_VERSION_MISSING"
      - "NTF_LDS_ICAO_COM_DGPM_INCORRECT"
      - "NTF_LDS_ICAO_COM_DGPM_MISSING"
      - "NTF_LDS_ICAO_COM_DGPM_UNEXPECTED"
      - "NTF_LDS_ICAO_APPLICATION_LDS_VERSION_UNSUPPORTED"
      - "NTF_LDS_ICAO_APPLICATION_UNICODE_VERSION_UNSUPPORTED"
      - "NTF_LDS_ICAO_APPLICATION_LDS_VERSION_INCONSISTENT"
      - "NTF_LDS_ICAO_APPLICATION_UNICODE_VERSION_INCONSISTENT"
      - "NTF_LDS_ASN_SIGNED_DATA_OID_INCORRECT"
      - "NTF_LDS_ASN_SIGNED_DATA_VERSION_INCORRECT"
      - "NTF_LDS_ASN_SIGNED_DATA_CONTENT_OID_INCORRECT"
      - "NTF_LDS_ICAO_SIGNED_DATA_VERSION_INCORRECT"
      - "NTF_LDS_ICAO_SIGNED_DATA_DIGEST_ALGORITHMS_EMPTY"
      - "NTF_LDS_ICAO_SIGNED_DATA_DIGEST_ALGORITHMS_UNSUPPORTED"
      - "NTF_LDS_ICAO_SIGNED_DATA_SIGNER_INFOS_MULTIPLE_ENTRIES"
      - "NTF_LDS_ICAO_SIGNED_DATA_CERTIFICATES_MISSED"
      - "NTF_LDS_ICAO_SIGNED_DATA_CERTIFICATES_EMPTY"
      - "NTF_LDS_ICAO_SIGNED_DATA_CRLS_INCORRECT_USAGE"
      - "NTF_LDS_ICAO_LDS_OBJECT_INCORRECT_CONTENT_OID"
      - "NTF_LDS_ICAO_LDS_OBJECT_DG_NUMBER_INCORRECT"
      - "NTF_LDS_ICAO_LDS_OBJECT_DG_HASH_MISSING"
      - "NTF_LDS_ICAO_LDS_OBJECT_DG_HASH_EXTRA"
      - "NTF_LDS_ICAO_LDS_OBJECT_VERSION_INCORRECT"
      - "NTF_LDS_ICAO_MASTER_LIST_VERSION_INCORRECT"
      - "NTF_LDS_ICAO_DEVIATION_LIST_VERSION_INCORRECT"
      - "NTF_LDS_BSI_DEFECT_LIST_VERSION_INCORRECT"
      - "NTF_LDS_BSI_BLACK_LIST_VERSION_INCORRECT"
      - "NTF_LDS_ASN_SIGNER_INFO_VERSION_INCORRECT"
      - "NTF_LDS_ASN_SIGNER_INFO_SID_INCORRECT_CHOICE"
      - "NTF_LDS_ASN_SIGNER_INFO_SID_DIGEST_ALGORITHM_NOT_LISTED"
      - "NTF_LDS_ASN_SIGNER_INFO_MESSAGE_DIGEST_ATTR_MISSING"
      - "NTF_LDS_ASN_SIGNER_INFO_MESSAGE_DIGEST_ATTR_DATA"
      - "NTF_LDS_ASN_SIGNER_INFO_MESSAGE_DIGEST_ATTR_Value"
      - "NTF_LDS_ASN_SIGNER_INFO_CONTENT_TYPE_ATTR_MISSING"
      - "NTF_LDS_ASN_SIGNER_INFO_CONTENT_TYPE_ATTR_DATA"
      - "NTF_LDS_ASN_SIGNER_INFO_CONTENT_TYPE_ATTR_VALUE"
      - "NTF_LDS_ASN_SIGNER_INFO_SIGNING_TIME_ATTR_MISSING"
      - "NTF_LDS_ASN_SIGNER_INFO_SIGNING_TIME_ATTR_DATA"
      - "NTF_LDS_ASN_SIGNER_INFO_SIGNING_TIME_ATTR_VALUE"
      - "NTF_LDS_ASN_SIGNER_INFO_LIST_CONTENT_DESCRIPTION_ATTR_MISSING"
      - "NTF_LDS_ASN_SIGNER_INFO_LIST_CONTENT_DESCRIPTION_ATTR_DATA"
      - "NTF_LDS_AUTH_SIGNER_INFO_CERTIFICATE_VALIDITY"
      - "NTF_LDS_AUTH_SIGNER_INFO_CERTIFICATE_ROOT_IS_NOT_TRUSTED"
      - "NTF_LDS_AUTH_SIGNER_INFO_CERTIFICATE_CANT_FIND_CSCA"
      - "NTF_LDS_AUTH_SIGNER_INFO_CERTIFICATE_REVOKED"
      - "NTF_LDS_AUTH_SIGNER_INFO_CERTIFICATE_SIGNATURE_INVALID"
      - "NTF_LDS_UNSUPPORTED_IMAGE_FORMAT"
      - "NTF_LDS_MRZ_DOCUMENT_TYPE_UNKNOWN"
      - "NTF_LDS_MRZ_ISSUING_STATE_SYNTAX_ERROR"
      - "NTF_LDS_MRZ_NAME_IS_VOID"
      - "NTF_LDS_MRZ_NUMBER_INCORRECT_CHECKSUM"
      - "NTF_LDS_MRZ_NATIONALITY_SYNTAX_ERROR"
      - "NTF_LDS_MRZ_DOB_SYNTAX_ERROR"
      - "NTF_LDS_MRZ_DOB_ERROR"
      - "NTF_LDS_MRZ_DOB_INCORRECT_CHECKSUM"
      - "NTF_LDS_MRZ_SEX_INCORRECT"
      - "NTF_LDS_MRZ_DOE_SYNTAX_ERROR"
      - "NTF_LDS_MRZ_DOE_ERROR"
      - "NTF_LDS_MRZ_DOE_INCORRECT_CHECKSUM"
      - "NTF_LDS_MRZ_OPTIONAL_DATA_INCORRECT_CHECKSUM"
      - "NTF_LDS_MRZ_INCORRECT_CHECKSUM"
      - "NTF_LDS_MRZ_INCORRECT"
      - "NTF_LDS_BIOMETRICS_FORMAT_OWNER_MISSING"
      - "NTF_LDS_BIOMETRICS_FORMAT_OWNER_INCORRECT"
      - "NTF_LDS_BIOMETRICS_FORMAT_TYPE_MISSING"
      - "NTF_LDS_BIOMETRICS_FORMAT_TYPE_INCORRECT"
      - "NTF_LDS_BIOMETRICS_TYPE_INCORRECT"
      - "NTF_LDS_BIOMETRICS_SUB_TYPE_MISSING"
      - "NTF_LDS_BIOMETRICS_SUB_TYPE_INCORRECT"
      - "NTF_LDS_BIOMETRICS_BDB_IMAGE_MISSING"
      - "NTF_LDS_BIOMETRICS_BDB_FORMAT_ID_INCORRECT"
      - "NTF_LDS_BIOMETRICS_BDB_VERSION_INCORRECT"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_LENGTH_INCORRECT"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_GENDER"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_EYE_COLOR"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_HAIR_COLOR"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_POSE_ANGLE_YAW"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_POSE_ANGLE_PITCH"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_POSE_ANGLE_ROLL"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_POSE_ANGLE_U_YAW"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_POSE_ANGLE_U_PITCH"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_POSE_ANGLE_U_ROLL"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_FACE_IMAGE_TYPE"
      - "NTF_LDS_BIOMETRICS_BDB_DATA_IMAGE_DATA_TYPE"
      - "NTF_LDS_SI_PACE_INFO_UNSUPPORTED_STD_PARAMETERS"
      - "NTF_LDS_SI_PACE_INFO_DEPRECATED_VERSION"
      - "NTF_LDS_SI_PACE_DOMAIN_PARAMS_USING_STD_REF"
      - "NTF_LDS_SI_PACE_DOMAIN_PARAMS_UNSUPPORTED_ALGORITHM"
      - "NTF_LDS_SI_CA_INFO_INCORRECT_VERSION"
      - "NTF_LDS_SI_CA_PUBLIC_KEY_UNSUPPORTED_ALGORITHM"
      - "NTF_LDS_SI_CA_DOMAIN_PARAMS_UNSUPPORTED_ALGORITHM"
      - "NTF_LDS_SI_TA_INFO_INCORRECT_VERSION"
      - "NTF_LDS_SI_TA_INFO_FILE_ID_FOR_VERSION2"
      - "NTF_LDS_SI_EID_SECURITY_UNSUPPORTED_DIGEST_ALGORITHM"
      - "NTF_LDS_SI_RI_INFO_INCORRECT_VERSION"
      - "NTF_LDS_SI_RI_DOMAIN_PARAMS_UNSUPPORTED_ALGORITHM"
      - "NTF_LDS_SI_AA_INFO_INCORRECT_VERSION"
      - "NTF_LDS_SI_AA_INFO_UNSUPPORTED_ALGORITHM"
      - "NTF_LDS_SI_AA_INFO_INCONSISTENT_ALGORITHM_REFERENCE"
      - "NTF_LDS_SI_STORAGE_PACE_INFO_NOT_AVAILABLE"
      - "NTF_LDS_SI_STORAGE_PACE_INFO_NO_STD_PARAMETERS"
      - "NTF_LDS_SI_STORAGE_PACE_INFO_NO_MATCHING_DOMAIN_PARAMS"
      - "NTF_LDS_SI_STORAGE_CA_INFO_NOT_AVAILABLE"
      - "NTF_LDS_SI_STORAGE_CA_DOMAIN_PARAMS_NO_REQUIRED_OPTION"
      - "NTF_LDS_SI_STORAGE_CA_DOMAIN_PARAMS_NOT_AVAILABLE"
      - "NTF_LDS_SI_STORAGE_CA_ANONYMOUS_INFOS"
      - "NTF_LDS_SI_STORAGE_CA_INFO_NO_MATCHING_DOMAIN_PARAMS"
      - "NTF_LDS_SI_STORAGE_CA_INFO_NO_MATCHING_PUBLIC_KEY"
      - "NTF_LDS_SI_STORAGE_CA_INCORRECT_INFOS_QUANTITY"
      - "NTF_LDS_SI_STORAGE_TA_INFO_NOT_AVAILABLE"
      - "NTF_LDS_SI_STORAGE_CARD_INFO_LOCATOR_MULTIPLE_ENTRIES"
      - "NTF_LDS_SI_STORAGE_EID_SECURITY_INFO_MULTIPLE_ENTRIES"
      - "NTF_LDS_SI_STORAGE_PRIVILEGED_TI_MULTIPLE_ENTRIES"
      - "NTF_LDS_SI_STORAGE_PRIVILEGED_TI_INCORRECT_USAGE"
      - "NTF_LDS_SI_STORAGE_RI_DOMAIN_PARAMS_MULTIPLE_ENTRIES"
      - "NTF_LDS_SI_STORAGE_PACE_INFOS_NON_CONSISTANT"
      - "NTF_LDS_CV_CERTIFICATE_PROFILE_INCORRECT_VERSION"
      - "NTF_LDS_CV_CERTIFICATE_VALIDITY"
      - "NTF_LDS_CV_CERTIFICATE_NON_CV_CA_DOMAIN_PARAMETERS"
      - "NTF_LDS_CV_CERTIFICATE_PRIVATE_KEY_INCORRECT_VERSION"
      - "NTF_LDS_TA_PACE_STATIC_BINDING_USED"
      - "NTF_LDS_AUTH_ML_SIGNER_INFO_CERTIFICATE_VALIDITY"
      - "NTF_LDS_AUTH_ML_SIGNER_INFO_CERTIFICATE_ROOT_IS_NOT_TRUSTED"
      - "NTF_LDS_AUTH_ML_SIGNER_INFO_CERTIFICATE_CANT_FIND_CSCA"
      - "NTF_LDS_AUTH_ML_SIGNER_INFO_CERTIFICATE_REVOKED"
      - "NTF_LDS_AUTH_ML_SIGNER_INFO_CERTIFICATE_SIGNATURE_INVALID"
