openapi: 3.0.4
components:
  schemas:
    RFIDErrorCodes:
      title: "RFIDErrorCodes"
      type: integer
      format: int64
      description: "Enumeration contains a set of error codes returned by SDK"
      enum:
        - 2147508866
        - 2147508867
        - 2147509184
        - 2147509185
        - 2147510659
        - 2147510660
        - 2147510661
        - 2147510912
        - 2147510914
        - 2147510920
        - 2147511040
        - 2147549185
        - 2147549186
        - 2147549188
        - 2147549189
        - 2147549190
        - 2147549192
        - 2147549193
        - 2147549194
        - 2147549195
        - 2147549196
        - 2147614720
        - 2147614721
        - 2147614722
        - 2147614723
        - 2147614724
        - 2147614725
        - 2147614726
        - 2147614736
        - 2148557760
        - 2197815296
        - 2197815297
        - 2197815298
        - 2197815312
        - 2197815313
        - 2197815314
        - 2197815315
        - 2197815316
        - 2197815317
        - 2197815318
        - 2197815319
        - 2197815320
        - 2197815321
        - 2197815322
        - 2197815323
        - 2197815324
        - 2197815328
        - 2197815329
        - 2197815330
        - 2197815331
        - 2197815332
        - 2197815333
        - 2197815334
        - 2197815335
        - 2197815336
        - 2197815337
        - 2197815338
        - 2197815344
        - 2197815345
        - 2197815360
        - 2197815361
        - 2197815362
        - 2197815376
        - 2197815377
        - 2197815378
        - 2197815392
        - 2197880832
        - 2197946368
        - 2198011904
        - 2198077440
        - 2198142976
        - 2198208512
        - 2198274048
        - 2198339584
        - 2214592512
        - 2214658048
        - 2214723584
        - 2214789120
        - 2214854656
        - 2214920192
        - 2214985728
        - 2215051264
        - 2215116800
        - 2215182336
        - 2215247872
        - 2215313408
        - 2215378944
        - 2215444480
        - 2215510016
        - 2215575552
        - 2248146944
        - 2248146945
        - 2248147200
        - 2248147201
        - 2248147202
        - 2248147203
        - 2248147456
        - 2248147457
        - 2248147458
        - 2248147459
        - 2248147460
        - 2248147712
        - 2248147713
        - 2248147714
        - 2248147715
        - 2248147716
        - 2248147717
        - 2248147718
        - 2248147719
        - 2248147720
        - 2248147721
        - 4294967295
        - 1
        - 2
        - 2147549191
        - 2147510016
      x-enum-descriptions:
        - "LAYER6: Reading beyond EOF / Unexpected EOF"
        - "LAYER6: PWD deactivated"
        - "LAYER6: PWD blocked"
        - "LAYER6: PWD suspended"
        - "LAYER6: PWD blocked 2"
        - "LAYER6: PWD deactivated 2"
        - "LAYER6: PWD suspended 2"
        - "LAYER6: Incorrect params"
        - "LAYER6: File selection failure / file not found"
        - "LAYER6: No reference data"
        - "LAYER6: Reading beyond EOF / Unexpected EOF"
        - "RFID: No chip is detected"
        - "RFID: Unavailable"
        - "RFID: Invalid parameter in ExecuteCommand() call found"
        - "RFID: Device is uninitialized"
        - "RFID: Out of memory"
        - "RFID: Invalid directory"
        - "RFID: Unknown command"
        - "RFID File: IO Error"
        - "RFID: RFID is busy"
        - "RFID: The firmware needs to be updated to a newer version"
        - "PCSC: Failed"
        - "PCSC: The reader is unavailable"
        - "PCSC: The card cannot be connected"
        - "PCSC: The card is not connected"
        - "PCSC: Operation is cancelled"
        - "PCSC: The card is busy"
        - "PCSC: Failed Smart Card"
        - "PCSC: ExtLe Failed"
        - "LAYER6: PWD failed"
        - "RFID: Not performed"
        - "RFID: Session is closed"
        - "RFID: Unsupported terminal operation"
        - "RFID: Terminal type unknown"
        - "RFID: Terminal type bad certificate"
        - "RFID: Terminal type not set"
        - "RFID: Unknown procedure type"
        - "RFID: Unsupported procedure type"
        - "RFID: Procedure type not set"
        - "RFID: Access key unknown type"
        - "RFID: Access key unsupported SM type"
        - "RFID: Access key incorrect SM type"
        - "RFID: Access key restricted"
        - "RFID: Access key incorrect data"
        - "RFID: Access key not set"
        - "RFID: PWD management not authorized"
        - "RFID: Access control unknown type"
        - "RFID: SM required"
        - "RFID: PACE required"
        - "RFID: CA keys required"
        - "RFID: TA required"
        - "RFID: CA required"
        - "RFID: Incorrect option CA"
        - "RFID: CA failed"
        - "RFID: TA failed"
        - "RFID: AA failed"
        - "RFID: RI failed"
        - "RFID: SO signature check failed"
        - "RFID: Hash check failed"
        - "RFID: Invalid aux data - date of expiry"
        - "RFID: Invalid aux data - date of birth"
        - "RFID: Invalid aux data - community ID"
        - "RFID: eSign requires app selection"
        - "RFID: eSign PIN not set"
        - "RFID: eSign PIN not verified"
        - "RFID: Incorrect data"
        - "RFID file: Insufficient data"
        - "RFID file: Incorrect data"
        - "RFID file: Unexpected data"
        - "RFID file: Contains unexpected data"
        - "RFID file: Wrong tag"
        - "RFID file: Cannot use data"
        - "RFID file: Cannot read data"
        - "RFID file: Access denied"
        - "RFID: Layer 34 - No error"
        - "RFID: Layer 34 - Timeout"
        - "RFID: Layer 34 - Collision"
        - "RFID: Layer 34 - CRC"
        - "RFID: Layer 34 - Data integrity"
        - "RFID: Layer 34 - Data length"
        - "RFID: Layer 34 - RFU"
        - "RFID: Layer 34 - Too many collision"
        - "RFID: Layer 34 - Protocol B"
        - "RFID: Layer 34 - Data contents"
        - "RFID: Layer 34 - Protocol"
        - "RFID: Layer 34 - Globa timeout"
        - "RFID: Layer 34 - MIFARE auth"
        - "RFID: Layer 34 - SAM error"
        - "RFID: Layer 34 - SAM collision"
        - "RFID: Layer 34 - SAM acknowledge"
        - "LAYER6: Secure Messaging was not activated"
        - "LAYER6: ISO7816_A_03 Application selection failure"
        - "LAYER6: ISO7816_B_01 Mutual authentication MAC failure"
        - "LAYER6: ISO7816_B_02 Mutual authentication encryption failure"
        - "LAYER6: ISO7816_B_03 Mutual authentication failure"
        - "LAYER6: ISO7816_B_03 Mutual authentication failure data"
        - "LAYER6: SM failure – MAC missing"
        - "LAYER6: SM failure – cryptogram missing"
        - "LAYER6: SM failure – secured status bytes missing"
        - "LAYER6: SM failure – incorrect MAC"
        - "LAYER6: SM failure – incorrect cryptogram"
        - "LAYER6: Not TLV response data"
        - "LAYER6: Wrong data length (APDU_INS_GET_CHALLENGE)"
        - "LAYER6: APDU_INS_INTERNAL_AUTHENTICATE failure"
        - "LAYER6: MSE:Set KAT failure"
        - "LAYER6: MSE:Set DST failure"
        - "LAYER6: PSO CERTIFICATE failure"
        - "LAYER6: MSE:Set AT failure"
        - "LAYER6: GET CHALLENGE failure"
        - "LAYER6: APDU_INS_EXTERNAL_AUTHENTICATE (external authentication) failure"
        - "LAYER6: General Authenticity Failure"
        - "RFID: Failed"
        - "RFID: No error"
        - "RFID: The requested operation is already performed"
        - "RFID: Not enough data"
        - "RFID: Layer 6 - Wrong data length"
      x-enum-varnames:
        - "RFID_ERROR_LAYER6_FILE_EOF1"
        - "RFID_ERROR_LAYER6_PWD_DEACTIVATED"
        - "RFID_ERROR_LAYER6_PWD_BLOCKED"
        - "RFID_ERROR_LAYER6_PWD_SUSPEND"
        - "RFID_ERROR_LAYER6_PWD_BLOCKED2"
        - "RFID_ERROR_LAYER6_PWD_DEACTIVATED2"
        - "RFID_ERROR_LAYER6_PWD_SUSPEND2"
        - "RFID_ERROR_LAYER6_INCORRECT_PARAMS"
        - "RFID_ERROR_LAYER6_FILE_NOT_FOUND"
        - "RFID_ERROR_LAYER6_NO_REFERENCE_DATA"
        - "RFID_ERROR_LAYER6_FILE_EOF2"
        - "RFID_ERROR_NO_CHIP_DETECTED"
        - "RFID_ERROR_NOT_AVAILABLE"
        - "RFID_ERROR_INVALID_PARAMETER"
        - "RFID_ERROR_NOT_INITIALIZED"
        - "RFID_ERROR_NOT_ENOUGH_MEMORY"
        - "RFID_ERROR_INVALID_DIRECTORY"
        - "RFID_ERROR_UNKNOWN_COMMAND"
        - "RFID_ERROR_FILE_IO_ERROR"
        - "RFID_ERROR_BUSY"
        - "RFID_ERROR_OLD_FIRMWARE"
        - "RFID_ERROR_PCSC_FAILED"
        - "RFID_ERROR_PCSC_READER_NOT_AVAILABLE"
        - "RFID_ERROR_PCSC_CANT_CONNECT_CARD"
        - "RFID_ERROR_PCSC_CARD_IS_NOT_CONNECTED"
        - "RFID_ERROR_PCSC_OPERATION_CANCELLED"
        - "RFID_ERROR_PCSC_CARD_IS_BUSY"
        - "RFID_ERROR_PCSC_FAILED_SCARD"
        - "RFID_ERROR_PCSC_EXT_LE_FAILED"
        - "RFID_ERROR_LAYER6_PWD_FAILED"
        - "RFID_ERROR_NOT_PERFORMED"
        - "RFID_ERROR_SESSION_IS_CLOSED"
        - "RFID_ERROR_SESSION_TERMINAL_UNSUPPORTED_OPERATION"
        - "RFID_ERROR_SESSION_TERMINAL_TYPE_UNKNOWN"
        - "RFID_ERROR_SESSION_TERMINAL_TYPE_BAD_CERTIFICATE"
        - "RFID_ERROR_SESSION_TERMINAL_TYPE_NOT_SET"
        - "RFID_ERROR_SESSION_PROCEDURE_TYPE_UNKNOWN"
        - "RFID_ERROR_Session_Procedure_Type_Unsupported"
        - "RFID_ERROR_SESSION_PROCEDURE_TYPE_NOT_SET"
        - "RFID_ERROR_SESSION_ACCESS_KEY_UNKNOWN_TYPE"
        - "RFID_ERROR_SESSION_ACCESS_KEY_UNSUPPORTED_SM_TYPE"
        - "RFID_ERROR_SESSION_ACCESS_KEY_INCORRECT_SM_TYPE"
        - "RFID_ERROR_SESSION_ACCESS_KEY_RESTRICTED"
        - "RFID_ERROR_SESSION_ACCESS_KEY_INCORRECT_DATA"
        - "RFID_ERROR_SESSION_ACCESS_KEY_NOT_SET"
        - "RFID_ERROR_SESSION_PWD_MANAGEMENT_NOT_AUTHORIZED"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_UNKNOWN_TYPE"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_SM"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_PACE"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_CA_KEYS"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_TA"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_REQUIRES_CA"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_INCORRECT_OPTION_CA"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_CA_FAILED"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_TA_FAILED"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_AA_FAILED"
        - "RFID_ERROR_SESSION_ACCESS_CONTROL_RI_FAILED"
        - "RFID_ERROR_SESSION_PA_SIGNATURE_CHECK_FAILED"
        - "RFID_ERROR_SESSION_PA_HASH_CHECK_FAILED"
        - "RFID_ERROR_SESSION_INVALID_AUX_DATA_DATE_OF_EXPIRY"
        - "RFID_ERROR_SESSION_INVALID_AUX_DATA_DATE_OF_BIRTH"
        - "RFID_ERROR_SESSION_INVALID_AUX_DATA_COMMUNITY_ID"
        - "RFID_ERROR_SESSION_E_SIGN_REQUIRES_APP_SELECTION"
        - "RFID_ERROR_SESSION_E_SIGN_PIN_NOT_SET"
        - "RFID_ERROR_SESSION_E_SIGN_PIN_NOT_VERIFIED"
        - "RFID_ERROR_SESSION_INCORRECT_DATA"
        - "RFID_ERROR_SESSION_FILE_NOT_ENOUGH_DATA"
        - "RFID_ERROR_SESSION_FILE_INCORRECT_DATA"
        - "RFID_ERROR_SESSION_FILE_UNEXPECTED_DATA"
        - "RFID_ERROR_SESSION_FILE_CONTENTS_UNEXPECTED_DATA"
        - "RFID_ERROR_SESSION_FILE_WRONG_TAG"
        - "RFID_ERROR_SESSION_FILE_CANT_USE_DATA"
        - "RFID_ERROR_SESSION_FILE_CANT_READ_DATA"
        - "RFID_ERROR_SESSION_FILE_ACCESS_DENIED"
        - "RFID_ERROR_LAYER34_NO_ERROR"
        - "RFID_ERROR_LAYER34_TIME_OUT"
        - "RFID_ERROR_LAYER34_COLLISION"
        - "RFID_ERROR_LAYER34_CRC"
        - "RFID_ERROR_LAYER34_DATA_INTEGRITY"
        - "RFID_ERROR_LAYER34_DATA_LENGTH"
        - "RFID_ERROR_Layer34_RFU"
        - "RFID_ERROR_LAYER34_COLLISION_TOO_MANY"
        - "RFID_ERROR_LAYER34_PROTOCOL_B"
        - "RFID_ERROR_LAYER34_DATA_CONTENTS"
        - "RFID_ERROR_LAYER34_PROTOCOL"
        - "RFID_ERROR_LAYER34_GLOBAL_TIME_OUT"
        - "RFID_ERROR_LAYER34_MIFARE_AUTH"
        - "RFID_ERROR_LAYER34_SAM_ERROR"
        - "RFID_ERROR_LAYER34_SAM_COLLISION"
        - "RFID_ERROR_LAYER34_SAM_ACKNOWLEDGE"
        - "RFID_ERROR_LAYER6_SECURITY_MANAGER"
        - "RFID_ERROR_LAYER6_APP_SELECTION_FAILURE"
        - "RFID_ERROR_LAYER6_MUTUAL_AUTH_MAC_FAIL"
        - "RFID_ERROR_LAYER6_MUTUAL_AUTH_ENC_FAIL"
        - "RFID_ERROR_LAYER6_MUTUAL_AUTH_FAILURE"
        - "RFID_ERROR_LAYER6_MUTUAL_AUTH_FAILURE_DATA"
        - "RFID_ERROR_LAYER6_SM_DO_8E_MISSING"
        - "RFID_ERROR_LAYER6_SM_DO_87_MISSING"
        - "RFID_ERROR_LAYER6_SM_DO_99_MISSING"
        - "RFID_ERROR_LAYER6_SM_MAC_INCORRECT"
        - "RFID_ERROR_LAYER6_SM_DO_87_INCORRECT"
        - "RFID_ERROR_LAYER6_NON_TLV_RESPONSE_DATA"
        - "RFID_ERROR_LAYER6_WRONG_RND_ICC_LENGTH"
        - "RFID_ERROR_LAYER6_INT_AUTH_FAILURE"
        - "RFID_ERROR_LAYER6_MSE_SET_KAT_FAILURE"
        - "RFID_ERROR_LAYER6_MSE_SET_DST_FAILURE"
        - "RFID_ERROR_LAYER6_PSO_CERTIFICATE_FAILURE"
        - "RFID_ERROR_LAYER6_MSE_SET_AT_FAILURE"
        - "RFID_ERROR_LAYER6_GET_CHALLENGE_FAILURE"
        - "RFID_ERROR_LAYER6_EXT_AUTH_FAILURE"
        - "RFID_ERROR_LAYER6_GENERAL_AUTH_FAILURE"
        - "RFID_ERROR_FAILED"
        - "RFID_ERROR_NO_ERROR"
        - "RFID_ERROR_ALREADY_DONE"
        - "RFID_ERROR_NOT_ENOUGH_DATA"
        - "RFID_LAYER6_WRONG_LENGTH"
