openapi: 3.1.1
components:
  schemas:
    RfidDataFileType:
      title: "RfidDataFileType"
      type: integer
      description: "Enumeration contains a set of constants that define the file type
      (or logical belonging of the data object) within the context of the communication session with electronic document"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 57
        - 58
        - 62
        - 63
        - 64
        - 101
        - 102
        - 103
        - 104
        - 105
        - 106
        - 107
        - 108
        - 109
        - 110
        - 111
        - 112
        - 113
        - 114
        - 115
        - 116
        - 117
        - 118
        - 119
        - 120
        - 121
        - 150
        - 151
        - 152
        - 153
        - 154
        - 155
        - 156
        - 157
        - 158
        - 159
        - 160
        - 161
        - 162
        - 163
        - 164
        - 165
        - 166
        - 167
        - 200
        - 201
        - 202
        - 300
        - 301
        - 302
        - 400
        - 500
        - 501
        - 600
        - 601
        - 602
        - 603
        - 700
        - 701
        - 702
        - 703
        - 710
        - 711
        - 712
        - 713
        - 714
        - 715
        - 1000
      x-enum-varnames:
        - "UNSPECIFIED"
        - "PASSPORT_DG1"
        - "PASSPORT_DG2"
        - "PASSPORT_DG3"
        - "PASSPORT_DG4"
        - "PASSPORT_DG5"
        - "PASSPORT_DG6"
        - "PASSPORT_DG7"
        - "PASSPORT_DG8"
        - "PASSPORT_DG9"
        - "PASSPORT_DG10"
        - "PASSPORT_DG11"
        - "PASSPORT_DG12"
        - "PASSPORT_DG13"
        - "PASSPORT_DG14"
        - "PASSPORT_DG15"
        - "PASSPORT_DG16"
        - "PASSPORT_DG17"
        - "PASSPORT_DG18"
        - "PASSPORT_DG19"
        - "PASSPORT_DG20"
        - "PASSPORT_SOD"
        - "PASSPORT_CVCA"
        - "PASSPORT_COM"
        - "DTC_DG17"
        - "DTC_DG18"
        - "DTC_DG22"
        - "DTC_DG23"
        - "DTC_DG24"
        - "ID_DG1"
        - "ID_DG2"
        - "ID_DG3"
        - "ID_DG4"
        - "ID_DG5"
        - "ID_DG6"
        - "ID_DG7"
        - "ID_DG8"
        - "ID_DG9"
        - "ID_DG10"
        - "ID_DG11"
        - "ID_DG12"
        - "ID_DG13"
        - "ID_DG14"
        - "ID_DG15"
        - "ID_DG16"
        - "ID_DG17"
        - "ID_DG18"
        - "ID_DG19"
        - "ID_DG20"
        - "ID_DG21"
        - "DL_COM"
        - "DL_DG1"
        - "DL_DG2"
        - "DL_DG3"
        - "DL_DG4"
        - "DL_DG5"
        - "DL_DG6"
        - "DL_DG7"
        - "DL_DG8"
        - "DL_DG9"
        - "DL_DG10"
        - "DL_DG11"
        - "DL_DG12"
        - "DL_DG13"
        - "DL_DG14"
        - "DL_SOD"
        - "DL_CE"
        - "DL_CVCA"
        - "PACE_CARD_ACCESS"
        - "PACE_CARD_SECURITY"
        - "PACE_CHIP_SECURITY"
        - "MIFARE_DATA"
        - "MIFARE_VALIDITY"
        - "AUTHENTICITY_V2"
        - "ATR"
        - "_E_SIGN_PK"
        - "_E_SIGN_SIGNED_DATA"
        - "CERTIFICATE"
        - "MASTER_LIST"
        - "DEFECT_LIST"
        - "BLACK_LIST"
        - "APP_DIRECTORY"
        - "SESSION"
        - "LOG_DATA"
        - "CHIP_PROPERTIES"
        - "POST_CA_RESPONSE"
        - "POST_CA_PUBLIC_KEY"
        - "POST_CA_INFO"
        - "POST_CA_D_PARAMS"
        - "POST_CA_CHECK_PK"
        - "POST_CA_CHECK_SK"
        - "USER_DEFINED"
