openapi: 3.0.4
components:
  schemas:
    RfidDataGroupTypeTag:
      title: "RfidDataGroupTypeTag"
      type: integer
      description: "Enumeration representing RFID Data Group Types.
      Constants with prefix  correspond to the informational data groups of ePassport
      application, with prefix EID_ – those of eID application, with prefix EDL_ –
      eDL application"
      enum:
        - 83
        - 96
        - 97
        - 98
        - 99
        - 100
        - 101
        - 102
        - 103
        - 104
        - 105
        - 106
        - 107
        - 108
        - 109
        - 110
        - 111
        - 112
        - 113
        - 114
        - 115
        - 116
        - 117
        - 118
        - 119
      x-enum-descriptions:
        - "eDL: Card Entitlement"
        - "Common Data Element"
        - "DG1: ePassport / eID / eDL"
        - "DG24: ePassport; eID: DG2"
        - "DG3: ePassport / eID; eDL: DG7"
        - "eID: DG4"
        - "DG5: ePassport / eID; eDL: DG4"
        - "DG6: ePassport / eID"
        - "DG7: ePassport / eID; eDL: DG5"
        - "DG8: ePassport / eID"
        - "DG9: ePassport / eID"
        - "DG10: ePassport / eID"
        - "DG11: ePassport / eID; eDL: DG2"
        - "DG12: ePassport / eID; eDL: DG3"
        - "DG13: ePassport / eID; eDL: DG11"
        - "DG14: ePassport / eID; eDL: DG14"
        - "DG15: ePassport / eID; eDL: DG13"
        - "DG16: ePassport / eID; eDL: DG9"
        - "DG17: ePassport / eID; eDL: DG12"
        - "DG18: ePassport / eID"
        - "DG22: ePassport; eID: DG19"
        - "DG23: ePassport; eID: DG20"
        - "DG2: ePassport; eID: DG21; eDL: DG6"
        - "DG4: ePassport; eDL: DG8"
        - "SOD: ePassport / eDL"
      x-enum-varnames:
        - "EDL_CE"
        - "EDL_COM__COM"
        - "EID_DG1__EDL_DG1__DG1"
        - "EID_DG2__DG24"
        - "EID_DG3__EDL_DG7__DG3"
        - "EID_DG4"
        - "EID_DG5__EDL_DG4__DG5"
        - "EID_DG6__DG6"
        - "EID_DG7__EDL_DG5__DG7"
        - "EID_DG8__DG8"
        - "EID_DG9__DG9"
        - "EID_DG10__DG10"
        - "EID_DG11__EDL_DG2__DG11"
        - "EID_DG12__EDL_DG3__DG12"
        - "EID_DG13__EDL_DG11__DG13"
        - "EID_DG14__EDL_DG14__DG14"
        - "EID_DG15__EDL_DG13__DG15"
        - "EID_DG16__EDL_DG9__DG16"
        - "EID_DG17__EDL_DG12__DG17"
        - "EID_DG18__DG18"
        - "EID_DG19__DG22"
        - "EID_DG20__DG23"
        - "EID_DG21__EDL_DG6__DG2"
        - "EDL_DG8__DG4"
        - "EDL_SOD__SOD"
