openapi: 3.0.4
components:
  schemas:
    RFIDErrorCodes:
      title: "RFIDErrorCodes"
      type: integer
      format: int64
      description: "Enumeration contains a set of error codes returned by SDK"
      enum:
        - 1
        - 2
        - 4294967295
        - 2147549185
        - 2147549186
        - 2147549188
        - 2147549189
        - 2147549190
        - 2147549191
        - 2147549192
        - 2147549193
        - 2147549194
        - 2147549195
        - 2147549196
        - 2147614720
        - 2147614721
        - 2147614722
        - 2147614723
        - 2147614724
        - 2147614725
        - 2147614726
        - 2147614736
        - 2248146944
        - 2248146945
        - 2248147200
        - 2248147201
        - 2248147202
        - 2248147203
        - 2248147456
        - 2248147457
        - 2248147458
        - 2248147459
        - 2248147460
        - 2248147712
        - 2248147713
        - 2248147714
        - 2248147715
        - 2248147716
        - 2248147717
        - 2248147718
        - 2248147719
        - 2248147720
        - 2248147721
        - 2147510914
        - 2147508866
        - 2147511040
        - 2147510016
        - 2147510912
        - 2147510920
        - 2147509185
        - 2147509184
        - 2147508867
        - 2147510659
        - 2147510660
        - 2147510661
        - 2148557760
        - 2197815296
        - 2197815297
        - 2197815298
        - 2197815312
        - 2197815313
        - 2197815314
        - 2197815315
        - 2197815316
        - 2197815317
        - 2197815318
        - 2197815319
        - 2197815320
        - 2197815321
        - 2197815322
        - 2197815323
        - 2197815324
        - 2197815328
        - 2197815329
        - 2197815330
        - 2197815331
        - 2197815332
        - 2197815333
        - 2197815334
        - 2197815335
        - 2197815336
        - 2197815337
        - 2197815338
        - 2197815344
        - 2197815345
        - 2197815360
        - 2197815361
        - 2197815362
        - 2197815376
        - 2197815377
        - 2197815378
        - 2197815392
        - 2197880832
        - 2197946368
        - 2198011904
        - 2198077440
        - 2198142976
        - 2198208512
        - 2198274048
        - 2198339584
        - 2214592512
        - 2214658048
        - 2214723584
        - 2214789120
        - 2214854656
        - 2214920192
        - 2214985728
        - 2215051264
        - 2215116800
        - 2215182336
        - 2215247872
        - 2215313408
        - 2215378944
        - 2215444480
        - 2215510016
        - 2215575552
      x-enum-descriptions:
        - "RFID: No error"
        - "RFID: Already done"
        - "RFID: Failed"
        - "RFID: No chip detected"
        - "RFID: Not available"
        - "RFID: Invalid parameter"
        - "RFID: Not initialized"
        - "RFID: Not enough memory"
        - "RFID: Not enough data"
        - "RFID: Invalid directory"
        - "RFID: Unknown command"
        - "RFID: File IO error"
        - "RFID: Busy"
        - "RFID: Old firmware"
        - "PCSC: Failed"
        - "PCSC: Reader not available"
        - "PCSC: Can't connect card"
        - "PCSC: Card is not connected"
        - "PCSC: Operation cancelled"
        - "PCSC: Card is busy"
        - "PCSC: Failed smart card"
        - "PCSC: ExtLe failed"
        - "Layer 6: Security manager"
        - "Layer 6: App selection failure"
        - "Layer 6: Mutual auth MAC fail"
        - "Layer 6: Mutual auth ENC fail"
        - "Layer 6: Mutual auth failure"
        - "Layer 6: Mutual auth failure data"
        - "Layer 6: SM DO8E missing"
        - "Layer 6: SM DO87 missing"
        - "Layer 6: SM DO99 missing"
        - "Layer 6: SM MAC incorrect"
        - "Layer 6: SM DO87 incorrect"
        - "Layer 6: NON TLV response data"
        - "Layer 6: Wrong RND ICC length"
        - "Layer 6: Int auth failure"
        - "Layer 6: MSE set KAT failure"
        - "Layer 6: MSE set DST failure"
        - "Layer 6: PSO certificate failure"
        - "Layer 6: MSE set at failure"
        - "Layer 6: Get challenge failure"
        - "Layer 6: EXT auth failure"
        - "Layer 6: GENERAL auth failure"
        - "Layer 6: File not found"
        - "Layer 6: File EOF1"
        - "Layer 6: File EOF2"
        - "Layer 6: Wrong length"
        - "Layer 6: Incorrect params"
        - "Layer 6: No reference data"
        - "Layer 6: PWD suspended"
        - "Layer 6: PWD blocked"
        - "Layer 6: PWD deactivated"
        - "Layer 6: PWD blocked 2"
        - "Layer 6: PWD deactivated 2"
        - "Layer 6: PWD suspended 2"
        - "Layer 6: PWD failed"
        - "RFID: NotPerformed"
        - "RFID: Session is closed"
        - "Session terminal: Unsupported operation"
        - "Session terminal type: Unknown"
        - "Session terminal type: Bad certificate"
        - "Session terminal type: Not set"
        - "Session procedure type: Unknown"
        - "Session procedure type: Unsupported"
        - "Session procedure type: Not set"
        - "Session access key: Unknown type"
        - "Session access key: Unsupported SM type"
        - "Session access key: Incorrect SM type"
        - "Session access key: Restricted"
        - "Session access key: Incorrect data"
        - "Session access key: Not set"
        - "Session pwd management: Not authorized"
        - "Session access control: Unknown type"
        - "Session access control: Requires SM"
        - "Session access control: Requires PACE"
        - "Session access control: Requires CA keys"
        - "Session access control: Requires TA"
        - "Session access control: Requires CA"
        - "Session access control: Incorrect option CA"
        - "Session access control: CA Failed"
        - "Session access control: TA Failed"
        - "Session access control: AA Failed"
        - "Session access control: RI Failed"
        - "Session PA: Signature check failed"
        - "Session PA: Hash check failed"
        - "Session invalid aux data: Date of expiry"
        - "Session invalid aux data: Date of birth"
        - "Session invalid aux data: Community ID"
        - "Session eSign: Requires app selection"
        - "Session eSign: PIN not set"
        - "Session eSign: PIN not verified"
        - "Session: Incorrect data"
        - "Session file: Not enough data"
        - "Session file: Incorrect data"
        - "Session file: Unexpected data"
        - "Session file: Contents unexpected data"
        - "Session file: Wrong tag"
        - "Session file: Cant use data"
        - "Session file: Cant read data"
        - "Session file: Access denied"
        - "Layer 34: No error"
        - "Layer 34: Time out"
        - "Layer 34: Collision"
        - "Layer 34: CRC"
        - "Layer 34: Data integrity"
        - "Layer 34: Data length"
        - "Layer 34: RFU"
        - "Layer 34: Collision too many"
        - "Layer 34: Protocol B"
        - "Layer 34: Data contents"
        - "Layer 34: Protocol"
        - "Layer 34: Global timeOut"
        - "Layer 34: MIFARE auth"
        - "Layer 34: SAM error"
        - "Layer 34: SAM collision"
        - "Layer 34: SAM acknowledge"
      x-enum-varnames:
        - "RFID_Error_NoError"
        - "RFID_Error_AlreadyDone"
        - "RFID_Error_Failed"
        - "RFID_Error_NoChipDetected"
        - "RFID_Error_NotAvailable"
        - "RFID_Error_InvalidParameter"
        - "RFID_Error_NotInitialized"
        - "RFID_Error_NotEnoughMemory"
        - "RFID_Error_NotEnoughData"
        - "RFID_Error_InvalidDirectory"
        - "RFID_Error_UnknownCommand"
        - "RFID_Error_FileIOError"
        - "RFID_Error_Busy"
        - "RFID_Error_OldFirmware"
        - "RFID_Error_PCSC_Failed"
        - "RFID_Error_PCSC_ReaderNotAvailable"
        - "RFID_Error_PCSC_CantConnectCard"
        - "RFID_Error_PCSC_CardIsNotConnected"
        - "RFID_Error_PCSC_OperationCancelled"
        - "RFID_Error_PCSC_CardIsBusy"
        - "RFID_Error_PCSC_FailedSCard"
        - "RFID_Error_PCSC_ExtLe_Failed"
        - "RFID_LAYER6_SECURITY_MANAGER"
        - "RFID_LAYER6_APP_SELECTION_FAILURE"
        - "RFID_LAYER6_MUTUAL_AUTH_MAC_FAIL"
        - "RFID_LAYER6_MUTUAL_AUTH_ENC_FAIL"
        - "RFID_LAYER6_MUTUAL_AUTH_FAILURE"
        - "RFID_LAYER6_MUTUAL_AUTH_FAILURE_DATA"
        - "RFID_LAYER6_SM_DO8E_MISSING"
        - "RFID_LAYER6_SM_DO87_MISSING"
        - "RFID_LAYER6_SM_DO99_MISSING"
        - "RFID_LAYER6_SM_MAC_INCORRECT"
        - "RFID_LAYER6_SM_DO87_INCORRECT"
        - "RFID_LAYER6_NON_TLV_RESPONSE_DATA"
        - "RFID_LAYER6_WRONG_RND_ICC_LENGTH"
        - "RFID_LAYER6_INT_AUTH_FAILURE"
        - "RFID_LAYER6_MSE_SET_KAT_FAILURE"
        - "RFID_LAYER6_MSE_SET_DST_FAILURE"
        - "RFID_LAYER6_PSO_CERTIFICATE_FAILURE"
        - "RFID_LAYER6_MSE_SET_AT_FAILURE"
        - "RFID_LAYER6_GET_CHALLENGE_FAILURE"
        - "RFID_LAYER6_EXT_AUTH_FAILURE"
        - "RFID_LAYER6_GENERAL_AUTH_FAILURE"
        - "RFID_LAYER6_FILE_NOT_FOUND"
        - "RFID_LAYER6_FILE_EOF1"
        - "RFID_LAYER6_FILE_EOF2"
        - "RFID_LAYER6_WRONG_LENGTH"
        - "RFID_LAYER6_INCORRECT_PARAMS"
        - "RFID_LAYER6_NO_REFERENCE_DATA"
        - "RFID_LAYER6_PWD_SUSPENDED"
        - "RFID_LAYER6_PWD_BLOCKED"
        - "RFID_LAYER6_PWD_DEACTIVATED"
        - "RFID_LAYER6_PWD_BLOCKED_2"
        - "RFID_LAYER6_PWD_DEACTIVATED_2"
        - "RFID_LAYER6_PWD_SUSPENDED_2"
        - "RFID_LAYER6_PWD_FAILED"
        - "RFID_Error_NotPerformed"
        - "RFID_Error_Session_IsClosed"
        - "RFID_Error_Session_Terminal_UnsupportedOperation"
        - "RFID_Error_Session_TerminalType_Unknown"
        - "RFID_Error_Session_TerminalType_BadCertificate"
        - "RFID_Error_Session_TerminalType_NotSet"
        - "RFID_Error_Session_ProcedureType_Unknown"
        - "RFID_Error_Session_ProcedureType_Unsupported"
        - "RFID_Error_Session_ProcedureType_NotSet"
        - "RFID_Error_Session_AccessKey_UnknownType"
        - "RFID_Error_Session_AccessKey_UnsupportedSMType"
        - "RFID_Error_Session_AccessKey_IncorrectSMType"
        - "RFID_Error_Session_AccessKey_Restricted"
        - "RFID_Error_Session_AccessKey_IncorrectData"
        - "RFID_Error_Session_AccessKey_NotSet"
        - "RFID_Error_Session_PwdManagement_NotAuthorized"
        - "RFID_Error_Session_AccessControl_UnknownType"
        - "RFID_Error_Session_AccessControl_RequiresSM"
        - "RFID_Error_Session_AccessControl_RequiresPACE"
        - "RFID_Error_Session_AccessControl_RequiresCAKeys"
        - "RFID_Error_Session_AccessControl_RequiresTA"
        - "RFID_Error_Session_AccessControl_RequiresCA"
        - "RFID_Error_Session_AccessControl_IncorrectOptionCA"
        - "RFID_Error_Session_AccessControl_CA_Failed"
        - "RFID_Error_Session_AccessControl_TA_Failed"
        - "RFID_Error_Session_AccessControl_AA_Failed"
        - "RFID_Error_Session_AccessControl_RI_Failed"
        - "RFID_Error_Session_PA_SignatureCheckFailed"
        - "RFID_Error_Session_PA_HashCheckFailed"
        - "RFID_Error_Session_InvalidAuxData_DateOfExpiry"
        - "RFID_Error_Session_InvalidAuxData_DateOfBirth"
        - "RFID_Error_Session_InvalidAuxData_CommunityID"
        - "RFID_Error_Session_eSign_RequiresAppSelection"
        - "RFID_Error_Session_eSign_PIN_NotSet"
        - "RFID_Error_Session_eSign_PIN_NotVerified"
        - "RFID_Error_Session_IncorrectData"
        - "RFID_Error_Session_File_NotEnoughData"
        - "RFID_Error_Session_File_IncorrectData"
        - "RFID_Error_Session_File_UnexpectedData"
        - "RFID_Error_Session_File_Contents_UnexpectedData"
        - "RFID_Error_Session_File_WrongTag"
        - "RFID_Error_Session_File_CantUseData"
        - "RFID_Error_Session_File_CantReadData"
        - "RFID_Error_Session_File_AccessDenied"
        - "RFID_Error_Layer34_NoError"
        - "RFID_Error_Layer34_TimeOut"
        - "RFID_Error_Layer34_Collision"
        - "RFID_Error_Layer34_CRC"
        - "RFID_Error_Layer34_DataIntegrity"
        - "RFID_Error_Layer34_DataLength"
        - "RFID_Error_Layer34_RFU"
        - "RFID_Error_Layer34_Collision_TooMany"
        - "RFID_Error_Layer34_ProtocolB"
        - "RFID_Error_Layer34_DataContents"
        - "RFID_Error_Layer34_Protocol"
        - "RFID_Error_Layer34_GlobalTimeOut"
        - "RFID_Error_Layer34_MIFARE_Auth"
        - "RFID_Error_Layer34_SAM_Error"
        - "RFID_Error_Layer34_SAM_Collision"
        - "RFID_Error_Layer34_SAM_Acknowledge"
