openapi: 3.0.4
components:
  schemas:
    SecurityFeatureType:
      title: "SecurityFeatureType"
      type: integer
      description: "Enumeration contains identifiers determining type of features for a document authenticity checks: https://docs.regulaforensics.com/develop/doc-reader-sdk/web-service/development/enums/security-feature-type/"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
        - 36
        - 38
        - 39
        - 40
        - 41
        - 42
        - 43
        - 44
        - 45
        - 46
        - 47
        - 48
        - 49
        - 50
        - 51
        - 52
        - 53
        - 54
      x-enum-descriptions:
        - "Blank element"
        - "Personalization element"
        - "Photo"
        - "MRZ"
        - "False luminescence"
        - "Hologram (static)"
        - "Hologram (static verify)"
        - "Hologram (static verify multiple)"
        - "Hologram (dynamic verify)"
        - "Pattern (non-interrupted)"
        - "Pattern (non-shifted)"
        - "Pattern (same colors)"
        - "Pattern (IR invisible)"
        - "Photo size"
        - "Main vs ghost portrait comparison"
        - "Main vs RFID portrait comparison"
        - "Main vs other page portrait comparison"
        - "Barcode"
        - "Pattern (different line thickness)"
        - "Main vs live camera portrait comparison"
        - "RFID vs live camera portrait comparison"
        - "Ghost photo"
        - "Clear ghost photo"
        - "Invisible object"
        - "Low contrast object"
        - "Photo color check"
        - "Photo squareness"
        - "Photo corners shape"
        - "OCR"
        - "External vs main portrait comparison"
        - "External vs RFID portrait comparison"
        - "External vs live camera portrait comparison"
        - "Portrait Depth"
        - "Micro text"
        - "Fluorescent Object"
        - "Facial landmarks check"
        - "Facial image presence"
        - "Facial image absence"
        - "Liveness screen capture. Deprecated. LIVENESS_ELECTRONIC_DEVICE is used instead."
        - "Liveness electronic device"
        - "Liveness OVI"
        - "Barcode size check"
        - "LASINK"
        - "Liveness MLI"
        - "Liveness barcode background"
        - "Visual zone portrait image vs. image from barcode"
        - "Image from barcode vs. image from RFID"
        - "Image from barcode vs. external source image"
        - "Image from barcode vs. photo from camera"
        - "Digital signature check"
        - "Contact chip check"
        - "Head position check"
        - "Black and white copy check"
        - "Liveness dynaprint"
      x-enum-varnames:
        - "BLANK"
        - "FILL"
        - "PHOTO"
        - "MRZ"
        - "FALSE_LUMINESCENCE"
        - "HOLO_SIMPLE"
        - "HOLO_VERIFY_STATIC"
        - "HOLO_VERIFY_MULTI_STATIC"
        - "HOLO_VERIFY_DYNAMIC"
        - "PATTERN_NOT_INTERRUPTED"
        - "PATTERN_NOT_SHIFTED"
        - "PATTERN_SAME_COLORS"
        - "PATTERN_IR_INVISIBLE"
        - "PHOTO_SIZE_CHECK"
        - "PORTRAIT_COMPARISON_VS_GHOST"
        - "PORTRAIT_COMPARISON_VS_RFID"
        - "PORTRAIT_COMPARISON_VS_VISUAL"
        - "BARCODE"
        - "PATTERN_DIFFERENT_LINES_THICKNESS"
        - "PORTRAIT_COMPARISON_VS_CAMERA"
        - "PORTRAIT_COMPARISON_RFID_VS_CAMERA"
        - "GHOST_PHOTO"
        - "CLEAR_GHOST_PHOTO"
        - "INVISIBLE_OBJECT"
        - "LOW_CONTRAST_OBJECT"
        - "PHOTO_COLOR"
        - "PHOTO_SHAPE"
        - "PHOTO_CORNERS"
        - "OCR"
        - "PORTRAIT_COMPARISON_EXT_VS_VISUAL"
        - "PORTRAIT_COMPARISON_EXT_VS_RFID"
        - "PORTRAIT_COMPARISON_EXT_VS_CAMERA"
        - "LIVENESS_DEPTH"
        - "MICRO_TEXT"
        - "FLUORESCENT_OBJECT"
        - "LANDMARK_CHECK"
        - "FACE_PRESENCE"
        - "FACE_ABSENCE"
        - "LIVENESS_SCREEN_CAPTURE"
        - "LIVENESS_ELECTRONIC_DEVICE"
        - "LIVENESS_OVI"
        - "BARCODE_SIZE_CHECK"
        - "LASINK"
        - "LIVENESS_MLI"
        - "LIVENESS_BARCODE_BACKGROUND"
        - "PORTRAIT_COMPARISON_VS_BARCODE"
        - "PORTRAIT_COMPARISON_RFID_VS_BARCODE"
        - "PORTRAIT_COMPARISON_EXT_VS_BARCODE"
        - "PORTRAIT_COMPARISON_BARCODE_VS_CAMERA"
        - "CHECK_DIGITAL_SIGNATURE"
        - "CONTACT_CHIP_CLASSIFICATION"
        - "HEAD_POSITION_CHECK"
        - "LIVENESS_BLACK_AND_WHITE_COPY_CHECK"
        - "LIVENESS_DYNAPRINT"
