openapi: 3.0.3
info:
  version: 5.2.0
  title: Regula Document Reader Web API
  description: Regula Document Reader Web API

servers:
  - url: http://localhost:8080/
    description: Local on-premise installation
  - url: https://api.regulaforensics.com/
    description: Regula document reader SaaS
  - url: https://test-api.regulaforensics.com/
    description: Regula document reader test SaaS

paths:
  /api/process:
    $ref: './p-process.yml#/paths/~1process'
  /api/ping:
    $ref: './p-ping.yml#/paths/~1ping'