openapi: 3.1.0

paths:
  /ping:
    get:
      summary: "Server health check"
      operationId: ping
      responses:
        200:
          description: "Device info"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceInfo'

components:
  schemas:
    DeviceInfo:
      type: object
      properties:
        app-name:
          type: string
        version:
          type: string
        license-id:
          type: string
        license-serial:
          type: string
        valid-until:
          type: string
          format: date-time
        server-time:
          type: string
          format: date-time
      example:
        app-name: "Regula Process Manager Service"
        version: "5.3.104980.123"
        license-id: "4d43a2af-e321-496c-9a4e-5a8f3d26df0e"
        license-serial: "OL70786"
        valid-until: "9999-12-31T23:59:59Z"
        server-time: "2020-10-16 09:42:08.080713+00:00"
