openapi: 3.0.4
paths:
  /ping:
    parameters:
      - $ref: "./common.yml#/components/parameters/x-request"
    get:
      deprecated: true
      summary: "Server health check"
      operationId: ping
      tags:
        - healthcheck
      responses:
        200:
          description: "Device info"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DeviceInfo"

components:
  schemas:
    DeviceInfo:
      title: "DeviceInfo"
      type: object
      properties:
        app-name:
          description: Application name.
          type: string
        version:
          description: Product version.
          type: string
        license-id:
          description: Unique license identifier.
          type: string
        license-serial:
          description: License serial number.
          type: string
        license-type:
          type: string
        valid-until:
          description: License validity date.
          type: string
          format: date-time
        server-time:
          type: string
        supported-scenarios:
          description: List of supported scenarios.
          type: array
          items:
            type: string
        metadata:
          type: object
          additionalProperties: true
        documents-database:
          description: Database information.
          type: object
          required:
            - id
            - version
            - export-date
            - description
          properties:
            id:
              description: Database identifier.
              type: string
              nullable: true
            version:
              description: Database version.
              type: string
              nullable: true
            export-date:
              description: Date of database creation.
              type: string
              nullable: true
            description:
              description: Description of the database contents, such as the list of supported countries and documents.
              type: string
              nullable: true
      example:
        app-name: "Regula Process Manager Service"
        version: "5.3.104980.123"
        license-id: "4d43a2af-e321-496c-9a4e-5a8f3d26df0e"
        license-serial: "OL70786"
        valid-until: "9999-12-31T23:59:59Z"
        server-time: "2020-10-16 09:42:08.080713+00:00"