openapi: 3.1.1
components:
  schemas:
    AuthenticityResult:
      title: "AuthenticityResult"
      allOf:
        - type: object
          required:
            - AuthenticityCheckList
          properties:
            AuthenticityCheckList:
              $ref: "#/components/schemas/AuthenticityCheckList"
        - $ref: "./rt.yml#/components/schemas/ResultItem"

    AuthenticityCheckList:
      title: "AuthenticityCheckList"
      type: object
      required:
        - Count
        - List
      properties:
        Count:
          type: integer
          description: "Count of items in List"
        List:
          type: array
          description: "Authenticity Check"
          items:
            $ref: "#/components/schemas/AuthenticityCheckResult"

    AuthenticityCheckResult:
      title: "AuthenticityCheckResult"
      type: object
      required:
        - Type
        - Result
        - List
      properties:
        Type:
          $ref: "./authenticity/e-result-type.yml#/components/schemas/AuthenticityResultType"
        Result:
          $ref: "./common.yml#/components/schemas/CheckResult"
        Count:
          type: integer
          description: "Count of items in List"
        List:
          type: array
          items:
            oneOf:
              - $ref: "./authenticity/rt-security-feature.yml#/components/schemas/SecurityFeatureResult"
              - $ref: "./authenticity/rt-ident.yml#/components/schemas/IdentResult"
              - $ref: "./authenticity/rt-fiber.yml#/components/schemas/FiberResult"
              - $ref: "./authenticity/rt-ocr-security-text.yml#/components/schemas/OCRSecurityTextResult"
              - $ref: "./authenticity/rt-photo-ident.yml#/components/schemas/PhotoIdentResult"

    AuthenticityType:
      title: "AuthenticityType"
      type: integer
      description: "Same as authenticity result type, but used for safe parsing of not-described values: https://docs.regulaforensics.com/develop/doc-reader-sdk/web-service/development/enums/authenticity-result-type/"
      default: 0

    AuthenticityCheckResultItem:
      title: "AuthenticityCheckResultItem"
      description: "Common fields for all authenticity result objects"
      type: object
      required:
        - Type
      properties:
        Type:
          $ref: "#/components/schemas/AuthenticityType"
        ElementResult:
          $ref: "./common.yml#/components/schemas/CheckResult"
        ElementDiagnose:
          $ref: "./authenticity/e-check-diagnose.yml#/components/schemas/CheckDiagnose"
        PercentValue:
          type: integer
          format: double

    AreaContainer:
      title: "AreaContainer"
      description: "Checked fragment coordinates"
      type: object
      required:
        - Count
        - List
        - Points
      properties:
        Count:
          type: integer
        List:
          type: array
          items:
            $ref: "./common.yml#/components/schemas/RectangleCoordinates"
        Points:
          type: array
          items:
            $ref: "#/components/schemas/PointsContainer"

    PointsContainer:
      title: "PointsContainer"
      type: object
      required:
        - PointsList
      properties:
        PointCount:
          type: integer
        PointsList:
          type: array
          items:
            $ref: "./common.yml#/components/schemas/Point"
