openapi: 3.0.4
components:
  schemas:
    AuthenticityCheckListItem:
      title: "AuthenticityCheckListItem"
      type: object
      required:
        - AuthenticityCheckList
      properties:
        AuthenticityCheckList:
          $ref: "#/components/schemas/AuthenticityCheckList"

    AuthenticityCheckList:
      title: "AuthenticityCheckList"
      type: object
      required:
        - Count
        - List
      properties:
        Count:
          type: integer
          description: "Count of items in List"
        List:
          type: array
          description: "Authenticity Check"
          items:
            $ref: "#/components/schemas/AuthenticityCheckResult"

    AuthenticityCheckResult:
      title: "AuthenticityCheckResult"
      type: object
      required:
        - Type
        - Result
        - List
      properties:
        Type:
          $ref: "./authenticity/e-result-type.yml#/components/schemas/AuthenticityResultType"
        Result:
          $ref: "./common.yml#/components/schemas/CheckResult"
        Count:
          type: integer
          description: "Count of items in List"
        List:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/SecurityFeatureResult"
              - $ref: "#/components/schemas/IdentResult"
              - $ref: "#/components/schemas/FiberResult"
              - $ref: "#/components/schemas/OCRSecurityTextResult"
              - $ref: "#/components/schemas/PhotoIdentResult"

    SecurityFeatureResult:
      title: "SecurityFeatureResult"
      allOf:
        - $ref: "#/components/schemas/AuthenticityCheckResultItem"
        - $ref: "./authenticity/rt-security-feature.yml#/components/schemas/SecurityFeatureItem"

    IdentResult:
      title: "IdentResult"
      allOf:
        - $ref: "#/components/schemas/AuthenticityCheckResultItem"
        - $ref: "./authenticity/rt-ident.yml#/components/schemas/IdentItem"

    FiberResult:
      title: "FiberResult"
      allOf:
        - $ref: "#/components/schemas/AuthenticityCheckResultItem"
        - $ref: "./authenticity/rt-fiber.yml#/components/schemas/FiberItem"

    OCRSecurityTextResult:
      title: "OCRSecurityTextResult"
      allOf:
        - $ref: "#/components/schemas/AuthenticityCheckResultItem"
        - $ref: "./authenticity/rt-ocr-security-text.yml#/components/schemas/OCRSecurityTextItem"

    PhotoIdentResult:
      title: "PhotoIdentResult"
      allOf:
        - $ref: "#/components/schemas/AuthenticityCheckResultItem"
        - $ref: "./authenticity/rt-photo-ident.yml#/components/schemas/PhotoIdentItem"

    AuthenticityCheckResultItem:
      title: "AuthenticityCheckResultItem"
      description: "Common fields for all authenticity result objects"
      type: object
      required:
        - Type
      properties:
        Type:
          $ref: "./authenticity/e-result-type.yml#/components/schemas/AuthenticityResultType"
        ElementResult:
          $ref: "./common.yml#/components/schemas/CheckResult"
        ElementDiagnose:
          $ref: "./authenticity/e-check-diagnose.yml#/components/schemas/CheckDiagnose"
        PercentValue:
          type: integer
          format: double
      discriminator:
        propertyName: Type
        mapping:
          1: "SecurityFeatureResult"
          2: "SecurityFeatureResult"
          4: "IdentResult"
          8: "SecurityFeatureResult"
          16: "FiberResult"
          32: "IdentResult"
          64: "OCRSecurityTextResult"
          128: "PhotoIdentResult"
          256: "PhotoIdentResult"
          512: "SecurityFeatureResult"
          1024: "IdentResult"
          2048: "IdentResult"
          4096: "SecurityFeatureResult"
          8192: "SecurityFeatureResult"
          16384: "FiberResult"
          32768: "IdentResult"
          65536: "SecurityFeatureResult"
          131072: "IdentResult"
          262144: "IdentResult"
          524288: "IdentResult"
          1048576: "IdentResult"
          2097152: "IdentResult"
          4194304: "SecurityFeatureResult"
          8388608: "SecurityFeatureResult"
          16777216: "OCRSecurityTextResult"
          2147483648: "SecurityFeatureResult"

    AreaContainer:
      title: "AreaContainer"
      description: "Checked fragment coordinates"
      type: object
      required:
        - Count
        - List
        - Points
      properties:
        Count:
          type: integer
        List:
          type: array
          items:
            $ref: "./common.yml#/components/schemas/RectangleCoordinates"
        Points:
          type: array
          items:
            $ref: "#/components/schemas/PointsContainer"

    PointsContainer:
      title: "PointsContainer"
      type: object
      required:
        - PointsList
      properties:
        PointCount:
          type: integer
        PointsList:
          type: array
          items:
            $ref: "./common.yml#/components/schemas/Point"
