openapi: 3.0.4
components:
  schemas:
    DocBarCodeInfoItem:
      title: "DocBarCodeInfoItem"
      type: object
      required:
        - DocBarCodeInfo
      properties:
        DocBarCodeInfo:
          $ref: "#/components/schemas/DocBarCodeInfoFieldsList"

    DocBarCodeInfoFieldsList:
      title: "DocBarCodeInfoFieldsList"
      type: object
      required:
        - nFields
        - pArrayFields
      properties:
        nFields:
          type: integer
          description: "Count of array fields"
        pArrayFields:
          type: array
          description: "Data from barcode"
          items:
            $ref: "#/components/schemas/pArrayField"

    pArrayField:
      title: "pArrayField"
      type: object
      required:
        - bcAngle_DETECT
        - bcCodeResult
        - bcCountModule
        - bcDataModule
        - bcROI_DETECT
        - bcType_DECODE
        - bcType_DETECT
      properties:
        bcAngle_DETECT:
          type: number
          format: float
        bcCodeResult:
          type: integer
        bcCountModule:
          type: integer
        bcDataModule:
          type: array
          items:
            $ref: "#/components/schemas/DataModule"
        bcPDF417INFO:
          $ref: "#/components/schemas/bcPDF417INFO"
        bcROI_DETECT:
          $ref: "#/components/schemas/bcROI_DETECT"
        bcTextDecoderTypes:
          type: integer
        bcTextFieldType:
          type: integer
        bcType_DECODE:
          $ref: "./e-barcode-type.yml#/components/schemas/BarcodeType"
        bcType_DETECT:
          type: integer

    bcPDF417INFO:
      title: "bcPDF417INFO"
      type: object
      required:
        - Angle
        - bcColumn
        - bcErrorLevel
        - bcRow
        - minX
        - minY
      properties:
        Angle:
          type: number
          format: float
        bcColumn:
          type: integer
        bcErrorLevel:
          type: integer
        bcRow:
          type: integer
        minX:
          type: number
          format: float
        minY:
          type: number
          format: float

    bcROI_DETECT:
      title: "bcROI_DETECT"
      type: object
      required:
        - bottom
        - left
        - right
        - top
      properties:
        bottom:
          type: integer
        left:
          type: integer
        right:
          type: integer
        top:
          type: integer

    DataModule:
      title: "DataModule"
      type: object
      required:
        - mData
        - mLength
        - mType
      properties:
        mData:
          type: string
        mLength:
          type: integer
        mReserved1:
          type: integer
        mReserver2:
          type: integer
        mType:
          $ref: "#/components/schemas/BarCodeModuleType"

    BarCodeModuleType:
      title: "BarCodeModuleType"
      type: integer
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
      x-enum-descriptions:
        - "Module contains text data"
        - "Module contains byte data"
        - "Module contains numeric data"
        - "Shifts in byte compaction mode (for PDF417)"
        - "Module contains any data"
      x-enum-varnames:
        - "TEXT"
        - "BYTE"
        - "NUM"
        - "SHIFT"
        - "ALL"
