openapi: 3.1.1
info:
  version: 7.4.0
  title: Regula Document Reader Web API
components:
  schemas:
    ByteArrayResult:
      title: "ByteArrayResult"
      allOf:
        - type: object
          required:
            - ByteArray
          properties:
            ByteArray:
              description: "Byte array in base64"
              type: string
        - $ref: "./rt.yml#/components/schemas/ResultItem"
