openapi: 3.0.4
components:
  schemas:
    ByteArrayItem:
      title: "ByteArrayItem"
      type: object
      required:
        - ByteArray
      properties:
        ByteArray:
          description: "Byte array in base64"
          type: string
