openapi: 3.0.4
components:
  schemas:
    DocumentPositionItem:
      title: "DocumentPositionItem"
      type: object
      required:
        - DocumentPosition
      properties:
        DocumentPosition:
          $ref: "./common.yml#/components/schemas/DocumentPosition"
