openapi: 3.0.3
components:
  schemas:

    ImagesResult:
      allOf:
        - $ref: './rt.yml#/components/schemas/ResultItem'
        - type: object
          required:
            - Images
          properties:
            Images:
              $ref: '#/components/schemas/Images'

    Images:
      type: object
      required:
        - availableSourceList
        - fieldList
      properties:
        availableSourceList:
          type: array
          items:
            $ref: '#/components/schemas/ImagesAvailableSource'
        fieldList:
          type: array
          items:
            $ref: '#/components/schemas/ImagesField'

    ImagesAvailableSource:
      type: object
      required:
        - source
        - sourceName
      properties:
        containerType:
          $ref: './rt.yml#/components/schemas/ContainerType'
        source:
          $ref: './common.yml#/components/schemas/Source'

    ImagesField:
      type: object
      required:
        - fieldName
        - fieldType
        - valueList
      properties:
        fieldName:
          $ref: "./e-graphic-field-type.yml#/components/schemas/GraphicFieldName"
        fieldType:
          $ref: "./e-graphic-field-type.yml#/components/schemas/GraphicFieldType"
        valueList:
          type: array
          items:
            $ref: "#/components/schemas/ImagesFieldValue"

    ImagesFieldValue:
      type: object
      required:
        - containerType
        - lightIndex
        - pageIndex
        - source
        - value
      properties:
        source:
          $ref: './common.yml#/components/schemas/Source'
        value:
          $ref: './common.yml#/components/schemas/ImageBase64'
        originalValue:
          description: "Only for images from RFID. Image as was originally stored in the RFID chip."
          $ref: './common.yml#/components/schemas/ImageBase64'
        pageIndex:
          $ref: './common.yml#/components/schemas/PageIndex'
        lightIndex:
          $ref: './common.yml#/components/schemas/Light'
        containerType:
          $ref: './rt.yml#/components/schemas/ContainerType'
        fieldRect:
          description: "Only for images from VISUAL. Coordinates of the image in the normalized image of the document."
          $ref: "./common.yml#/components/schemas/RectangleCoordinates"
        rfidOrigin:
          description: "Only for images from RFID. Image location in RFID chip."
          $ref: "./common.yml#/components/schemas/RfidOrigin"