openapi: 3.1.1
components:
  schemas:
    ImagesResult:
      title: "ImagesResult"
      allOf:
        - type: object
          required:
            - Images
          properties:
            Images:
              $ref: "#/components/schemas/Images"
        - $ref: "./rt.yml#/components/schemas/ResultItem"

    Images:
      title: "Images"
      type: object
      required:
        - availableSourceList
        - fieldList
      properties:
        fieldCount:
          type: integer
          description: "Fields count"
        availableSourceCount:
          type: integer
          description: "Available sources count"
        availableSourceList:
          type: array
          items:
            $ref: "#/components/schemas/ImagesAvailableSource"
        fieldList:
          type: array
          items:
            $ref: "#/components/schemas/ImagesField"

    ImagesAvailableSource:
      title: "ImagesAvailableSource"
      type: object
      required:
        - containerType
        - source
      properties:
        containerType:
          $ref: "./rt.yml#/components/schemas/ContainerType"
        source:
          $ref: "./common.yml#/components/schemas/Source"

    ImagesField:
      title: "ImagesField"
      type: object
      required:
        - fieldName
        - fieldType
        - valueList
      properties:
        fieldName:
          $ref: "./e-graphic-field-type.yml#/components/schemas/GraphicFieldName"
        fieldType:
          $ref: "./e-graphic-field-type.yml#/components/schemas/GraphicFieldType"
        valueList:
          type: array
          items:
            $ref: "#/components/schemas/ImagesFieldValue"
        valueCount:
          description: "Field value count"
          type: number

    ImagesFieldValue:
      title: "ImagesFieldValue"
      type: object
      required:
        - containerType
        - lightIndex
        - pageIndex
        - source
      properties:
        source:
          $ref: "./common.yml#/components/schemas/Source"
        value:
          $ref: "./common.yml#/components/schemas/ImageBase64"
        originalValue: # Only for images from RFID. Image as was originally stored in the RFID chip.
          $ref: "./common.yml#/components/schemas/ImageBase64"
        originalPageIndex:
          description: "Original page index"
          type: integer
        pageIndex:
          $ref: "./common.yml#/components/schemas/PageIndex"
        lightIndex:
          $ref: "./common.yml#/components/schemas/Light"
        containerType:
          $ref: "./rt.yml#/components/schemas/ContainerType"
        fieldRect: # Only for images from VISUAL. Coordinates of the image in the normalized image of the document.
          $ref: "./common.yml#/components/schemas/RectangleCoordinates"
        rfidOrigin:
          description: # Only for images from RFID. Image location in RFID chip.
          $ref: "./common.yml#/components/schemas/RfidOrigin"
