openapi: 3.0.3
components:
  schemas:

    ImageQualityListResult:
      allOf:
        - type: object
          required:
            - ImageQualityChecks
          properties:
            ImageQualityChecks:
              $ref: '#/components/schemas/ImageQualityChecks'
        - $ref: './rt.yml#/components/schemas/ResultItem'


    ImageQualityChecks:
      type: object
      properties:
        result:
          description: 'Overall checks status. Root status.'
          $ref: './common.yml#/components/schemas/CheckResult'
        List:
          type: array
          items:
            $ref: '#/components/schemas/ImageQualityCheck'

    ImageQualityCheckType:
      type: integer
      description: ''
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      x-enum-varnames:
        - 'ImageGlares'
        - 'ImageFocus'
        - 'ImageResolution'
        - 'ImageColorness'
        - 'Perspective'
        - 'Bounds'
      x-enum-descriptions:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''

    AreaArray:
      type: object
      properties:
        List:
          type: array
          items:
            $ref: './common.yml#/components/schemas/RectangleCoordinates'
        Points:
          $ref: '#/components/schemas/PointArray'

    PointArray:
      type: object
      properties:
        PointsList:
          type: array
          items:
            $ref: './common.yml#/components/schemas/Point'

    ImageQualityCheck:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ImageQualityCheckType'
        result:
          $ref: './common.yml#/components/schemas/CheckResult'
        featureType:
          $ref: './e-security-feature-type.yml#/components/schemas/SecurityFeatureType'
        areas:
          $ref: '#/components/schemas/AreaArray'
        mean:
          type: number
          format: float
        std_dev:
          type: number
          format: float
        probability:
          # todo 0-1 or 0-100 ?
          type: integer
