openapi: 3.0.3
components:
  schemas:
    GraphicsResult:
      title: "GraphicsResult"
      description: "Graphic fields extracted from one of the document sources.
      Returns separate results for each provided page."
      required:
        - DocGraphicsInfo
      allOf:
        - type: object
          properties:
            DocGraphicsInfo:
              $ref: "#/components/schemas/GraphicFieldsList"
        - $ref: "./rt.yml#/components/schemas/ResultItem"

    GraphicFieldsList:
      title: "GraphicFieldsList"
      type: object
      required:
        - pArrayFields
        - nFields
      properties:
        pArrayFields:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/GraphicFieldRect"
              - $ref: "#/components/schemas/GraphicFieldRfid"
        nFields:
          description: "Number of pArrayFields array elements"
          type: number

    GraphicFieldRect:
      title: "GraphicFieldRect"
      description: "Information about one graphic field, which is a rectangle"
      required:
        - FieldRect
      allOf:
        - type: object
          properties:
            FieldRect:
              $ref: "./common.yml#/components/schemas/RectangleCoordinates"
        - $ref: "#/components/schemas/GraphicField"

    GraphicFieldRfid:
      title: "GraphicFieldRfid"
      description: "Information about one graphic field, which is a RFID"
      required:
        - RFID_OriginDG
        - RFID_OriginDGTag
        - RFID_OriginTagEntry
        - RFID_OriginEntryView
      allOf:
        - type: object
          properties:
            RFID_OriginDG:
              $ref: "./e-rfid-data-group-type-tag.yml#/components/schemas/RfidDataGroupTypeTag"
            RFID_OriginDGTag:
              description: "Index of the source record of the image with biometric information in the information data group. Only for Result.RFID_GRAPHICS result."
              type: integer
            RFID_OriginTagEntry:
              type: integer
              description: "Index of the template in the record with biometric data. Only for Result.RFID_GRAPHICS result."
            RFID_OriginEntryView:
              type: integer
              description: "Index of the variant of the biometric data template. Only for Result.RFID_GRAPHICS result."
        - $ref: "#/components/schemas/GraphicField"

    GraphicField:
      title: "GraphicField"
      description: "Information about one graphic field - abstract class"
      type: object
      required:
        - FieldType
        - FieldName
        - image
      properties:
        FieldType:
          $ref: "./e-graphic-field-type.yml#/components/schemas/GraphicFieldType"
        FieldName:
          description: "Graphic field symbolic name"
          type: string
        image:
          $ref: "./common.yml#/components/schemas/ImageData"
