openapi: 3.0.4
components:
  schemas:
    DocGraphicsInfoItem:
      title: "DocGraphicsInfoItem"
      type: object
      required:
        - DocGraphicsInfo
      properties:
        DocGraphicsInfo:
          $ref: "#/components/schemas/GraphicFieldsList"

    GraphicFieldsList:
      title: "GraphicFieldsList"
      type: object
      required:
        - pArrayFields
        - nFields
      properties:
        pArrayFields:
          type: array
          items:
            $ref: "#/components/schemas/GraphicField"
        nFields:
          description: "Number of pArrayFields array elements"
          type: number

    GraphicField:
      title: "GraphicField"
      description: "Information about one graphic field - abstract class"
      type: object
      required:
        - FieldRect
        - FieldType
        - FieldName
        - image
      properties:
        FieldRect:
          $ref: "./common.yml#/components/schemas/RectangleCoordinates"
        FieldType:
          $ref: "./e-graphic-field-type.yml#/components/schemas/GraphicFieldType"
        FieldName:
          description: "Graphic field symbolic name"
          type: string
        image:
          $ref: "./common.yml#/components/schemas/ImageData"
