openapi: 3.0.3
components:
  schemas:

    ImageQualityCheckType:
      type: integer
      description: ''
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
      x-enum-varnames:
        - 'ImageGlares'
        - 'ImageFocus'
        - 'ImageResolution'
        - 'ImageColorness'
        - 'Perspective'
        - 'Bounds'
      x-enum-descriptions:
        - ''
        - ''
        - ''
        - ''
        - ''
        - ''

    AreaArray:
      type: object
      properties:
        _List:
          type: array
          items:
            $ref: './common.yml#/components/schemas/RectangleCoordinates'
        Points:
          type: array
          items:
            $ref: './common.yml#/components/schemas/Point'

    ImageQualityCheck:
      type: object
      properties:
        Type:
          $ref: '#/components/schemas/ImageQualityCheckType'
        Result:
          $ref: './common.yml#/components/schemas/CheckResult'
        FeatureType:
          $ref: './e-security-feature-type.yml#/components/schemas/SecurityFeatureType'
        Areas:
          type: object
          items:
            $ref: '#/components/schemas/AreaArray'
        Mean:
          type: number
        StdDev:
          type: number
        Probability:
          type: integer

    ImageQualityListResult:
      title: "ImageQualityCheckList"
      allOf:
        - type: object
          properties:
            Result:
              description: 'Overall checks status. Root status.'
              $ref: './common.yml#/components/schemas/CheckResult'
            _List:
              type: array
              items:
                $ref: '#/components/schemas/ImageQualityCheck'

    