openapi: 3.0.4
components:
  schemas:
    DocGraphicsInfoItem:
      title: "DocGraphicsInfoItem"
      type: object
      required:
        - DocGraphicsInfo
      properties:
        DocGraphicsInfo:
          $ref: "#/components/schemas/GraphicFieldsList"

    GraphicFieldsList:
      title: "GraphicFieldsList"
      type: object
      required:
        - pArrayFields
        - nFields
      properties:
        pArrayFields:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/GraphicFieldRect"
              - $ref: "#/components/schemas/GraphicFieldRfid"
        nFields:
          description: "Number of pArrayFields array elements"
          type: number

    GraphicFieldRect:
      title: "GraphicFieldRect"
      description: "Information about one graphic field, which is a rectangle"
      allOf:
        - $ref: "#/components/schemas/GraphicField"
        - $ref: "#/components/schemas/GraphicFieldRectItem"

    GraphicFieldRfid:
      title: "GraphicFieldRfid"
      description: "Information about one graphic field, which is a RFID"
      allOf:
        - $ref: "#/components/schemas/GraphicField"
        - $ref: "#/components/schemas/GraphicFieldRfidItem"

    GraphicFieldRectItem:
      title: "GraphicFieldRectItem"
      type: object
      required:
        - FieldRect
      properties:
        FieldRect:
          $ref: "./common.yml#/components/schemas/RectangleCoordinates"

    GraphicFieldRfidItem:
      title: "GraphicFieldRfidItem"
      type: object
      required:
        - RFID_OriginDG
        - RFID_OriginDGTag
        - RFID_OriginTagEntry
        - RFID_OriginEntryView
      properties:
        RFID_OriginDG:
          $ref: "./e-rfid-data-group-type-tag.yml#/components/schemas/RfidDataGroupTypeTag"
        RFID_OriginDGTag:
          description: "Index of the source record of the image with biometric information in the information data group. Only for Result.RFID_GRAPHICS result."
          type: integer
        RFID_OriginTagEntry:
          type: integer
          description: "Index of the template in the record with biometric data. Only for Result.RFID_GRAPHICS result."
        RFID_OriginEntryView:
          type: integer
          description: "Index of the variant of the biometric data template. Only for Result.RFID_GRAPHICS result."

    GraphicField:
      title: "GraphicField"
      description: "Information about one graphic field - abstract class"
      type: object
      required:
        - FieldType
        - FieldName
        - image
      properties:
        FieldType:
          $ref: "./e-graphic-field-type.yml#/components/schemas/GraphicFieldType"
        FieldName:
          description: "Graphic field symbolic name"
          type: string
        image:
          $ref: "./common.yml#/components/schemas/ImageData"
