openapi: 3.1.1
info:
  version: 7.4.0
  title: Regula Document Reader Web API
components:
  schemas:
    LicenseResult:
      title: "LicenseResult"
      allOf:
        - type: object
          description: "Contains license"
          required:
            - License
          properties:
            License:
              $ref: "./common.yml#/components/schemas/License"
        - $ref: "./rt.yml#/components/schemas/ResultItem"
