openapi: 3.1.1
info:
  version: 7.4.0
  title: Regula Document Reader Web API
components:
  schemas:
    MRZDetectorResult:
      title: "MRZDetectorResult"
      allOf:
        - type: object
          required:
            - ResultMRZDetector
          properties:
            ResultMRZDetector:
              $ref: "#/components/schemas/ResultMRZDetector"
        - $ref: "./rt.yml#/components/schemas/ResultItem"

    ResultMRZDetector:
      title: "ResultMRZDetector"
      type: object
      required:
        - MRZFormat
        - MRZRows
        - MRZRowsNum
        - boundingQuadrangle
      properties:
        MRZFormat:
          type: integer
        MRZRows:
          type: array
          items:
            $ref: "#/components/schemas/MRZRowsItem"
        MRZRowsNum:
          type: integer
        boundingQuadrangle:
          type: array
          items:
            type: integer

    MRZRowsItem:
      title: "MRZRowsItem"
      type: object
      required:
        - length
        - maxLength
        - symbols
      properties:
        length:
          type: integer
        maxLength:
          type: integer
        symbols:
          type: array
          items:
            $ref: "#/components/schemas/Symbol"

    Symbol:
      title: "Symbol"
      type: object
      required:
        - boundingRect
      properties:
        boundingRect:
          type: array
          items:
            type: integer
