openapi: 3.0.4
components:
  schemas:
    MrzPositionItem:
      title: "MrzPositionItem"
      type: object
      required:
        - MrzPosition
      properties:
        MrzPosition:
          $ref: "./common.yml#/components/schemas/DocumentPosition"
