openapi: 3.1.1
info:
  version: 7.4.0
  title: Regula Document Reader Web API
components:
  schemas:
    DocumentImageResult:
      title: "DocumentImageResult"
      description: "Contains document image."
      allOf:
        - type: object
          required:
            - RawImageContainer
          properties:
            RawImageContainer:
              $ref: "./common.yml#/components/schemas/ImageData"
        - $ref: "./rt.yml#/components/schemas/ResultItem"
