openapi: 3.0.3
components:
  schemas:

    DocumentImageResult:
      title: "Document Image"
      description: "Contains cropped and rotated with perspective compensation image of document.
        Single input image can contain multiple document side/pages, which will be returned as separated results.
        Most of coordinates in other types defined on that image"
      allOf:
        - type: object
          required:
            - RawImageContainer
          properties:
            RawImageContainer:
              $ref: "#/components/schemas/RawImageContainerFieldList"
        - $ref: "./rt.yml#/components/schemas/ResultItem"

    RawImageContainerFieldList:
      title: "RawImageContainerFieldList"
      allOf:
        - type: object
          required:
            - format
          properties:
            format:
              description: "Image format"
              type: string
        - $ref: "./common.yml#/components/schemas/ImageData"
