openapi: 3.0.4
components:
  schemas:
    StatusItem:
      title: "StatusItem"
      type: object
      required:
        - Status
      properties:
        Status:
          $ref: "#/components/schemas/Status"

    Status:
      title: "Status"
      type: object
      required:
        - overallStatus
        - optical
        - portrait
        - rfid
        - stopList
        - detailsOptical
        - age
        - detailsAge
        - mDL
      properties:
        overallStatus:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Overall checks status. Rootx status"
        optical:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Overall optical checks combined status"
        portrait:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Portrait comparison status"
        rfid:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Overall RFID checks combined status"
        stopList:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Stop list check status"
        detailsRFID:
          $ref: "#/components/schemas/detailsRFID"
        detailsOptical:
          $ref: "#/components/schemas/detailsOptical"
        age:
          $ref: "./common.yml#/components/schemas/CheckResult"
        detailsAge:
          $ref: "#/components/schemas/DetailsAge"
        mDL:
          $ref: "./common.yml#/components/schemas/CheckResult"

    detailsOptical:
      title: "detailsOptical"
      description: "Details on performed optical checks"
      type: object
      required:
        - overallStatus
        - docType
        - expiry
        - imageQA
        - mrz
        - pagesCount
        - security
        - text
      properties:
        overallStatus:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Overall optical checks combined status"
        docType:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Status of document type recognition"
        expiry:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Status of document expiration"
        imageQA:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Status of document image quality check"
        mrz:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Status of document MRZ"
        pagesCount:
          description: "Number of processed pages in the document"
          type: integer
        security:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Authenticity verification status"
        text:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Status of text fields analysis"
        vds:
          type: integer

    detailsRFID:
      title: "detailsRFID"
      description: "Details on performed RFID checks"
      type: object
      required:
        - overallStatus
        - AA
        - BAC
        - CA
        - PA
        - PACE
        - TA
      properties:
        overallStatus:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Overall RFID checks combined status"
        AA:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Active Authentication status"
        BAC:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Basic Access Control (BAC) status"
        CA:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Chip Authentication status"
        PA:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Passive Authentication status"
        PACE:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Password Authenticated Connection Establishment (PACE) status"
        TA:
          allOf:
            - $ref: "./common.yml#/components/schemas/CheckResult"
          description: "Terminal Authentication status"

    DetailsAge:
      title: "DetailsAge"
      type: object
      required:
        - threshold
        - overThreshold
        - over18
        - over21
        - over25
        - over65
      properties:
        threshold:
          type: integer
        overThreshold:
          $ref: "./common.yml#/components/schemas/CheckResult"
        over18:
          $ref: "./common.yml#/components/schemas/CheckResult"
        over21:
          $ref: "./common.yml#/components/schemas/CheckResult"
        over25:
          $ref: "./common.yml#/components/schemas/CheckResult"
        over65:
          $ref: "./common.yml#/components/schemas/CheckResult"
