openapi: 3.1.1
components:
  schemas:
    StatusResult:
      title: "StatusResult"
      allOf:
        - type: object
          required:
            - Status
          properties:
            Status:
              $ref: "#/components/schemas/Status"
        - $ref: "./rt.yml#/components/schemas/ResultItem"

    Status:
      title: "Status"
      type: object
      required:
        - overallStatus
        - optical
        - portrait
        - rfid
        - stopList
        - detailsOptical
      properties:
        overallStatus: # Overall checks status. Rootx status
          $ref: "./common.yml#/components/schemas/CheckResult"
        optical: # Overall optical checks combined status
          $ref: "./common.yml#/components/schemas/CheckResult"
        portrait: # Portrait comparison status
          $ref: "./common.yml#/components/schemas/CheckResult"
        rfid: # Overall RFID checks combined status
          $ref: "./common.yml#/components/schemas/CheckResult"
        stopList: # Stop list check status
          $ref: "./common.yml#/components/schemas/CheckResult"
        detailsRFID:
          $ref: "#/components/schemas/detailsRFID"
        detailsOptical:
          $ref: "#/components/schemas/detailsOptical"

    detailsOptical:
      title: "detailsOptical"
      description: "Details on performed optical checks"
      type: object
      required:
        - overallStatus
        - docType
        - expiry
        - imageQA
        - mrz
        - pagesCount
        - security
        - text
      properties:
        overallStatus: # Overall optical checks combined status
          $ref: "./common.yml#/components/schemas/CheckResult"
        docType: # Status of document type recognition
          $ref: "./common.yml#/components/schemas/CheckResult"
        expiry: # Status of document expiration
          $ref: "./common.yml#/components/schemas/CheckResult"
        imageQA: # Status of document image quality check
          $ref: "./common.yml#/components/schemas/CheckResult"
        mrz: # Status of document MRZ
          $ref: "./common.yml#/components/schemas/CheckResult"
        pagesCount:
          description: "Number of processed pages in the document"
          type: integer
        security: # Authenticity verification status
          $ref: "./common.yml#/components/schemas/CheckResult"
        text: # Status of text fields analysis
          $ref: "./common.yml#/components/schemas/CheckResult"
        vds:
          type: integer

    detailsRFID:
      title: "detailsRFID"
      description: "Details on performed RFID checks"
      type: object
      required:
        - overallStatus
        - AA
        - BAC
        - CA
        - PA
        - PACE
        - TA
      properties:
        overallStatus: # Overall RFID checks combined status
          $ref: "./common.yml#/components/schemas/CheckResult"
        AA: # Active Authentication status
          $ref: "./common.yml#/components/schemas/CheckResult"
        BAC: # Basic Access Control (BAC) status
          $ref: "./common.yml#/components/schemas/CheckResult"
        CA: # Chip Authentication status
          $ref: "./common.yml#/components/schemas/CheckResult"
        PA: # Passive Authentication status
          $ref: "./common.yml#/components/schemas/CheckResult"
        PACE: # Password Authenticated Connection Establishment (PACE) status
          $ref: "./common.yml#/components/schemas/CheckResult"
        TA: # Terminal Authentication status
          $ref: "./common.yml#/components/schemas/CheckResult"
