openapi: 3.0.3
components:
  schemas:

    StatusResult:
      allOf:
        - $ref: './rt.yml#/components/schemas/ResultItem'
        - type: object
          required:
            - Status
          properties:
            Status:
              $ref: '#/components/schemas/Status'

    # $ref with description doesnt work right now, waiting for OAS 3.1 (comming soon)
    # allOf should be used here to replace description from CheckResult
    # see https://github.com/OAI/OpenAPI-Specification/issues/556#issuecomment-192007034
    # but java codegen produce invalid code for allOf `int complete=null`
    Status:
      type: object
      required:
        - overallStatus
        - optical
        - detailsOptical
      properties:
        overallStatus:
          description: "Overall checks status. Root status."
          $ref: "./common.yml#/components/schemas/CheckResult"
        optical:
          description: "Overall optical checks combined status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        portrait:
          description: "Portrait comparison status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        rfid:
          description: "Overall RFID checks combined status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        stopList:
          description: "Stop list check status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        detailsRFID:
          description: "Details on performed RFID checks"
          $ref: "#/components/schemas/detailsRFID"
        detailsOptical:
          description: "Details on performed optical checks"
          $ref: "#/components/schemas/detailsOptical"

    detailsOptical:
      type: object
      required:
        - overallStatus
        - docType
        - expiry
        - imageQA
        - mrz
        - pagesCount
        - security
        - text
      properties:
        overallStatus:
          description: "Overall optical checks combined status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        docType:
          description: "Status of document type recognition"
          $ref: "./common.yml#/components/schemas/CheckResult"
        expiry:
          description: "Status of document expiration"
          $ref: "./common.yml#/components/schemas/CheckResult"
        imageQA:
          description: "Status of document image quality check"
          $ref: "./common.yml#/components/schemas/CheckResult"
        mrz:
          description: "Status of document MRZ"
          $ref: "./common.yml#/components/schemas/CheckResult"
        pagesCount:
          description: "Number of processed pages in the document"
          type: integer
        security:
          description: "Status of document MRZ"
          $ref: "./common.yml#/components/schemas/CheckResult"
        text:
          description: "Status of text fields analysis"
          $ref: "./common.yml#/components/schemas/CheckResult"

    detailsRFID:
      type: object
      required:
        - overallStatus
        - AA
        - BAC
        - CA
        - PA
        - PACE
        - TA
      properties:
        overallStatus:
          description: "Overall RFID checks combined status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        AA:
          description: "Active Authentication status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        BAC:
          description: "Basic Access Control (BAC) status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        CA:
          description: "Chip Authentication status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        PA:
          description: "Passive Authentication status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        PACE:
          description: "Password Authenticated Connection Establishment (PACE) status"
          $ref: "./common.yml#/components/schemas/CheckResult"
        TA:
          description: "Terminal Authentication status"
          $ref: "./common.yml#/components/schemas/CheckResult"
