openapi: 3.0.4
components:
  schemas:
    DocVisualExtendedInfoItem:
      title: "DocVisualExtendedInfoItem"
      type: object
      required:
        - DocVisualExtendedInfo
      properties:
        DocVisualExtendedInfo:
          $ref: "#/components/schemas/DocVisualExtendedInfo"

    DocVisualExtendedInfo:
      title: "DocVisualExtendedInfo"
      type: object
      description: "Container for extracted text fields. Fields are identified by type and language"
      required:
        - nFields
        - pArrayFields
      properties:
        nFields:
          description: "Number of pArrayFields array elements"
          type: number
        pArrayFields:
          type: array
          items:
            $ref: "#/components/schemas/DocVisualExtendedField"

    DocVisualExtendedField:
      title: "DocVisualExtendedField"
      type: object
      required:
        - FieldRect
      allOf:
        - $ref: "./common.yml#/components/schemas/VisualExtendedFieldItem"
        - $ref: "#/components/schemas/DocVisualExtendedFieldItem"

    DocVisualExtendedFieldItem:
      title: "DocVisualExtendedFieldItem"
      type: object
      required:
        -FieldRect
      properties:
        FieldRect: # Coordinates of the text field in the normalized image of the document. Only for Result.VISUAL_TEXT and Result.MRZ_TEXT results.
          $ref: "./common.yml#/components/schemas/RectangleCoordinates"
