openapi: 3.0.3
components:
  schemas:

    ContainerType:
      type: integer
      description: "Same as Result type, but used for safe parsing of not-described values. See Result type."
      default: 0

    Result:
      type: integer
      description: "Describes possible extracted result types from documents"
      enum:
        - 1
        - 30
        - 33
        - 36
        - 37
        - 3
        - 17
        - 18
        - 102
        - 15
        - 6
        - 19
        - 103
        - 8
        - 9
        - 20
        - 85
        - 50
        - 49
      x-enum-descriptions:
        - 'Contains cropped and rotated with perspective compensation image of document.
        Single input image can contain multiple document side/pages, which will be returned as separated results.
         Most of coordinates in other types defined on that image'
        - 'Contains image quality check results'
        - 'Contains check statuses with details, grouped by source'
        - 'Contains document textual fields from all sources (mrz, rfid, visual, barcode) with validity and cross-source compare checks'
        - 'Contains images from all document sources (mrz, rfid, visual, barcode)'
        - 'Contains MRZ OCR results'
        - 'Contains Visual zone OCR results'
        - 'Contains barcode parsing result with text fields'
        - 'Contains RFID parsing result with text fields'
        - "Contains lexical data analysis results that allow you to compare MRZ OCR results,
           Visual zone OCR results, barcodes and RFID chip data for an additional
           assessment of the authenticity of the document (this is an old format, better use TEXT type)"
        - 'Contains cropped graphic fields from Visual zone'
        - 'Contains barcode parsing result with graphic fields'
        - 'Contains RFID parsing result with graphic fields'
        - 'Contains list of document type candidates with their probabilities and descriptions'
        - 'Contains description of determined document type, if any'
        - 'Contains result of document authenticity checks'
        - 'Contains information about document position on the input image, its center, angle, etc'
        - 'Contains license'
        - 'Contains encrypted ResultContainerList'
      x-enum-varnames:
        - DOCUMENT_IMAGE
        - IMAGE_QUALITY
        - STATUS
        - TEXT
        - IMAGES
        - MRZ_TEXT
        - VISUAL_TEXT
        - BARCODE_TEXT
        - RFID_TEXT
        - LEXICAL_ANALYSIS
        - VISUAL_GRAPHICS
        - BARCODE_GRAPHICS
        - RFID_GRAPHICS
        - DOCUMENT_TYPE_CANDIDATES
        - DOCUMENT_TYPE
        - AUTHENTICITY
        - DOCUMENT_POSITION
        - LICENSE
        - ENCRYPTED_RCL


    ResultItem:
      type: object
      description: "Common fields for all result objects"
      required:
        - result_type
      properties:
        buf_length:
          type: integer
        light:
          type: integer
        list_idx:
          type: integer
        page_idx:
          type: integer
        result_type:
          $ref: "#/components/schemas/ContainerType"
      discriminator:
        propertyName: result_type
        mapping:
          1: "DocumentImageResult"
          3: "TextDataResult"
          6: "GraphicsResult"
          8: "DocumentTypesCandidatesResult"
          9: "ChosenDocumentTypeResult"
          20: "AuthenticityResult"
          15: "LexicalAnalysisResult"
          17: "TextDataResult"
          18: "TextDataResult"
          19: "GraphicsResult"
          30: "ImageQualityResult"
          33: "StatusResult"
          36: "TextResult"
          37: "ImagesResult"
          85: "DocumentPositionResult"
          102: "TextDataResult"
          103: "GraphicsResult"
          50: "License"
          49: "EncryptedRCL"

    ContainerList:
      type: object
      description: "List with various objects, containing processing results"
      required:
        - List
      properties:
        List:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/StatusResult"
              - $ref: "#/components/schemas/TextResult"
              - $ref: "#/components/schemas/DocumentImageResult"
              - $ref: "#/components/schemas/ImagesResult"
              - $ref: "#/components/schemas/ChosenDocumentTypeResult"
              - $ref: "#/components/schemas/DocumentTypesCandidatesResult"
              - $ref: "#/components/schemas/TextDataResult"
              - $ref: "#/components/schemas/GraphicsResult"
              - $ref: "#/components/schemas/LexicalAnalysisResult"
              - $ref: "#/components/schemas/AuthenticityResult"
              - $ref: "#/components/schemas/ImageQualityResult"
              - $ref: "#/components/schemas/DocumentPositionResult"

    DocumentPositionResult:
      $ref: "./rt-document-position.yml#/components/schemas/DocumentPositionResult"

    DocumentImageResult:
      $ref: "./rt-raw-image.yml#/components/schemas/DocumentImageResult"

    StatusResult:
      $ref: "./rt-status.yml#/components/schemas/StatusResult"

    T1`tResult:
      $ref: "./rt-text.yml#/components/schemas/TextResult"

    ImagesResult:
      $ref: "./rt-images.yml#/components/schemas/ImagesResult"

    LexicalAnalysisResult:
      $ref: "./rt-ocr-lexical-analisis.yml#/components/schemas/LexicalAnalysisResult"

    TextDataResult:
      $ref: "./rt-text-data.yml#/components/schemas/TextDataResult"

    GraphicsResult:
      $ref: "./rt-image-data.yml#/components/schemas/GraphicsResult"

    DocumentTypesCandidatesResult:
      $ref: "./rt-doc-type-old.yml#/components/schemas/DocumentTypesCandidatesResult"
    ChosenDocumentTypeResult:
      $ref: "./rt-doc-type-old.yml#/components/schemas/ChosenDocumentTypeResult"

    AuthenticityResult:
      $ref: "./rt-authenticity.yml#/components/schemas/AuthenticityResult"

    ImageQualityResult:
      $ref: "./rt-image-quality.yml#/components/schemas/ImageQualityResult"
