openapi: 3.1.1
components:
  schemas:
    ContainerType:
      title: "ContainerType"
      type: integer
      description: "Same as Result type, but used for safe parsing of not-described values. See Result type."
      default: 0

    Result:
      title: "Result"
      type: integer
      enum:
        - 1
        - 3
        - 5
        - 6
        - 8
        - 9
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 26
        - 30
        - 32
        - 33
        - 34
        - 35
        - 36
        - 37
        - 38
        - 39
        - 49
        - 50
        - 61
        - 62
        - 85
        - 101
        - 102
        - 103
        - 104
        - 105
        - 109
      x-enum-descriptions:
        - "Contains cropped and rotated with perspective compensation image of document. Single input image can contain multiple document side/pages, which will be returned as separated results. Most of coordinates in other types defined on that image"
        - "Contains MRZ OCR results"
        - "Contains raw information about barcodes on the input image"
        - "Contains cropped graphic fields from Visual zone"
        - "Contains list of document type candidates with their probabilities and descriptions"
        - "Contains description of determined document type, if any"
        - "Contains lexical data analysis results that allow you to compare MRZ OCR results, Visual zone OCR results, barcodes and RFID chip data for an additional assessment of the authenticity of the document (this is an old format, better use TEXT type)"
        - "Contains raw uncropped images"
        - "Contains Visual zone OCR results"
        - "Contains barcode parsing result with text fields"
        - "Contains barcode parsing result with graphic fields"
        - "Contains result of document authenticity checks"
        - "Contains result of DocVisualExtendedInfoContainer"
        - "Contains image quality check results"
        - "Contains result of DocGraphicsInfoContainer"
        - "Contains check statuses with details, grouped by source"
        - "Contains result of portraits comparison"
        - "Contains result of DocGraphicsInfoContainer"
        - "Contains document textual fields from all sources (mrz, rfid, visual, barcode) with validity and cross-source compare checks"
        - "Contains images from all document sources (mrz, rfid, visual, barcode)"
        - "Contains result of DocGraphicsInfoContainer"
        - "Contains result of fingerprints comparison"
        - "Contains encrypted ResultContainerList"
        - "Contains license"
        - "Contains result of DocumentPosition"
        - "Contains result of DocumentPosition"
        - "Contains information about document position on the input image, its center, angle, etc"
        - "Contains RFID raw data"
        - "Contains RFID text results"
        - "Contains RFID graphic results"
        - "Contains RFID binary data"
        - "Contains RFID original graphics data"
        - "Digital Travel Credential data"
      x-enum-varnames:
        - "DOCUMENT_IMAGE"
        - "MRZ_TEXT"
        - "BARCODES"
        - "VISUAL_GRAPHICS"
        - "DOCUMENT_TYPE_CANDIDATES"
        - "DOCUMENT_TYPE"
        - "LEXICAL_ANALYSIS"
        - "RAW_UNCROPPED_IMAGE"
        - "VISUAL_TEXT"
        - "BARCODE_TEXT"
        - "BARCODE_GRAPHICS"
        - "AUTHENTICITY"
        - "MAGNETIC_STRIPE_TEXT_DATA"
        - "IMAGE_QUALITY"
        - "LIVE_PORTRAIT"
        - "STATUS"
        - "PORTRAIT_COMPARISON"
        - "EXT_PORTRAIT"
        - "TEXT"
        - "IMAGES"
        - "FINGERPRINTS"
        - "FINGERPRINT_COMPARISON"
        - "ENCRYPTED_RCL"
        - "LICENSE"
        - "MRZ_POSITION"
        - "BARCODE_POSITION"
        - "DOCUMENT_POSITION"
        - "RFID_RAW_DATA"
        - "RFID_TEXT"
        - "RFID_GRAPHICS"
        - "RFID_BINARY_DATA"
        - "RFID_ORIGINAL_GRAPHICS"
        - "DTC_VC"

    ResultItem:
      title: "ResultItem"
      type: object
      description: "Common fields for all result objects"
      required:
        - result_type
      properties:
        buf_length:
          type: integer
        light:
          type: integer
        list_idx:
          type: integer
        page_idx:
          type: integer
        result_type:
          $ref: "#/components/schemas/ContainerType"

    ContainerList:
      title: "ContainerList"
      type: object
      description: "List with various objects, containing processing results"
      required:
        - Count
        - List
      properties:
        Count:
          type: integer
          description: "Length of list (Count for items)"
        List:
          type: array
          items:
            oneOf:
              - $ref: "./rt-status.yml#/components/schemas/StatusResult"
              - $ref: "./rt-text.yml#/components/schemas/TextResult"
              - $ref: "./rt-raw-image.yml#/components/schemas/DocumentImageResult"
              - $ref: "./rt-images.yml#/components/schemas/ImagesResult"
              - $ref: "./rt-doc-type-old.yml#/components/schemas/ChosenDocumentTypeResult"
              - $ref: "./rt-doc-type-old.yml#/components/schemas/DocumentTypesCandidatesResult"
              - $ref: "./rt-text-data.yml#/components/schemas/TextDataResult"
              - $ref: "./rt-image-data.yml#/components/schemas/GraphicsResult"
              - $ref: "./rt-ocr-lexical-analysis.yml#/components/schemas/LexicalAnalysisResult"
              - $ref: "./rt-authenticity.yml#/components/schemas/AuthenticityResult"
              - $ref: "./rt-image-quality.yml#/components/schemas/ImageQualityResult"
              - $ref: "./rt-document-position.yml#/components/schemas/DocumentPositionResult"
              - $ref: "./rt-barcodes.yml#/components/schemas/DocBarCodeInfo"
              - $ref: "./rt-license.yml#/components/schemas/LicenseResult"
              - $ref: "./rt-encrypted-rcl.yml#/components/schemas/EncryptedRCLResult"
              - $ref: "./rt-rfid-binary-data.yml#/components/schemas/DocumentBinaryInfoResult"
              - $ref: "./rt-byte-array-data.yml#/components/schemas/ByteArrayResult"
