openapi: 3.0.3
components:
  schemas:

    Result:
      type: integer
      description: "Describes possible extracted data types from documents"
      enum:
        - 1
        - 33
        - 36
        - 3
        - 17
        - 18
        - 102
        - 15
        - 6
        - 19
        - 103
        - 8
        - 9
      x-enum-descriptions:
        - 'Contains cropped and rotated image of document. Most of coordinates in other types defined on that image'
        - 'Contains check statuses with details, grouped by source'
        - 'Contains document textual fields from all sources (mrz, rfid, visual, barcode) with validity and cross-source compare checks'
        - 'Contains MRZ OCR results'
        - 'Contains Visual zone OCR results'
        - 'Contains barcode parsing result with text fields'
        - 'Contains RFID parsing result with text fields'
        - "Contains lexical data analysis results that allow you to compare MRZ OCR results,
           Visual zone OCR results, barcodes and RFID chip data for an additional
           assessment of the authenticity of the document (this is an old format, better use TEXT type)"
        - 'Contains cropped graphic fields from Visual zone'
        - 'Contains barcode parsing result with graphic fields'
        - 'Contains RFID parsing result with graphic fields'
        - 'Contains list of document type candidates with their probabilities and descriptions'
        - 'Contains description of determined document type, if any'
      x-enum-varnames:
        - RAW_IMAGE
        - STATUS
        - TEXT
        - MRZ_TEXT
        - VISUAL_TEXT
        - BARCODE_TEXT
        - RFID_TEXT
        - LEXICAL_ANALYSIS
        - VISUAL_GRAPHICS
        - BARCODE_GRAPHICS
        - RFID_GRAPHICS
        - DOCUMENT_TYPE_CANDIDATES
        - DOCUMENT_TYPE

    ResultItem:
      type: object
      description: "Common fields for all result objects"
      required:
        - result_type
      properties:
        buf_length:
          type: integer
        light:
          type: integer
        list_idx:
          type: integer
        page_idx:
          type: integer
        result_type:
          type: integer
      discriminator:
        propertyName: result_type
        mapping:
          1: "RawImageResult"
          3: "TextDataResult"
          6: "GraphicsResult"
          8: "DocumentTypesCandidatesResult"
          9: "ChosenDocumentTypeResult"
          15: "LexicalAnalysisResult"
          17: "TextDataResult"
          18: "TextDataResult"
          19: "GraphicsResult"
          33: "StatusResult"
          36: "TextResult"
          102: "TextDataResult"
          103: "GraphicsResult"

    ContainerList:
      type: object
      description: "list with result objects"
      required:
        - List
      properties:
        List:
          type: array
          items:
            anyOf:
              - $ref: "#/components/schemas/RawImageResult"
              - $ref: "#/components/schemas/TextResult"
              - $ref: "#/components/schemas/StatusResult"
              - $ref: "#/components/schemas/TextDataResult"
              - $ref: "#/components/schemas/GraphicsResult"
              - $ref: "#/components/schemas/LexicalAnalysisResult"
              - $ref: "#/components/schemas/ChosenDocumentTypeResult"
              - $ref: "#/components/schemas/DocumentTypesCandidatesResult"

    RawImageResult:
      $ref: "./rt-raw-image.yml#/components/schemas/RawImageResult"

    StatusResult:
      $ref: "./rt-status.yml#/components/schemas/StatusResult"

    TextResult:
      $ref: "./rt-text.yml#/components/schemas/TextResult"

    LexicalAnalysisResult:
      $ref: "./rt-ocr-lexical-analisis.yml#/components/schemas/LexicalAnalysisResult"

    TextDataResult:
      $ref: "./rt-text-data.yml#/components/schemas/TextDataResult"

    GraphicsResult:
      $ref: "./rt-image-data.yml#/components/schemas/GraphicsResult"

    DocumentTypesCandidatesResult:
      $ref: "./rt-doc-type-old.yml#/components/schemas/DocumentTypesCandidatesResult"

    ChosenDocumentTypeResult:
      $ref: "./rt-doc-type-old.yml#/components/schemas/ChosenDocumentTypeResult"
