openapi: 3.0.4
components:
  schemas:
    ContainerType:
      title: "ContainerType"
      type: integer
      description: "Same as Result type, but used for safe parsing of not-described values. See Result type."
      default: 0

    Result:
      title: "Result"
      type: integer
      enum:
        - 1
        - 3
        - 5
        - 6
        - 7
        - 8
        - 9
        - 15
        - 16
        - 17
        - 18
        - 19
        - 20
        - 26
        - 30
        - 32
        - 33
        - 34
        - 35
        - 36
        - 37
        - 38
        - 39
        - 49
        - 50
        - 61
        - 62
        - 85
        - 87
        - 97
        - 101
        - 102
        - 103
        - 104
        - 105
        - 109
        - 120
        - 121
        - 122
        - 123
        - 124
        - 125
      x-enum-descriptions:
        - "Contains cropped and rotated with perspective compensation image of document. Single input image can contain multiple document side/pages, which will be returned as separated results. Most of coordinates in other types defined on that image"
        - "Contains MRZ OCR results"
        - "Contains raw information about barcodes on the input image"
        - "Contains cropped graphic fields from Visual zone"
        - "Contains result of MRZTestQuality"
        - "Contains list of document type candidates with their probabilities and descriptions"
        - "Contains description of determined document type, if any"
        - "Contains lexical data analysis results that allow you to compare MRZ OCR results, Visual zone OCR results, barcodes and RFID chip data for an additional assessment of the authenticity of the document (this is an old format, better use TEXT type)"
        - "Contains raw uncropped images"
        - "Contains Visual zone OCR results"
        - "Contains barcode parsing result with text fields"
        - "Contains barcode parsing result with graphic fields"
        - "Contains result of document authenticity checks"
        - "Contains result of DocVisualExtendedInfoContainer"
        - "Contains image quality check results"
        - "Contains result of DocGraphicsInfoContainer"
        - "Contains check statuses with details, grouped by source"
        - "Contains result of portraits comparison"
        - "Contains result of DocGraphicsInfoContainer"
        - "Contains document textual fields from all sources (mrz, rfid, visual, barcode) with validity and cross-source compare checks"
        - "Contains images from all document sources (mrz, rfid, visual, barcode)"
        - "Contains result of DocGraphicsInfoContainer"
        - "Contains result of fingerprints comparison"
        - "Contains encrypted ResultContainerList"
        - "Contains license"
        - "Contains result of MRZ position"
        - "Contains result of barcode position"
        - "Contains information about document position on the input image, its center, angle, etc"
        - "Contains result of MRZDetectorResult"
        - "Contains result of FaceDetection"
        - "Contains RFID raw data"
        - "Contains RFID text results"
        - "Contains RFID graphic results"
        - "Contains RFID binary data"
        - "Contains RFID original graphics data"
        - "Digital Travel Credential data"
        - "Contains mDL device raw response"
        - "Contains mDL device parsed response"
        - "Contains mDL server raw response"
        - "Contains mDL server parsed response"
        - "Contains result of VDS NC"
        - "Contains result of VDS"
      x-enum-varnames:
        - "DOCUMENT_IMAGE"
        - "MRZ_TEXT"
        - "BARCODES"
        - "VISUAL_GRAPHICS"
        - "MRZ_TEST_QUALITY"
        - "DOCUMENT_TYPE_CANDIDATES"
        - "DOCUMENT_TYPE"
        - "LEXICAL_ANALYSIS"
        - "RAW_UNCROPPED_IMAGE"
        - "VISUAL_TEXT"
        - "BARCODE_TEXT"
        - "BARCODE_GRAPHICS"
        - "AUTHENTICITY"
        - "MAGNETIC_STRIPE_TEXT_DATA"
        - "IMAGE_QUALITY"
        - "LIVE_PORTRAIT"
        - "STATUS"
        - "PORTRAIT_COMPARISON"
        - "EXT_PORTRAIT"
        - "TEXT"
        - "IMAGES"
        - "FINGERPRINTS"
        - "FINGERPRINT_COMPARISON"
        - "ENCRYPTED_RCL"
        - "LICENSE"
        - "MRZ_POSITION"
        - "BARCODE_POSITION"
        - "DOCUMENT_POSITION"
        - "MRZ_DETECTOR"
        - "FACE_DETECTION"
        - "RFID_RAW_DATA"
        - "RFID_TEXT"
        - "RFID_GRAPHICS"
        - "RFID_BINARY_DATA"
        - "RFID_ORIGINAL_GRAPHICS"
        - "DTC_VC"
        - "MDL_DEVICE_RAW_RESPONSE"
        - "MDL_DEVICE_PARSED_RESPONSE"
        - "MDL_SERVER_RAW_RESPONSE"
        - "MDL_SERVER_PARSED_RESPONSE"
        - "VDS_NC"
        - "VDS"

    ResultItem:
      title: "ResultItem"
      type: object
      description: "Common fields for all result objects"
      required:
        - result_type
      properties:
        buf_length:
          type: integer
        light:
          type: integer
        list_idx:
          type: integer
        page_idx:
          type: integer
        result_type:
          $ref: "#/components/schemas/Result"
      discriminator:
        propertyName: result_type
        mapping:
          1: "DocumentImageResult"
          3: "TextDataResult"
          5: "DocBarCodeInfo"
          6: "GraphicsResult"
          7: "MRZTestQualityResult"
          8: "DocumentTypesCandidatesResult"
          9: "ChosenDocumentTypeResult"
          15: "LexicalAnalysisResult"
          16: "DocumentImageResult"
          17: "TextDataResult"
          18: "TextDataResult"
          19: "GraphicsResult"
          20: "AuthenticityResult"
          26: "TextDataResult"
          30: "ImageQualityResult"
          32: "GraphicsResult"
          33: "StatusResult"
          34: "AuthenticityResult"
          35: "GraphicsResult"
          36: "TextResult"
          37: "ImagesResult"
          38: "GraphicsResult"
          39: "AuthenticityResult"
          49: "EncryptedRCLResult"
          50: "LicenseResult"
          61: "MRZPositionResult"
          62: "BarcodePositionResult"
          85: "DocumentPositionResult"
          87: "MRZDetectorResult"
          97: "FaceDetectionResult"
          101: "DocumentBinaryInfoResult"
          102: "RFIDTextDataResult"
          103: "GraphicsResult"
          104: "DocumentBinaryInfoResult"
          105: "RFIDGraphicsInfoResult"
          109: "ByteArrayResult"

    ContainerList:
      title: "ContainerList"
      type: object
      description: "List with various objects, containing processing results"
      required:
        - List
      properties:
        Count:
          type: integer
          description: "Length of list (Count for items)"
        List:
          type: array
          items:
            oneOf:
              - $ref: "#/components/schemas/StatusResult"
              - $ref: "#/components/schemas/TextResult"
              - $ref: "#/components/schemas/DocumentImageResult"
              - $ref: "#/components/schemas/ImagesResult"
              - $ref: "#/components/schemas/ChosenDocumentTypeResult"
              - $ref: "#/components/schemas/DocumentTypesCandidatesResult"
              - $ref: "#/components/schemas/TextDataResult"
              - $ref: "#/components/schemas/GraphicsResult"
              - $ref: "#/components/schemas/LexicalAnalysisResult"
              - $ref: "#/components/schemas/AuthenticityResult"
              - $ref: "#/components/schemas/ImageQualityResult"
              - $ref: "#/components/schemas/BarcodePositionResult"
              - $ref: "#/components/schemas/DocumentPositionResult"
              - $ref: "#/components/schemas/DocBarCodeInfo"
              - $ref: "#/components/schemas/LicenseResult"
              - $ref: "#/components/schemas/EncryptedRCLResult"
              - $ref: "#/components/schemas/DocumentBinaryInfoResult"
              - $ref: "#/components/schemas/ByteArrayResult"
              - $ref: "#/components/schemas/FaceDetectionResult"
              - $ref: "#/components/schemas/MRZDetectorResult"
              - $ref: "#/components/schemas/MRZPositionResult"
              - $ref: "#/components/schemas/MRZTestQualityResult"
              - $ref: "#/components/schemas/RFIDGraphicsInfoResult"
              - $ref: "#/components/schemas/RFIDTextDataResult"

    StatusResult:
      title: "StatusResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-status.yml#/components/schemas/StatusItem"

    TextResult:
      title: "TextResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-text.yml#/components/schemas/TextItem"

    DocumentImageResult:
      title: "DocumentImageResult"
      description: "Contains document image."
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-raw-image.yml#/components/schemas/RawImageContainerItem"

    ImagesResult:
      title: "ImagesResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-images.yml#/components/schemas/ImagesItem"

    ChosenDocumentTypeResult:
      title: "ChosenDocumentTypeResult"
      description: "Contains information about the type of document that was determined
      based on the analysis of the provided image"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-doc-type-old.yml#/components/schemas/OneCandidateItem"

    DocumentTypesCandidatesResult:
      title: "DocumentTypesCandidatesResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-doc-type-old.yml#/components/schemas/CandidatesListItem"

    TextDataResult:
      title: "TextDataResult"
      description: "Text fields extracted from one document source.
      Contains results of specific source for each provided page."
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-text-data.yml#/components/schemas/DocVisualExtendedInfoItem"

    GraphicsResult:
      title: "GraphicsResult"
      description: "Graphic fields extracted from one of the document sources.
      Returns separate results for each provided page."
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-image-data.yml#/components/schemas/DocGraphicsInfoItem"

    ByteArrayResult:
      title: "ByteArrayResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-byte-array-data.yml#/components/schemas/ByteArrayItem"

    LexicalAnalysisResult:
      title: "LexicalAnalysisResult"
      description: |
        Lexical data analysis allows you to compare the results of reading the text data of the MRZ,
        the document filling area, barcodes and data from the memory of the RFID chip for an additional
        assessment of the authenticity of the document. Single result for all pages.
        Consider using Result.TEXT type for more simplicity.
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-ocr-lexical-analysis.yml#/components/schemas/ListVerifiedFieldsItem"

    AuthenticityResult:
      title: "AuthenticityResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-authenticity.yml#/components/schemas/AuthenticityCheckListItem"

    ImageQualityResult:
      title: "ImageQualityResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-image-quality.yml#/components/schemas/ImageQualityCheckListItem"

    BarcodePositionResult:
      title: "BarcodePositionResult"
      description: "Contains information about barcode position on the input image, its center, angle, etc"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-barcode-position.yml#/components/schemas/BarcodePositionItem"

    DocumentPositionResult:
      title: "DocumentPositionResult"
      description: "Contains information about document position on the input image, its center, angle, etc"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-document-position.yml#/components/schemas/DocumentPositionItem"

    DocBarCodeInfo:
      title: "DocBarCodeInfo"
      description: "Raw data from BarCodes"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-barcodes.yml#/components/schemas/DocBarCodeInfoItem"

    LicenseResult:
      title: "LicenseResult"
      description: "Contains license"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-license.yml#/components/schemas/LicenseItem"

    EncryptedRCLResult:
      title: "EncryptedRCLResult"
      description: "Contains encrypted result container list"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-encrypted-rcl.yml#/components/schemas/EncryptedRCLItem"

    DocumentBinaryInfoResult:
      title: "DocumentBinaryInfoResult"
      description: "Structure is used to store the data reading results from the RFID-chip in
      a form of a list of the logically separated data groups."
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-rfid-binary-data.yml#/components/schemas/TDocBinaryInfoItem"

    FaceDetectionResult:
      title: "FaceDetectionResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-face-detection.yml#/components/schemas/FaceDetectionItem"

    MRZDetectorResult:
      title: "MRZDetectorResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-mrz-detector.yml#/components/schemas/ResultMRZDetectorItem"

    MRZPositionResult:
      title: "MRZPositionResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-mrz-position.yml#/components/schemas/MrzPositionItem"

    MRZTestQualityResult:
      title: "MRZTestQualityResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-mrz-test-quality.yml#/components/schemas/MRZTestQualityItem"

    RFIDGraphicsInfoResult:
      title: "RFIDGraphicsInfoResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-rfid-graphics-info.yml#/components/schemas/TOriginalRFIDGraphicsInfoItem"

    RFIDTextDataResult:
      title: "RFIDTextDataResult"
      allOf:
        - $ref: "#/components/schemas/ResultItem"
        - $ref: "./rt-rfid-text-data.yml#/components/schemas/RFIDDocVisualExtendedInfoItem"
