openapi: 3.0.3
components:
  schemas:
    CheckDiagnose:
      type: integer
      description: "Enumeration contains identifiers which determinate the single document element authenticity check outcome reason: https://docs.regulaforensics.com/develop/doc-reader-sdk/web-service/development/enums/check-diagnose/"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 7
        - 8
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 33
        - 34
        - 40
        - 41
        - 42
        - 43
        - 44
        - 50
        - 51
        - 52
        - 53
        - 54
        - 55
        - 60
        - 65
        - 80
        - 81
        - 82
        - 83
        - 84
        - 85
        - 90
        - 91
        - 92
        - 93
        - 94
        - 95
        - 96
        - 100
        - 101
        - 102
        - 103
        - 104
        - 110
        - 111
        - 112
        - 113
        - 114
        - 115
        - 116
        - 117
        - 118
        - 119
        - 120
        - 121
        - 122
        - 130
        - 131
        - 132
        - 133
        - 140
        - 141
        - 142
        - 143
        - 144
        - 150
        - 151
        - 152
        - 153
        - 154
        - 155
        - 156
        - 160
        - 161
        - 170
        - 180
        - 181
        - 182
        - 183
        - 184
        - 185
        - 186
        - 187
        - 190
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 220
        - 221
        - 222
        - 230
        - 240
        - 241
        - 250
      x-enum-varnames:
        - "UNKNOWN"
        - "PASS"
        - "INVALID_INPUT_DATA"
        - "INTERNAL_ERROR"
        - "EXCEPTION_IN_MODULE"
        - "UNCERTAIN_VERIFICATION"
        - "NECESSARY_IMAGE_NOT_FOUND"
        - "PHOTO_SIDES_NOT_FOUND"
        - "INVALID_CHECKSUM"
        - "SYNTAX_ERROR"
        - "LOGIC_ERROR"
        - "SOURCES_COMPARISON_ERROR"
        - "FIELDS_COMPARISON_LOGIC_ERROR"
        - "INVALID_FIELD_FORMAT"
        - "TRUE_LUMINESCENCE_ERROR"
        - "FALSE_LUMINESCENCE_ERROR"
        - "FIXED_PATTERN_ERROR"
        - "LOW_CONTRAST_IN_IR_LIGHT"
        - "INCORRECT_BACKGROUND_LIGHT"
        - "BACKGROUND_COMPARISON_ERROR"
        - "INCORRECT_TEXT_COLOR"
        - "PHOTO_FALSE_LUMINESCENCE"
        - "TOO_MUCH_SHIFT"
        - "CONTACT_CHIP_TYPE_MISMATCH"
        - "FIBERS_NOT_FOUND"
        - "TOO_MANY_OBJECTS"
        - "SPECKS_IN_UV"
        - "TOO_LOW_RESOLUTION"
        - "INVISIBLE_ELEMENT_PRESENT"
        - "VISIBLE_ELEMENT_ABSENT"
        - "ELEMENT_SHOULD_BE_COLORED"
        - "ELEMENT_SHOULD_BE_GRAYSCALE"
        - "PHOTO_WHITE_IR_DONT_MATCH"
        - "UV_DULL_PAPER_MRZ"
        - "FALSE_LUMINESCENCE_IN_MRZ"
        - "UV_DULL_PAPER_PHOTO"
        - "UV_DULL_PAPER_BLANK"
        - "UV_DULL_PAPER_ERROR"
        - "FALSE_LUMINESCENCE_IN_BLANK"
        - "BAD_AREA_IN_AXIAL"
        - "FALSE_IP_PARAMETERS"
        - "FIELD_POS_CORRECTOR_HIGHLIGHT_IR"
        - "FIELD_POS_CORRECTOR_GLARES_IN_PHOTO_AREA"
        - "FIELD_POS_CORRECTOR_PHOTO_REPLACED"
        - "FIELD_POS_CORRECTOR_LANDMARKS_CHECK_ERROR"
        - "FIELD_POS_CORRECTOR_FACE_PRESENCE_CHECK_ERROR"
        - "FIELD_POS_CORRECTOR_FACE_ABSENCE_CHECK_ERROR"
        - "OVI_IR_INVISIBLE"
        - "OVI_INSUFFICIENT_AREA"
        - "OVI_COLOR_INVARIABLE"
        - "OVI_BAD_COLOR_FRONT"
        - "OVI_BAD_COLOR_SIDE"
        - "OVI_WIDE_COLOR_SPREAD"
        - "OVI_BAD_COLOR_PERCENT"
        - "HOLOGRAM_ELEMENT_ABSENT"
        - "HOLOGRAM_SIDE_TOP_IMAGES_ABSENT"
        - "HOLOGRAM_ELEMENT_PRESENT"
        - "HOLOGRAM_FRAMES_IS_ABSENT"
        - "HOLOGRAM_HOLO_FIELD_IS_ABSENT"
        - "PHOTO_PATTERN_INTERRUPTED"
        - "PHOTO_PATTERN_SHIFTED"
        - "PHOTO_PATTERN_DIFFERENT_COLORS"
        - "PHOTO_PATTERN_IR_VISIBLE"
        - "PHOTO_PATTERN_NOT_INTERSECT"
        - "PHOTO_SIZE_IS_WRONG"
        - "PHOTO_PATTERN_INVALID_COLOR"
        - "PHOTO_PATTERN_SHIFTED_VERT"
        - "PHOTO_PATTERN_PATTERN_NOT_FOUND"
        - "PHOTO_PATTERN_DIFFERENT_LINES_THICKNESS"
        - "PHOTO_IS_NOT_RECTANGLE"
        - "PHOTO_CORNERS_IS_WRONG"
        - "DOCUMENT_IS_CANCELLING"
        - "TEXT_COLOR_SHOULD_BE_BLUE"
        - "TEXT_COLOR_SHOULD_BE_GREEN"
        - "TEXT_COLOR_SHOULD_BE_RED"
        - "TEXT_SHOULD_BE_BLACK"
        - "BARCODE_WAS_READ_WITH_ERRORS"
        - "BARCODE_DATA_FORMAT_ERROR"
        - "BARCODE_SIZE_PARAMS_ERROR"
        - "NOT_ALL_BARCODES_READ"
        - "GLARES_IN_BARCODE_AREA"
        - "PORTRAIT_COMPARISON_PORTRAITS_DIFFER"
        - "PORTRAIT_COMPARISON_NO_SERVICE_REPLY"
        - "PORTRAIT_COMPARISON_SERVICE_ERROR"
        - "PORTRAIT_COMPARISON_NOT_ENOUGH_IMAGES"
        - "PORTRAIT_COMPARISON_NO_LIVE_PHOTO"
        - "PORTRAIT_COMPARISON_NO_SERVICE_LICENSE"
        - "PORTRAIT_COMPARISON_NO_PORTRAIT_DETECTED"
        - "MOBILE_IMAGES_UNSUITABLE_LIGHT_CONDITIONS"
        - "MOBILE_IMAGES_WHITE_UV_NO_DIFFERENCE"
        - "FINGERPRINTS_COMPARISON_MISMATCH"
        - "HOLO_PHOTO_FACE_NOT_DETECTED"
        - "HOLO_PHOTO_FACE_COMPARISON_FAILED"
        - "HOLO_PHOTO_GLARE_IN_CENTER_ABSENT"
        - "HOLO_PHOTO_HOLO_ELEMENT_SHAPE_ERROR"
        - "HOLO_PHOTO_ALGORITHMS_STEPS_ERROR"
        - "HOLO_PHOTO_HOLO_AREAS_NOT_LOADED"
        - "HOLO_PHOTO_FINISHED_BY_TIMEOUT"
        - "HOLO_PHOTO_DOCUMENT_OUTSIDE_FRAME"
        - "LIVENESS_DEPTH_CHECK_FAILED"
        - "MRZ_QUALITY_WRONG_SYMBOL_POSITION"
        - "MRZ_QUALITY_WRONG_BACKGROUND"
        - "MRZ_QUALITY_WRONG_MRZ_WIDTH"
        - "MRZ_QUALITY_WRONG_MRZ_HEIGHT"
        - "MRZ_QUALITY_WRONG_LINE_POSITION"
        - "MRZ_QUALITY_WRONG_FONT_TYPE"
        - "OCR_QUALITY_TEXT_POSITION"
        - "OCR_QUALITY_INVALID_FONT"
        - "OCR_QUALITY_INVALID_BACKGROUND"
        - "LASINK_INVALID_LINES_FREQUENCY"
        - "DOC_LIVENESS_ELECTRONIC_DEVICE_DETECTED"
        - "DOC_LIVENESS_INVALID_BARCODE_BACKGROUND"
        - "LAST_DIAGNOSE_VALUE"
