openapi: 3.0.4
components:
  schemas:
    CheckDiagnose:
      title: "CheckDiagnose"
      type: integer
      description: "Enumeration contains identifiers which determinate the single document element authenticity check outcome reason: https://docs.regulaforensics.com/develop/doc-reader-sdk/web-service/development/enums/check-diagnose/"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 7
        - 8
        - 10
        - 11
        - 12
        - 13
        - 14
        - 15
        - 20
        - 21
        - 22
        - 23
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
        - 30
        - 31
        - 33
        - 34
        - 40
        - 41
        - 42
        - 43
        - 44
        - 50
        - 51
        - 52
        - 53
        - 54
        - 55
        - 60
        - 65
        - 66
        - 67
        - 80
        - 81
        - 82
        - 83
        - 84
        - 85
        - 86
        - 87
        - 88
        - 90
        - 91
        - 92
        - 93
        - 94
        - 95
        - 96
        - 100
        - 101
        - 102
        - 103
        - 104
        - 110
        - 111
        - 112
        - 113
        - 114
        - 115
        - 116
        - 117
        - 118
        - 119
        - 120
        - 121
        - 122
        - 130
        - 131
        - 132
        - 133
        - 134
        - 140
        - 141
        - 142
        - 143
        - 144
        - 145
        - 150
        - 151
        - 152
        - 153
        - 154
        - 155
        - 156
        - 160
        - 161
        - 170
        - 180
        - 181
        - 182
        - 183
        - 184
        - 185
        - 186
        - 187
        - 190
        - 200
        - 201
        - 202
        - 203
        - 204
        - 205
        - 220
        - 221
        - 222
        - 230
        - 238
        - 239
        - 240
        - 241
        - 242
        - 243
        - 244
        - 245
        - 246
        - 247
        - 248
        - 250
        - 260
        - 261
        - 262
      x-enum-varnames:
        - "UNKNOWN"
        - "PASS"
        - "INVALID_INPUT_DATA"
        - "INTERNAL_ERROR"
        - "EXCEPTION_IN_MODULE"
        - "UNCERTAIN_VERIFICATION"
        - "NECESSARY_IMAGE_NOT_FOUND"
        - "PHOTO_SIDES_NOT_FOUND"
        - "INVALID_CHECKSUM"
        - "SYNTAX_ERROR"
        - "LOGIC_ERROR"
        - "SOURCES_COMPARISON_ERROR"
        - "FIELDS_COMPARISON_LOGIC_ERROR"
        - "INVALID_FIELD_FORMAT"
        - "TRUE_LUMINESCENCE_ERROR"
        - "FALSE_LUMINESCENCE_ERROR"
        - "FIXED_PATTERN_ERROR"
        - "LOW_CONTRAST_IN_IR_LIGHT"
        - "INCORRECT_BACKGROUND_LIGHT"
        - "BACKGROUND_COMPARISON_ERROR"
        - "INCORRECT_TEXT_COLOR"
        - "PHOTO_FALSE_LUMINESCENCE"
        - "TOO_MUCH_SHIFT"
        - "CONTACT_CHIP_TYPE_MISMATCH"
        - "FIBERS_NOT_FOUND"
        - "TOO_MANY_OBJECTS"
        - "SPECKS_IN_UV"
        - "TOO_LOW_RESOLUTION"
        - "INVISIBLE_ELEMENT_PRESENT"
        - "VISIBLE_ELEMENT_ABSENT"
        - "ELEMENT_SHOULD_BE_COLORED"
        - "ELEMENT_SHOULD_BE_GRAYSCALE"
        - "PHOTO_WHITE_IR_DONT_MATCH"
        - "UV_DULL_PAPER_MRZ"
        - "FALSE_LUMINESCENCE_IN_MRZ"
        - "UV_DULL_PAPER_PHOTO"
        - "UV_DULL_PAPER_BLANK"
        - "UV_DULL_PAPER_ERROR"
        - "FALSE_LUMINESCENCE_IN_BLANK"
        - "BAD_AREA_IN_AXIAL"
        - "FALSE_IPI_PARAMETERS"
        - "ENCRYPTED_IPI_NOT_FOUND"
        - "ENCRYPTED_IPI_DATA_DONT_MATCH"
        - "FIELD_POS_CORRECTOR_HIGHLIGHT_IR"
        - "FIELD_POS_CORRECTOR_GLARES_IN_PHOTO_AREA"
        - "FIELD_POS_CORRECTOR_PHOTO_REPLACED"
        - "FIELD_POS_CORRECTOR_LANDMARKS_CHECK_ERROR"
        - "FIELD_POS_CORRECTOR_FACE_PRESENCE_CHECK_ERROR"
        - "FIELD_POS_CORRECTOR_FACE_ABSENCE_CHECK_ERROR"
        - "FIELD_POS_CORRECTOR_INCORRECT_HEAD_POSITION"
        - "FIELD_POS_CORRECTOR_AGE_CHECK_ERROR"
        - "FIELD_POS_CORRECTOR_SEX_CHECK_ERROR"
        - "OVI_IR_INVISIBLE"
        - "OVI_INSUFFICIENT_AREA"
        - "OVI_COLOR_INVARIABLE"
        - "OVI_BAD_COLOR_FRONT"
        - "OVI_BAD_COLOR_SIDE"
        - "OVI_WIDE_COLOR_SPREAD"
        - "OVI_BAD_COLOR_PERCENT"
        - "HOLOGRAM_ELEMENT_ABSENT"
        - "HOLOGRAM_SIDE_TOP_IMAGES_ABSENT"
        - "HOLOGRAM_ELEMENT_PRESENT"
        - "HOLOGRAM_FRAMES_IS_ABSENT"
        - "HOLOGRAM_HOLO_FIELD_IS_ABSENT"
        - "PHOTO_PATTERN_INTERRUPTED"
        - "PHOTO_PATTERN_SHIFTED"
        - "PHOTO_PATTERN_DIFFERENT_COLORS"
        - "PHOTO_PATTERN_IR_VISIBLE"
        - "PHOTO_PATTERN_NOT_INTERSECT"
        - "PHOTO_SIZE_IS_WRONG"
        - "PHOTO_PATTERN_INVALID_COLOR"
        - "PHOTO_PATTERN_SHIFTED_VERT"
        - "PHOTO_PATTERN_PATTERN_NOT_FOUND"
        - "PHOTO_PATTERN_DIFFERENT_LINES_THICKNESS"
        - "PHOTO_IS_NOT_RECTANGLE"
        - "PHOTO_CORNERS_IS_WRONG"
        - "DOCUMENT_IS_CANCELLING"
        - "TEXT_COLOR_SHOULD_BE_BLUE"
        - "TEXT_COLOR_SHOULD_BE_GREEN"
        - "TEXT_COLOR_SHOULD_BE_RED"
        - "TEXT_SHOULD_BE_BLACK"
        - "TEXT_IS_ABSENT"
        - "BARCODE_WAS_READ_WITH_ERRORS"
        - "BARCODE_DATA_FORMAT_ERROR"
        - "BARCODE_SIZE_PARAMS_ERROR"
        - "NOT_ALL_BARCODES_READ"
        - "GLARES_IN_BARCODE_AREA"
        - "NO_CERTIFICATE_FOR_DIGITAL_SIGNATURE_CHECK"
        - "PORTRAIT_COMPARISON_PORTRAITS_DIFFER"
        - "PORTRAIT_COMPARISON_NO_SERVICE_REPLY"
        - "PORTRAIT_COMPARISON_SERVICE_ERROR"
        - "PORTRAIT_COMPARISON_NOT_ENOUGH_IMAGES"
        - "PORTRAIT_COMPARISON_NO_LIVE_PHOTO"
        - "PORTRAIT_COMPARISON_NO_SERVICE_LICENSE"
        - "PORTRAIT_COMPARISON_NO_PORTRAIT_DETECTED"
        - "MOBILE_IMAGES_UNSUITABLE_LIGHT_CONDITIONS"
        - "MOBILE_IMAGES_WHITE_UV_NO_DIFFERENCE"
        - "FINGERPRINTS_COMPARISON_MISMATCH"
        - "HOLO_PHOTO_FACE_NOT_DETECTED"
        - "HOLO_PHOTO_FACE_COMPARISON_FAILED"
        - "HOLO_PHOTO_GLARE_IN_CENTER_ABSENT"
        - "HOLO_PHOTO_HOLO_ELEMENT_SHAPE_ERROR"
        - "HOLO_PHOTO_ALGORITHMS_STEPS_ERROR"
        - "HOLO_PHOTO_HOLO_AREAS_NOT_LOADED"
        - "HOLO_PHOTO_FINISHED_BY_TIMEOUT"
        - "HOLO_PHOTO_DOCUMENT_OUTSIDE_FRAME"
        - "LIVENESS_DEPTH_CHECK_FAILED"
        - "MRZ_QUALITY_WRONG_SYMBOL_POSITION"
        - "MRZ_QUALITY_WRONG_BACKGROUND"
        - "MRZ_QUALITY_WRONG_MRZ_WIDTH"
        - "MRZ_QUALITY_WRONG_MRZ_HEIGHT"
        - "MRZ_QUALITY_WRONG_LINE_POSITION"
        - "MRZ_QUALITY_WRONG_FONT_TYPE"
        - "OCR_QUALITY_TEXT_POSITION"
        - "OCR_QUALITY_INVALID_FONT"
        - "OCR_QUALITY_INVALID_BACKGROUND"
        - "LASINK_INVALID_LINES_FREQUENCY"
        - "DOC_LIVENESS_DOCUMENT_NOT_LIVE"
        - "DOC_LIVENESS_BLACK_AND_WHITE_COPY_DETECTED"
        - "DOC_LIVENESS_ELECTRONIC_DEVICE_DETECTED"
        - "DOC_LIVENESS_INVALID_BARCODE_BACKGROUND"
        - "DOC_LIVENESS_VIRTUAL_CAMERA_DETECTED"
        - "CHD_ICAO_IDB_BASE32_ERROR"
        - "CHD_ICAO_IDB_ZIPPED_ERROR"
        - "CHD_ICAO_IDB_MESSAGE_ZONE_EMPTY"
        - "CHD_ICAO_IDB_SIGNATURE_MUST_BE_PRESENT"
        - "CHD_ICAO_IDB_SIGNATURE_MUST_NOT_BE_PRESENT"
        - "CHD_ICAO_IDB_CERTIFICATE_MUST_NOT_BE_PRESENT"
        - "CHD_INCORRECT_OBJECT_COLOR"
        - "PROPERTY_NO_SIGNATURE"
        - "PROPERTY_TEXT_AS_SIGNATURE"
        - "PROPERTY_FINGERPRINT_AS_SIGNATURE"
      x-enum-descriptions:
        - "Check was not performed"
        - "Check was OK"
        - "Invalid input data"
        - "Internal error in module"
        - "Exception caught"
        - "Can't make reliable decision"
        - "Image in necessary light was not found"
        - "Necessary side of photo was not found"
        - "Invalid checksum"
        - "Syntactical error"
        - "Logical error"
        - "Comparison was incorrect"
        - "Logical error, e.g. the current date is less than issue date"
        - "Wrong field format"
        - "Element of the luminescense in the UV does not meet the standard"
        - "The presence of excess luminescence in UV"
        - "Pattern does not match the standard"
        - "Low contrast of object in transmitted IR light"
        - "Background of page is too light or has invalid color"
        - "Background lightness of two pages is different"
        - "Text has incorrect color of luminescence in UV light"
        - "Invalid luminescence in photo area"
        - "Object is too shifted from standard coordinates"
        - "Contact chip type mismatch"
        - "No protective fibers were found in UV"
        - "Error finding fibers, too many objects"
        - "Speck or exposure in UV image"
        - "Resolution too low for fibers search"
        - "Erroneous visibility of the element in IR"
        - "Element is absent in IR"
        - "Element should be in color"
        - "Element should be in grayscale"
        - "Photo white IR do not match"
        - "Glow paper in MRZ"
        - "Luminescence characters in MRZ"
        - "Glow in the field of photo paper"
        - "Glow of the whole paper form"
        - "Glow of the document in UV"
        - "Element of blank has luminescence"
        - "Violation of the retro-reflective protection"
        - "Invalid params for IPI check"
        - "Encrypted IPI not found, information not decoded"
        - "Decoded data don't match to other data sources"
        - "IR image too bright"
        - "Glares in photo area"
        - "Photo replaced"
        - "Landmarks check error"
        - "Face presence check error"
        - "Face absence check error"
        - "Incorrect head position"
        - "Age check error"
        - "Sex check error"
        - "OVI object is not visible in IR"
        - "Insufficient area of the object OVI"
        - "OVI color of an object does not change"
        - "Impossible to determine the color of the AXIAL image"
        - "Impossible to determine the color of the WHITE image"
        - "Wide color spread"
        - "Not enough color information"
        - "Hologram element absent"
        - "There are no side or top images. Check cancelled"
        - "Hologram element present"
        - "Hologram frames is absent"
        - "Hologram holo field is absent"
        - "Pattern is interrupted"
        - "Some of the patterns are shifted relative to each other"
        - "Some parts of the pattern have different color"
        - "Pattern visible in the infrared"
        - "Edge of the photo does not intersect with the pattern. Check cancelled"
        - "Size of the photo does not correspond to requirements"
        - "Some parts of the pattern have invalid color"
        - "Some patterns are relatively shifted"
        - "Not found pattern, check cancelled"
        - "Different lines thickness"
        - "Photo shape is not rectangular"
        - "Photo corners don't satisfy the requirements"
        - "For internal use"
        - "Text color should be blue"
        - "Text color should be green"
        - "Text color should be red"
        - "Text should be black"
        - "Security text is absent"
        - "Barcode read with errors"
        - "Barcode data format error"
        - "Barcode size parameters error"
        - "This document should contain more barcodes"
        - "Glares in barcode area"
        - "No certificate for digital signature check"
        - "The portraits do not match"
        - "The service does not respond"
        - "Service error"
        - "Not enough images"
        - "There is no camera image"
        - "There is no license for the service"
        - "No portraits detected"
        - "Unsuitable light conditions"
        - "No difference in visible and UV mobile images, possible UV torch malfunction"
        - "Fingerprints comparison mismatch"
        - "Face isn’t detected"
        - "Face comparison failed"
        - "Glare in center absent"
        - "Hologram element shape error"
        - "Algorithm steps error"
        - "Hologram areas not loaded"
        - "Hologram check finished by time out"
        - "Holo photo document outside frame"
        - "Liveness depth check failed"
        - "Wrong mrz dpi"
        - "Wrong background"
        - "MRZ quality: wrong MRZ width"
        - "MRZ quality: wrong MRZ height"
        - "MRZ quality: wrong line position"
        - "MRZ quality: wrong font type"
        - "OCR quality: text position"
        - "OCR quality: invalid font"
        - "OCR quality: invalid background"
        - "Invalid LASINK lines frequency"
        - "Verification failed"
        - "Black and white copy detected"
        - "Traces of an electronic device were found in the image"
        - "Invalid barcode background"
        - "Virtual camera was detected"
        - "Base32 barcode error"
        - "Data decompression error"
        - "Message zone is empty"
        - "Signature must be present"
        - "Signature must not be present"
        - "Certificate reference must not be present"
        - "Incorrect object color"
        - "No signature"
        - "Text as signature"
        - "Fingerprint as signature"
