openapi: 3.0.4
components:
  schemas:
    AuthenticityResultType:
      title: "AuthenticityResultType"
      type: integer
      format: int64
      description: "Enumeration describes available authenticity checks: https://docs.regulaforensics.com/develop/doc-reader-sdk/web-service/development/enums/authenticity-result-type/."
      enum:
        - 0
        - 1
        - 2
        - 4
        - 8
        - 16
        - 32
        - 64
        - 128
        - 256
        - 512
        - 1024
        - 2048
        - 4096
        - 8192
        - 16384
        - 32768
        - 65536
        - 131072
        - 262144
        - 524288
        - 1048576
        - 2097152
        - 4194304
        - 8388608
        - 16777216
        - 2147483648
      x-enum-descriptions:
        - "No authenticity control procedure"
        - "Document luminescence check in UV light"
        - "B900 ink MRZ contrast check in IR light"
        - "Image patterns presence/absence check (position, shape, color)"
        - "Confirm laminate integrity check in axial light"
        - "Protection fibers presence check (color, density) in UV light"
        - "Document elements visibility check in IR light"
        - "OCR for the text field in UV light comparison with other text sources check"
        - "Invisible Personal Information (IPI) visualization"
        - "Document photo check in IR light"
        - "Owner's photo embedding check (is photo printed or sticked)"
        - "OVI check. Deprecated, use Document liveness check instead"
        - "IR luminescence check"
        - "Hologram presence check. Deprecated"
        - "Owner's photo area advanced check (photo shape, size, position, etc.)"
        - "UV background check"
        - "Portrait comparison check (document printed vs chip vs live)"
        - "Barcode format check (code metadata, data format, contents format, etc.)"
        - "Kinegram check"
        - "LetterScreen check"
        - "Hologram detection and validation check"
        - "Fingerprint comparison check"
        - "Document liveness check"
        - "Extended OCR Check"
        - "Extended MRZ check"
        - "Encrypted IPI"
        - "Flag for status-only authenticity"
      x-enum-varnames:
        - "NONE"
        - "UV_LUMINESCENCE"
        - "IR_B900"
        - "IMAGE_PATTERN"
        - "AXIAL_PROTECTION"
        - "UV_FIBERS"
        - "IR_VISIBILITY"
        - "OCR_SECURITY_TEXT"
        - "IPI"
        - "IR_PHOTO"
        - "PHOTO_EMBED_TYPE"
        - "OVI"
        - "IR_LUMINESCENCE"
        - "HOLOGRAMS"
        - "PHOTO_AREA"
        - "UV_BACKGROUND"
        - "PORTRAIT_COMPARISON"
        - "BARCODE_FORMAT_CHECK"
        - "KINEGRAM"
        - "LETTER_SCREEN"
        - "HOLOGRAM_DETECTION"
        - "FINGERPRINT_COMPARISON"
        - "LIVENESS"
        - "EXTENDED_OCR_CHECK"
        - "EXTENDED_MRZ_CHECK"
        - "ENCRYPTED_IPI"
        - "STATUS_ONLY"
