openapi: 3.0.1
components:
  schemas:

    Visibility:
      description: "Enumeration contains visibility status of the security element"
      type: integer
      enum:
        - 0
        - 1
        - 2
        - 4
        - 8
      x-enum-description:
        - "Invisible"
        - "Visible"
        - "Colored"
        - "Grayscale"
        - "Visible vs IR match"
      x-enum-varnames:
        - "INVISIBLE"
        - "VISIBLE"
        - "COLORED"
        - "GRAYSCALE"
        - "WHITE_IR_MATCHING"