openapi: 3.0.3
components:
  schemas:
    IdentResult:
      title: "IdentResult"
      allOf:
        - $ref: "../rt-authenticity.yml#/components/schemas/AuthenticityCheckResultItem"
        - type: object
          required:
            - ElementType
            - LightIndex
            - Area
            - Image
            - EtalonImage
          properties:
            ElementType:
              $ref: "../e-security-feature-type.yml#/components/schemas/SecurityFeatureType"
            LightIndex:
              $ref: "../common.yml#/components/schemas/Light"
            Area:
              $ref: "../common.yml#/components/schemas/RectangleCoordinates"
            Image:
              description: "Original image"
              $ref: "../common.yml#/components/schemas/ImageData"
            EtalonImage:
              description: "Reference image"
              $ref: "../common.yml#/components/schemas/ImageData"
            AreaList:
              $ref: "../rt-authenticity.yml#/components/schemas/AreaContainer"
