openapi: 3.0.4
components:
  schemas:
    PhotoIdentItem:
      title: "PhotoIdentItem"
      type: object
      required:
        - LightIndex
        - Area
        - SourceImage
        - ResultImages
      properties:
        LightIndex:
          $ref: "../common.yml#/components/schemas/Light"
        Area:
          $ref: "../common.yml#/components/schemas/RectangleCoordinates"
        SourceImage:
          $ref: "../common.yml#/components/schemas/ImageData"
        ResultImages:
          $ref: "#/components/schemas/RawImageContainerList"
        FieldTypesCount:
          type: integer
        FieldTypesList:
          type: array
          items:
            type: integer
        Step:
          type: integer
        Angle:
          type: integer
        Result:
          type: integer
        Reserved3:
          type: integer

    RawImageContainerList:
      title: "RawImageContainerList"
      type: object
      required:
        - Count
        - Images
      properties:
        Count:
          type: integer
        Images:
          type: array
          items:
            $ref: "../common.yml#/components/schemas/ImageData"
