name: Back Merge

on:
  push:
    branches:
      - master
      - stable

jobs:
  back-merge:
    uses: regulaforensics/reusable-workflows/.github/workflows/back-merge.yaml@2831e890f7245dfb6944a27891dbd6b98a3be366 # main
    with:
      source_branch: ${{ github.ref_name }}
      merge_pairs: "master:stable,stable:develop"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
