name: Make PRs for client repos

on:
  pull_request:
    branches:
      - feature/automatization-web-clients

#  workflow_dispatch:
#    inputs:
#      source_branch:
#        description: "Source branch"
#        default: "develop"
#        type: choice
#        required: true
#        options:
#          - develop
#          - master
#          - stable
#      target_branch:
#        description: "Target branch"
#        default: "master"
#        type: choice
#        required: true
#        options:
#          - develop
#          - master
#          - stable

jobs:
  create-pr-for-python-client:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout Python Client Repo
#        uses: actions/checkout@4
#        with:
#          repository: 'regulaforensics/DocumentReader-web-python-client'
#          token: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}
#          path: 'python-client'
      - name: Create PR from source to target branch
#        working-directory: python-client
        run: |
          gh pr create --base stable --head develop --title "[GitHub Actions] Merge develop -> stable" --label OpenAPI --body 'Autogenerated PR triggered by Github Actions in OpenAPI repository' --repo regulaforensics/DocumentReader-web-python-client
#          gh pr create --base ${{ github.event.inputs.target }} --head ${{ github.event.inputs.source }} --title "[GitHub Actions] Merge ${{ github.event.inputs.source }} -> ${{ github.event.inputs.target }}" --label OpenAPI --body 'Autogenerated PR triggered by Github Actions in OpenAPI repository' --repo regulaforensics/DocumentReader-web-python-client
        env:
          GITHUB_TOKEN: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}

#
#  update-java-client:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Specify Java Version
#        uses: actions/setup-java@v1
#        with:
#          java-version: 11
#          java-package: jdk
#      - name: Checkout Specification Repo
#        uses: actions/checkout@v2
#        with:
#          path: 'DocumentReader-web-openapi'
#      - name: Checkout Java Client Repo
#        uses: actions/checkout@v2
#        with:
#          repository: 'regulaforensics/DocumentReader-web-java-client'
#          token: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}
#          path: 'java-client'
#      - name: Update Model According To Specification
#        working-directory: java-client
#        run: |
#          ./update-models.sh
#      - name: Push Changes Back To Client Repo
#        working-directory: java-client
#        run: |
#          git checkout -b ${GITHUB_SHA::8}
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add --all
#          git commit -m "${{ github.event.inputs.title }}" -a
#          git push --set-upstream origin ${GITHUB_SHA::8}
#          gh pr create --fill --draft
#        env:
#          GITHUB_TOKEN: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}
#
#  update-python-client:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Specification Repo
#        uses: actions/checkout@v2
#        with:
#          path: 'DocumentReader-web-openapi'
#      - name: Checkout Python Client Repo
#        uses: actions/checkout@v2
#        with:
#          repository: 'regulaforensics/DocumentReader-web-python-client'
#          token: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}
#          path: 'python-client'
#      - name: Update Model According To Specification
#        working-directory: python-client
#        run: |
#          ./update-models.sh
#      - name: Push Changes Back To Client Repo
#        working-directory: python-client
#        run: |
#          git checkout -b ${GITHUB_SHA::8}
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git add --all
#          git commit -m "${{ github.event.inputs.title }}" -a
#          git push --set-upstream origin ${GITHUB_SHA::8}
#          gh pr create --fill --draft
#        env:
#          GITHUB_TOKEN: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}
#
#  update-csharp-client:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Specification Repo
#        uses: actions/checkout@v2
#        with:
#          path: 'DocumentReader-web-openapi'
#      - name: Checkout C# Client Repo
#        uses: actions/checkout@v2
#        with:
#          repository: 'regulaforensics/DocumentReader-web-csharp-client'
#          token: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}
#          path: 'csharp-client'
#      - name: Update Model According To Specification
#        working-directory: csharp-client
#        run: |
#          ./update-models.sh
#      - name: Push Changes Back To Client Repo
#        working-directory: csharp-client
#        run: |
#          git checkout -b ${GITHUB_SHA::8}
#          git config --local user.email "action@github.com"
#          git config --local user.name "GitHub Action"
#          git checkout src/Regula.DocumentReader.WebClient/Api/DefaultApi.cs src/Regula.DocumentReader.WebClient/Api/ProcessApi.cs
#          git add --all
#          git commit -m "${{ github.event.inputs.title }}" -a
#          git push --set-upstream origin ${GITHUB_SHA::8}
#          gh pr create --fill --draft
#        env:
#          GITHUB_TOKEN: ${{ secrets.REGULA_GITHUB_PUSH_TOKEN }}
