name: validate specification

on:
  pull_request:
    branches:
      - master
      - develop
      - stable

jobs:
  validate-specification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install redoc
        run: |
          npm install -g @redocly/cli
          redocly build-docs index.yml

      - name: Revert changes
        if: ${{ false }}
        run: |
          npm install -g @openapitools/openapi-generator-cli
          openapi-generator-cli validate --recommend -i index.yml
