name: validate specification

on:
  pull_request:
    branches:
      - master
      - develop
      - stable

jobs:
  validate-specification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Install redoc
        run: |
          npm install -g @redocly/cli
          redocly build-docs index.yml

      - name: Revert changes
        if: ${{ false }}
        run: |
          npm install -g @openapitools/openapi-generator-cli
          openapi-generator-cli validate --recommend -i index.yml
